dotnet/docker-tools

- src/Microsoft.DotNet.ImageBuilder/CommandType.cs
- src/Microsoft.DotNet.ImageBuilder/ImageBuilder.cs
- src/Microsoft.DotNet.ImageBuilder/Model/Manifest.cs
- src/Microsoft.DotNet.ImageBuilder/Options.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/ManifestInfo.cs
> Add support for updating the Full Description in Docker Hub.

- src/Microsoft.DotNet.ImageBuilder/ImageBuilder.cs
- src/Microsoft.DotNet.ImageBuilder/Model/Image.cs
- src/Microsoft.DotNet.ImageBuilder/Model/Manifest.cs
- src/Microsoft.DotNet.ImageBuilder/Model/Repo.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/ImageInfo.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/ManifestInfo.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/PlatformInfo.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/RepoInfo.cs
- Refactored to support building images that are from multiple Docker Hub repos.
- Refactored manifest model to validate required properties.
- Refactored code to handle optional manifest properties.
- Fixed issue related to test commands that have no arguments.
> Changes needed to build the aspnet-docker images

- src/Microsoft.DotNet.ImageBuilder/ImageBuilder.cs
> Add simple retry on manifest-tool failure

- src/Microsoft.DotNet.ImageBuilder/ImageBuilder.cs
- src/Microsoft.DotNet.ImageBuilder/Options.cs
- src/Microsoft.DotNet.ImageBuilder/Utilities.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/ImageInfo.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/ManifestInfo.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/ModelExtensions.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/PlatformInfo.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/RepoInfo.cs
- Add support to build Dockerfiles for a specific repo
- Add support to build Dockerfiles within a specific path
- Refactored logic that detects FROM image to support the mult-stage builds feature which allows multiple FROM commands within a Dockerfile
Related #24 
Related #25
> Add support for building subset of images

- src/Microsoft.DotNet.ImageBuilder/ImageBuilder.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/ImageInfo.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/ManifestInfo.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/PlatformInfo.cs
> Refactor pull logic and rename view model `Tag` properties

- src/Microsoft.DotNet.ImageBuilder/Commands/PublishManifestCommand.cs
- src/Microsoft.DotNet.ImageBuilder/Dockerfile
> Upgrade manifest-tool version and make use of tags element

- src/Microsoft.DotNet.ImageBuilder/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/Commands/BuildOptions.cs
- src/Microsoft.DotNet.ImageBuilder/Commands/Command.TOptions.cs
- src/Microsoft.DotNet.ImageBuilder/Commands/DockerRegistryOptions.cs
- src/Microsoft.DotNet.ImageBuilder/Commands/GenerateTagsReadmeCommand.cs
- src/Microsoft.DotNet.ImageBuilder/Commands/ICommand.cs
- src/Microsoft.DotNet.ImageBuilder/Commands/Options.cs
- src/Microsoft.DotNet.ImageBuilder/Commands/PublishManifestCommand.cs
- src/Microsoft.DotNet.ImageBuilder/Commands/PublishManifestOptions.cs
- src/Microsoft.DotNet.ImageBuilder/Commands/UpdateReadmeCommand.cs
- src/Microsoft.DotNet.ImageBuilder/Commands/UpdateReadmeOptions.cs
- src/Microsoft.DotNet.ImageBuilder/Commands/UpdateVersionsCommand.cs
- src/Microsoft.DotNet.ImageBuilder/Commands/UpdateVersionsOptions.cs
- src/Microsoft.DotNet.ImageBuilder/DockerHelper.cs
- src/Microsoft.DotNet.ImageBuilder/ImageBuilder.cs
- src/Microsoft.DotNet.ImageBuilder/Microsoft.DotNet.ImageBuilder.csproj
- src/Microsoft.DotNet.ImageBuilder/NuGet.config
- src/Microsoft.DotNet.ImageBuilder/Utilities.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/ManifestFilter.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/ManifestInfo.cs
> Add command that persists base image version info

- src/Microsoft.DotNet.ImageBuilder/Commands/Command.TOptions.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/ModelExtensions.cs
> Add manifest validation

- src/Microsoft.DotNet.ImageBuilder/Commands/BuildOptions.cs
- src/Microsoft.DotNet.ImageBuilder/Commands/Options.cs
- src/Microsoft.DotNet.ImageBuilder/Commands/UpdateVersionsOptions.cs
> Add Architecture option to UpdateDependenciesCommand

- src/Microsoft.DotNet.ImageBuilder/Dockerfile
- src/Microsoft.DotNet.ImageBuilder/Dockerfile.nanoserver
Related to #16 
This reduces the image sizes substantially.
Linux => 1.81GB to 398 MB
Windows => 2.83GB to 1.14 GB
> Update Dockerfiles to be multi-staged

- src/Microsoft.DotNet.ImageBuilder/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/Commands/GenerateTagsReadmeCommand.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/PlatformInfo.cs
> Add support for multiple Dockerfiles in same dir

- src/Microsoft.DotNet.ImageBuilder/ImageBuilder.cs
Display version of Docker using -
```C#
ExecuteHelper.ExecuteWithRetry(fileName: "docker", args: "version", isDryRun: false);
```
> Display version of Docker being used.

- src/Microsoft.DotNet.ImageBuilder/ViewModel/ManifestFilter.cs
Adding `$` anchor in regex pattern for path ensures full match of Dockerfile path string.
> Include end of line anchor in regex for path.

- src/Microsoft.DotNet.ImageBuilder/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/Commands/Command.TOptions.cs
- src/Microsoft.DotNet.ImageBuilder/Commands/Options.cs
- src/Microsoft.DotNet.ImageBuilder/DockerHelper.cs
- src/Microsoft.DotNet.ImageBuilder/ExecuteHelper.cs
> Update Docker login logic and add verbose option

- src/Microsoft.DotNet.ImageBuilder/Commands/BuildOptions.cs
- src/Microsoft.DotNet.ImageBuilder/Model/Platform.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/ManifestFilter.cs
Fixes https://github.com/dotnet/dotnet-docker-samples/issues/90
This [PR](https://github.com/dotnet/dotnet-docker-samples/compare/nano-1709?expand=1#diff-4b1eb3dc48c4e16d49db5b42298fe654) illustrates what the manifest would look like with this change.
> Add support for OS Version in manifest

- src/Microsoft.DotNet.ImageBuilder/DockerHelper.cs
The [changes ](https://github.com/dotnet/docker-tools/commit/1452ac24c24f7dae94e4990792c269574ad66719) recently made to make use of the newish Docker login `--password-stdin` option can't be the only login option as image-builder is being used on machines with older versions of docker.  This change adds support to detect which version exists and use the appropriate login options.
> Add support for logging in across multiple versions of Docker

- src/Microsoft.DotNet.ImageBuilder/Commands/GenerateTagsReadmeCommand.cs
- src/Microsoft.DotNet.ImageBuilder/Commands/PublishManifestCommand.cs
- src/Microsoft.DotNet.ImageBuilder/DockerHelper.cs
- src/Microsoft.DotNet.ImageBuilder/Model/EnumKeyDictionaryConverter.cs
- src/Microsoft.DotNet.ImageBuilder/Model/Manifest.cs
- src/Microsoft.DotNet.ImageBuilder/Model/OS.cs
- src/Microsoft.DotNet.ImageBuilder/Model/Platform.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/ManifestFilter.cs
> Add GenerateTagsReadmeSupport for Windows Server RS3 tags

- src/Microsoft.DotNet.ImageBuilder/Commands/GenerateTagsReadmeCommand.cs
- src/Microsoft.DotNet.ImageBuilder/Commands/GenerateTagsReadmeOptions.cs
> Added --update-readme option to generateTagsReadme

- Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
> Add message indicating no tests found

- Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/TagInfo.cs
> Add logic to handle stage references in FROM instructions

- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateTagsReadmeCommand.cs
Related to dotnet/dotnet-docker#397
> Fixup Nano Server tags readme heading

- Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- Microsoft.DotNet.ImageBuilder/src/ImageBuilder.cs
Also added logic to capture the `docker info`.  This is useful to capture in the build output.
Fixes #105
> Add retry logic to logout

- Microsoft.DotNet.ImageBuilder/src/Commands/BuildOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/CopyImagesOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/IManifestFilterOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/Options.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestFilter.cs
This supports the following `build --path 2.1* --path 2.2*`
> Add support for multiple path options w/build command

- .vsts-pipelines/build.yml
- Microsoft.DotNet.ImageBuilder/tests/Microsoft.DotNet.ImageBuilder.Tests.csproj
Related to https://github.com/dotnet/dotnet-docker/issues/743
> Add Azure DevOps build definition

- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateTagsReadmeCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Model/Tag.cs
> Add a documentation group concept

- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateTagsReadmeCommand.cs
Related to #119
Fixed an issue where the correct `ImageDocumentationInfo` was not getting found when looking up `TagDoc` variables.
> Update generateTagsDocumentation to correctly match doc groups

- Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ImageInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/RepoInfo.cs
This is a requirement to support https://github.com/dotnet/dotnet-docker/pull/860/files.
> Add support for ARG references in FROM statements

- Microsoft.DotNet.ImageBuilder/src/AzureHelper.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/CopyAcrImagesCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/CopyAcrImagesOptions.cs
- Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- Microsoft.DotNet.ImageBuilder/src/ImageBuilder.cs
- Microsoft.DotNet.ImageBuilder/src/StringExtensions.cs
This is being added to support moving to our Docker repos to MCR.
> Add CopyAcrImages command to support fast coping within Azure

- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
1. With the recent changes to add the Linux distro variant info in the Manifest, the build matrix now inadvertently includes the distro in the matrix entry names.  This change will ignore the osVersion for Linux entries.
2. Modified the build matrix logic to retrieve the osVariant test variable from the Manifest's osVersion.
> Update generateBuildMatrix to ignore OsVersion for grouping Linux entries

- Microsoft.DotNet.ImageBuilder/src/Commands/RebuildStaleImagesCommand.cs
The RebuildStaleImageCommand wasn't correctly caching the extracted repo paths.  This messed up the cleanup logic which would delete the unzipped repos at the end of the command.
> Fix RebuildStaleImageCommand cleanup

- .vsts-pipelines/variables/docker-images.yml
Updates the referenced tag in order to get the fix from 139b4cfa61e76d5c52d1d5878b4cf5b37a9ea9cb.
> Update Image Builder tag

- .vsts-pipelines/cleanup-acr-images.yml
- scripts/Invoke-AcrCleanup.ps1
- scripts/Invoke-ImageBuilder.ps1
> Add build pipeline to cleanup old ACR images

- eng/common/templates/variables/docker-images.yml
- eng/pipelines/templates/steps/queue-build-for-stale-images.yml
Misc fixes on the build to get it running after the common engineering folder integration.
> Fix stale image build

- eng/pipelines/cleanup-acr-images.yml
Set the build to run every night.
> Add build schedule for ACR cleanup build

- Microsoft.DotNet.ImageBuilder/src/Commands/RebuildStaleImagesCommand.cs
The algorithm for generating the set of path variables in the RebuildStaleImages command had a bug in it that allowed for certain Dockerfile paths from being skipped in the analysis.  This was due to the code that kept tracked of images that had already been processed, the `processedImages` variable.  If it was determined that the Dockerfile's base image had already been processed, it would skip the Dockerfile completely.  The intention is actually to skip pulling the image and querying for its digest since that already already been done before but to still continue with comparing the digest values.  The code has been fixed to do that.
> Fix path variable generation code in RebuildStaleImages

- eng/common/templates/jobs/build-images.yml
- eng/common/templates/jobs/publish.yml
- eng/common/templates/steps/download-build-artifact.yml
- eng/common/templates/steps/init-docker-linux.yml
- eng/common/templates/steps/init-docker-windows.yml
- eng/common/templates/steps/test-images-linux-client.yml
- eng/common/templates/steps/test-images-windows-client.yml
- eng/common/templates/variables/docker-images.yml
Updates the common/eng folder with the latest changes that had been made in dotnet-docker/nightly.
> Update common/eng folder

- Microsoft.DotNet.ImageBuilder/.dockerignore
- Microsoft.DotNet.ImageBuilder/Dockerfile.debian
- Microsoft.DotNet.ImageBuilder/Dockerfile.nanoserver
- Microsoft.DotNet.ImageBuilder/build.ps1
- Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
- Microsoft.DotNet.ImageBuilder/tests/Microsoft.DotNet.ImageBuilder.Tests.csproj
> Update Image-Builder to use .NET Core 3.0

- eng/common/templates/steps/test-images-linux-client.yml
- eng/common/templates/steps/test-images-windows-client.yml
Integrates the changes from https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/158
> Integrate latest eng common changes

- eng/common/templates/jobs/publish.yml
- eng/common/templates/variables/common.yml
Integrates the latest changes that were made in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/163
> Integrate latest changes to eng/common

- Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
> Exclude IsLocal tags from image info output

- eng/common/templates/steps/test-images-linux-client.yml
- eng/common/templates/steps/test-images-windows-client.yml
> Drop Window/Linux from Publish Test Results testRunTile

- Microsoft.DotNet.ImageBuilder/src/Commands/CopyAcrImagesCommand.cs
The code in the CopyAcrImagesCommand class is creating an IAzure object and passing it to multiple methods that are executed in parallel and making requests with that object.  Apparently this is not a thread-safe object because this behavior results in a NullReferenceException:
```
System.NullReferenceException: Object reference not set to an instance of an object.
at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at Microsoft.Azure.Management.ContainerRegistry.Fluent.RegistriesOperations.B …
```
> Avoid using IAzure object in parallel

- eng/common/Invoke-CleanupDocker.ps1
Migration of https://github.com/dotnet/dotnet-docker/pull/1259.
> Refactor Invoke-CleanupDocker.ps1 to preserve the eng infra images to avoid re-pulls

- eng/common/Invoke-ReadmeGeneration.ps1
- eng/common/build-and-test.ps1
Migrating changes from https://github.com/microsoft/dotnet-framework-docker/pull/346
> Migrating eng/common changes introduced in dotnet-framework-docker

- eng/pipelines/dotnet-buildtools-image-builder-official.yml
> Add trigger path to only build ImageBuilder when its source is changed

- eng/common/templates/jobs/test-images-linux-client.yml
- eng/common/templates/jobs/test-images-windows-client.yml
- eng/common/templates/stages/build-test-publish-repo.yml
> Allow timeout of test jobs to be configurable

- eng/check-base-image-subscriptions.json
> Add subscription for dotnet-docker master branch

- Microsoft.DotNet.ImageBuilder/src/Models/Manifest/Tag.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ModelExtensions.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/VariableHelper.cs
> Remove unused Tag.Id manifest property

- eng/check-base-image-subscriptions.json
Fixes #309
Also adds a subscription for .NET Fx Samples.
> Update base image subscriptions

- Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/GitOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoOptions.cs
- Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
- Microsoft.DotNet.ImageBuilder/tests/GetStaleImagesCommandTests.cs
> Consume repo-specific image info files for GetStaleImagesCommand

- eng/common/Invoke-ReadmeGeneration.ps1
Fixes regression introduced in https://github.com/dotnet/docker-tools/pull/328.
> Fix break in Invoke-ReadmeGeneration.ps1

- src/Microsoft.DotNet.ImageBuilder/src/Commands/ValidateImageSizeCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/ValidateImageSizeCommandTests.cs
> Skip image pulls on image size baseline integrity checks

- eng/file-pusher/Dockerfile
- eng/file-pusher/file-pusher.csproj
- src/Microsoft.DotNet.ImageBuilder/Dockerfile.debian
- src/Microsoft.DotNet.ImageBuilder/Dockerfile.nanoserver
- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
- src/Microsoft.DotNet.ImageBuilder/tests/Microsoft.DotNet.ImageBuilder.Tests.csproj
> Upgraded projects to .NET Core 3.1

- src/Microsoft.DotNet.ImageBuilder/tests/GetStaleImagesCommandTests.cs
This is a very clean repo for spelling and grammatical errors!  I'm checking to see if pr triggers are working ( @mthalman  reported issue)
> Fix typo to test PR automation

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GetStaleImagesCommandTests.cs
Fixes #205  
Fixes #343 
* Tweaked getStaleImages to only inspect the final stage of multi-stage Dockerfiles
* Added unit tests to cover multi-stage Dockerfile scenarios
* Enhanced the logging of getStaleImages
> Fix multi-stage Dockerfile support in getStaleImage and enhance logging

- eng/common/templates/jobs/validate-image-sizes.yml
- eng/common/templates/steps/validate-image-sizes.yml
Migrates the `eng/common` changes from https://github.com/dotnet/dotnet-docker/pull/1655 to this repo.
> Update image size validation job

- eng/Invoke-AcrCleanup.ps1
Updates the script to cleanup ACR by including untagged images in the nightly repos.
Fixes #378
> Cleanup untagged nightly images

- eng/common/build.ps1
Migrates the changes to refactor the common build script from https://github.com/dotnet/dotnet-docker/pull/1654.
> Refactor common build script

- eng/common/Invoke-CleanupDocker.ps1
- eng/common/templates/steps/cleanup-docker-linux.yml
> Update scripts to clean up untagged images

- eng/pipelines/dotnet-buildtools-image-builder-pr.yml
- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/PlatformData.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GetStaleImagesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Helpers/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/ImageInfoHelperTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/MergeImageInfoFilesCommandTests.cs
Fixes https://github.com/dotnet/dotnet-docker/issues/1668
> Store the digest of only the final stage's base image

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/ImageData.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/ImageInfoHelperTests.cs
> Include shared tag data in image info output

- eng/check-base-image-subscriptions.json
- eng/pipelines/check-base-image-updates.yml
Hooks up the pipeline to check base image updates for the dotnet-docker/nightly branch.
> Update "check base image" pipeline

- eng/pipelines/check-base-image-updates.yml
Still working through some issues in getting the feature/image-info-schema branch to get scheduled for build.  Trying some changes to make sure that it's in sync with the master branch.
> Fix issue with feature branch build not getting scheduled

- eng/common/templates/jobs/publish.yml
- eng/common/templates/variables/docker-images.yml
> Integrate ingestKustoImageInfo command into the builds

- eng/common/templates/stages/build-test-publish-repo.yml
> Add build/test legs for Windows, version 2004

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishMcrDocsCommand.cs
The `publishMcrDocs` command computes one product family for the entire manifest when publishing.  Now that we have `dotnet/core-nightly` and `dotnet/nightly`, this doesn't work.  It ends up putting all the readmes into a single folder: `teams/dotnet/core-nightly`.  Fixed the logic to compute the product family from each repo name.
> Fix publishMcrDocs to handle different product repos

- eng/common/templates/steps/cleanup-docker-linux.yml
> Update build cleanup logic to use /bin/sh vs /bin/bash

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateBuildMatrixCommandTests.cs
Updates the logic to generate a build matrix so that it supports scenarios where there's a build job dependency between Dockerfiles for Windows Server Core and Nano Server.  This allows us to take advantage of Docker's layer caching within a local build where Dockerfiles don't have a direct dependency but have shared content that the cache can be used with.  The goal is to build those Dockerfiles in the same job to take advantage of the layer caching.
One minor aspect needed to be addressed first to support this which was to treat Windows Server Core and Nano Server as equivalent from a platform perspective such that they wouldn't be placed in distinct jobs if all else was equal.  This was accomplished by adding a `NormalizedOsVersion` property to the `PlatformId` class.
The rest of the …
> Build matrix support for building nano and server core

- eng/common/templates/variables/docker-images.yml
Related to https://github.com/dotnet/docker-tools/issues/486
> Reference multi-arch tag of testrunner

- eng/common/build.ps1
Backporting the build.ps1 changes made with dotnet/dotnet-docker#1972
> Backport changes to support src directory in build.ps1

- eng/common/templates/jobs/generate-matrix.yml
- eng/common/templates/jobs/post-build.yml
- eng/common/templates/jobs/validate-image-sizes.yml
- eng/common/templates/stages/build-test-publish-repo.yml
- eng/common/templates/variables/common.yml
- eng/pipelines/check-base-image-updates.yml
- eng/pipelines/cleanup-acr-images-custom.yml
- eng/pipelines/cleanup-acr-images.yml
- eng/pipelines/push-common-updates.yml
> Update pipelines to use ubuntu-latest VM image

- eng/common/templates/jobs/build-images.yml
- eng/common/templates/jobs/test-images-linux-client.yml
- eng/common/templates/stages/build-test-publish-repo.yml
- eng/common/templates/steps/cleanup-docker-linux.yml
- eng/common/templates/steps/init-docker-linux.yml
- eng/common/templates/steps/test-images-linux-client.yml
- eng/pipelines/check-base-image-updates.yml
- eng/pipelines/templates/steps/get-stale-images.yml
Fixes https://github.com/dotnet/docker-tools/issues/486
> Use ARM64-enabled build agents in all build environments

- eng/common/Invoke-ImageBuilder.ps1
This optimization is nice when you are repeatedly running the Invoke-ImageBuilder script locally.  Given the ImageBuilder tags are unique per build, there is no need to repull the image if it already exists locally.
> Add pull ImageBuilder optimization to Invoke-ImageBuilder script

- eng/pipelines/cleanup-acr-images.yml
> Prune dangling sample images

- eng/common/templates/jobs/build-images.yml
- eng/common/templates/jobs/test-images-linux-client.yml
- eng/common/templates/stages/build-test-publish-repo.yml
- eng/common/templates/steps/test-images-linux-client.yml
- eng/tests/pipeline-validation/run-tests.ps1
- src/Microsoft.DotNet.ImageBuilder/run-tests.ps1
Backporting the pre-build validation infrastructure that was introduced in https://github.com/dotnet/dotnet-docker/pull/2114 as part of #1933
> Add pre-build validation to common build infrastructure

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerService.cs
- src/Microsoft.DotNet.ImageBuilder/src/IDockerService.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
> Validate build doesn't cause an inadvertent pull

- eng/common/templates/jobs/generate-matrix.yml
- eng/common/templates/stages/build-test-publish-repo.yml
- eng/common/templates/steps/test-images-linux-client.yml
- eng/common/templates/steps/test-images-windows-client.yml
- eng/common/templates/variables/docker-images.yml
Updates the Image Builder tag to use the changes from https://github.com/dotnet/docker-tools/pull/594
> Update ImageBuilder tag

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateDockerfilesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateDockerfilesOptions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateDockerfilesCommandTests.cs
> Refactor generateDockerfiles to ensure templates are defined

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateTagsReadmeCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateTagsReadmeOptions.cs
Related to https://github.com/dotnet/dotnet-docker/issues/1618
> Add 'Validate' option to the generatedTagsReadMe command

- eng/common/Invoke-ReadmeGeneration.ps1
Related https://github.com/dotnet/dotnet-docker/issues/1618
> Update Invoke-ReadmeGeneration.ps1 to support validate option.

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
A build that results in a cache hit will fail when a subsequent dependent image is checked for whether it is cached.  For example, if `runtime-deps` is a cache hit, then a failure will occur when checking whether `runtime` is a cache hit or miss.  The failure occurs when calling the manifest tool to get the digest of the base image (`runtime-deps` in this example) because the tag doesn't exist in the registry.  That's because the tag being queried is the staging location but it hasn't been pushed yet.
To fix this, an image digest cache was introduced so that it can be pre-populated with the digest value for each of the staging location tags when the cached image is pulled.  This ensures it will never attempt to call the manifest tool with that tag.
> Fix digest retrieval for cached images

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
Fixes up the `build` command to avoid doing unnecessary work to generate an image info model in the case when no image info output file path has been specified.  The most significant aspect of this is not having to retrieve image digests.
> Optimize build to not generate image info unnecessarily

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishManifestCommandTests.cs
Fix the manifest publishing logic to skip any images that do not define a manifest.
> Fix manifest publishing

- src/Microsoft.DotNet.ImageBuilder/src/McrTagsMetadataGenerator.cs
- src/Microsoft.DotNet.ImageBuilder/tests/McrTagsMetadataGeneratorTests.cs
With the changes being done for dotnet/dotnet-docker#2182, it will cause a platform to be defined multiple times in a manifest, contained in separate images.  This requires changes to `McrTagsMetadataGenerator` in order to correctly handle this scenario because, otherwise, it will throw an exception during validating saying that no tags were defined in the template for the duplicated platform.
The logic that's necessary here is that the lookup logic of a tag specified in the tags metadata template file needs to find not only the platform which defines that tag, but also any other platforms that match it.  It needs to combine the tags for all those platforms into one entry.
> Readme generation support for duplicate platforms

- eng/common/templates/stages/build-test-publish-repo.yml
> Add build/test job support for Windows, version 2009

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
The image info output of `BuildCommand` is incorrect for platforms defined in the manifest that have been duplicated in order to declare them in separate images and do not define concrete tags.  Those duplicated platforms do not have their Digest and Created fields set.
This happens because the code which sets those values does so by querying Docker based on the platform's concrete tags.  Since the platform has no concrete tags, those platforms do not get the digest and created date info set.
To fix this, there's a post-processing step added to the logic which finds the matching platform for each of these platforms without concrete tags.  It finds the matching platform that does its data set and copies the necessary data from it.
> Set image info data for duplicated platforms

- src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/ImageInfoHelperTests.cs
> Fix product version comparison when loading image info

- eng/common/Get-ImageBuilder.ps1
- eng/common/Invoke-ImageBuilder.ps1
Migrates the eng/common changes that were made in https://github.com/dotnet/dotnet-docker/pull/2404
> Provide common script for pulling ImageBuilder

- eng/common/templates/stages/build-test-publish-repo.yml
- eng/common/templates/variables/docker-images.yml
Ports some changes to the common eng infra:
* Port of https://github.com/dotnet/dotnet-docker/pull/2411
* Update ImageBuilder tag
> Port common infra updates

- eng/common/Install-DotNetSdk.ps1
> Update .NET SDK install to 5.0

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateDockerfilesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateDockerfilesCommandTests.cs
This is required for https://github.com/microsoft/dotnet-framework-docker/issues/616 as demonstrated in https://github.com/microsoft/dotnet-framework-docker/pull/705
> Add PRODUCT_VERSION Dockerfile template symbol

- eng/file-pusher/FilePusher.cs
- eng/file-pusher/NuGet.config
- eng/file-pusher/Options.cs
- eng/file-pusher/file-pusher.csproj
Related to https://github.com/dotnet/docker-tools/issues/154
> Update System.CommandLine version for FilePusher

- eng/file-pusher/FilePusher.cs
The changes in https://github.com/dotnet/docker-tools/pull/736 didn't correctly make use of the options that are passed into the `ExecuteAsync` method.
> Fix use of options in FilePusher

- src/Microsoft.DotNet.ImageBuilder/src/Commands/IngestKustoImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/IngestKustoImageInfoOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Services/IKustoClient.cs
- src/Microsoft.DotNet.ImageBuilder/src/Services/KustoClient.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Helpers/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/IngestKustoImageInfoCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Microsoft.DotNet.ImageBuilder.Tests.csproj
> Add IngestKustoImageInfoCommand support for layers

- eng/pipelines/check-base-image-updates.yml
- eng/pipelines/cleanup-acr-images.yml
- eng/pipelines/dotnet-buildtools-image-builder-official.yml
- eng/pipelines/dotnet-buildtools-image-builder-pr.yml
- eng/pipelines/dotnet-docker-tools-eng-validation-pr.yml
- eng/pipelines/dotnet-docker-tools-eng-validation.yml
- eng/pipelines/push-common-updates.yml
> Remove pipeline triggers for master branch

- src/Microsoft.DotNet.ImageBuilder/src/Commands/IngestKustoImageInfoCommand.cs
Small tweak to make the logging more readable.
Related to #719
> Enhance IngestKustoImageInfoCommand logging

- eng/file-pusher/NuGet.config
- src/Microsoft.DotNet.ImageBuilder/NuGet.config
@mmitche - We need the following packages added to `dotnet-public`:
* [Cottle](https://www.nuget.org/packages/Cottle/)
* [Polly.Contrib.WaitAndRetry](https://www.nuget.org/packages/Polly.Contrib.WaitAndRetry/)
* [GiGraph.Dot](https://www.nuget.org/packages/GiGraph.Dot/)
* [Sprache](https://www.nuget.org/packages/Sprache/)
> Fixup feed

- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyBaseImagesCommand.cs
> Fix CopyBaseImages cmd to get the correct registry value

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerService.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerServiceCache.cs
- src/Microsoft.DotNet.ImageBuilder/src/IDockerService.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/ManifestToolServiceExtensions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
Fixed #773 
I have validated this e2e with a test build - https://dev.azure.com/dnceng/internal/_build/results?buildId=1025102&view=logs&j=739bb7ec-7296-5b40-7dff-ee3297bfdaa4&t=78db2542-c627-4140-8a7a-d06178fff4e4 (internal link)
> Refactor image-info layer retrieval logic

- eng/common/templates/jobs/build-images.yml
- eng/common/templates/jobs/copy-base-images.yml
- eng/common/templates/jobs/generate-matrix.yml
- eng/common/templates/jobs/publish.yml
- eng/common/templates/stages/build-test-publish-repo.yml
- eng/common/templates/steps/set-dry-run.yml
- eng/common/templates/variables/common.yml
- eng/common/templates/variables/docker-images.yml
Port of https://github.com/dotnet/dotnet-docker/pull/2617
Related to https://github.com/dotnet/docker-tools/issues/613
> Consume mirrored tags in build pipeline

- eng/common/templates/stages/build-test-publish-repo.yml
Related to https://github.com/dotnet/docker-tools/issues/785
> Remove Windows Server, version 1909 build/test legs

- eng/common/templates/steps/publish-readmes.yml
- eng/common/templates/variables/docker-images.yml
Port of https://github.com/dotnet/dotnet-docker/pull/2817
Fixes dotnet/dotnet-docker#2361
> Set exclude-product-family readme option for nightly branch

- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
Related to https://github.com/dotnet/docker-tools/issues/798
> Add display name for Windows Server 2022

- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
- src/Microsoft.DotNet.ImageBuilder/src/RetryHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/Services/KustoClient.cs
To handle the throttling exception, I've added the same retry logic we use for similar scenarios.
Fixes #800
> Add retry to Kusto ingestion

- eng/common/templates/variables/docker-images.yml
- eng/pipelines/check-base-image-updates.yml
Enable the new build notifications feature from https://github.com/dotnet/docker-tools/pull/790.
> Enable build notifications

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
> Remove check for fully-qualified digest value

- eng/common/templates/jobs/publish.yml
- eng/eng-common-file-pusher-config.json
- eng/image-builder-tag-update-config.json
- eng/pipelines/push-common-updates.yml
- eng/pipelines/update-image-builder-tag.yml
- eng/src/file-pusher/Dockerfile
- eng/src/file-pusher/FilePusher.cs
- eng/src/file-pusher/Models/Config.cs
- eng/src/file-pusher/Models/GitRepo.cs
- eng/src/file-pusher/NuGet.config
- eng/src/file-pusher/Options.cs
- eng/src/file-pusher/file-pusher.csproj
- eng/src/tools.sln
- eng/src/yaml-updater/Dockerfile
- eng/src/yaml-updater/NuGet.config
- eng/src/yaml-updater/Options.cs
- eng/src/yaml-updater/YamlUpdater.cs
- eng/src/yaml-updater/yaml-updater.csproj
Defines a pipeline which updates the referenced Image Builder tag variable with a new tag value.  This pipeline gets triggered after the completion of the Image Builder pipeline.
Fixes #226
> Automatically create PR to reference new Image Builder tag

- eng/common/templates/stages/build-test-publish-repo.yml
Related to https://github.com/dotnet/docker-tools/issues/798
> Add build/test leg support for WS 2022

- eng/common/templates/jobs/copy-base-images.yml
> Copy base images should ignore dry run for internal builds

- eng/common/Install-DotNetSdk.ps1
- eng/common/Invoke-WithRetry.ps1
- src/Microsoft.DotNet.ImageBuilder/src/AcrClient.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyBaseImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishMcrDocsCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/GitHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/GitHubClientFactory.cs
- src/Microsoft.DotNet.ImageBuilder/src/HttpPolicyBuilder.cs
- src/Microsoft.DotNet.ImageBuilder/src/McrStatusClient.cs
- src/Microsoft.DotNet.ImageBuilder/src/RetryHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/Services/AzdoGitHttpClientFactory.cs
- src/Microsoft.DotNet.ImageBuilder/src/Services/VssConnectionFactory.cs
- src/Microsoft.DotNet.ImageBuilder/src/SubscriptionHelper.cs
> Adds retry logic to network requests

- src/Microsoft.DotNet.ImageBuilder/manifest.json
> Define floating tags for Image Builder

- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
Needed to support https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/510
> Add display name support for Ubuntu 21.04

- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
Supports the changes in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/512
> Add display name support for openSUSE Leap

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateImageGraphCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetBaseImageStatusCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/ImageSizeCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PullImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/UpdateImageSizeBaselineCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/ValidateImageSizeCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerService.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerServiceCache.cs
- src/Microsoft.DotNet.ImageBuilder/src/IDockerService.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageDigestCache.cs
- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/PlatformData.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Helpers/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishManifestCommandTests.cs
In preparation for #871, I'm enabling nullable reference types for a select set of classes.
> Enable nullable ref types

- eng/pipelines/upload-file.yml
This provides a secure means to upload arbitrary files to the storage account.
> Pipeline to upload files to storage account

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildOptions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
> Support build args passed from pipeline

- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
Related to https://github.com/dotnet/dotnet-docker/issues/3350
> Add display name support for Ubuntu 22.04

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerService.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerServiceCache.cs
- src/Microsoft.DotNet.ImageBuilder/src/IDockerService.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
> Remove dead architecture modification code

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateArtifactsCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateDockerfilesCommandTests.cs
There can be cases where a given artifact file is processed multiple times for artifact generation. For example, a given runtime-deps Dockerfile can be listed multiple times in the manifest file because it is shared in different contexts (across multiple .NET versions). The current logic ends up processing regenerating the artifact file each time which is problematic in certain cases.
If the template file associated with such an artifact file relies on variable state which is different between the two generation calls, it will end up overwriting the content of a previous generation. Using the example of a runtime-deps Dockerfile, if the template were to conditionally output content based on the `PRODUCT_VERSION` symbol, this value will be different depending on whether the generation call …
> Generate artifacts: handle multiple entries for a path

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PullImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
As described in https://github.com/dotnet/dotnet-docker/pull/3491, there are build agent space issues we need to handle when using the `pullImages` command. When the `--image-info` option is used for this command, it ends up pulling _all_ images described in that image info file.
To make things easier, it would be better to allow the caller to apply manifest filtering to the results. This would allow the caller to specify `--architecture amd64`, for example, to only pull images with the amd64 architecture that are described in the image info file.
To do this, I've extended the image info loading behavior to allow lookups to be made with the filtered content of the manifest. The caller can then filter out items that don't have an associated manifest item.
> Support filtering of image info content for pullImages command

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PostPublishNotificationCommand.cs
In order to avoid hitting GitHub's message body length limit when posting publish notifications, we need to trim the amount of text we're generating to describe the published images.
There's a lot of duplicate content in the tag names because the registry and repo are included. By breaking things up into a hierarchical view with a repo header, we can avoid all that duplication.
I also fixed the repo name because it wasn't including the repo prefix. It's important to have that information when we start enabling support for internal builds which will use a different repo prefix from our publish operations meant for public consumption.
```markdown
* sha256:049e447033362029fa9c8362e1ecdc62342f5f5eff191955593c6f3942eba74a
* dotnetdocker.azurecr.io/dotnet/nightly/aspnet:7.0-windowsservercore-lts …
```
> Publish notifications: Trim repo from tag name

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateBuildMatrixCommandTests.cs
These changes ensure that the same set of Dockerfiles aren't build across multiple build jobs with the `platformVersionedOs` matrix type, the default for PR builds.
Up to this point, this consolidation of build jobs hasn't been necessary. But the work to fix https://github.com/dotnet/dotnet-docker/issues/3870 has exposed an issue with the matrix generation that is resolved by these changes.
For CBL-Mariner 2.0, there are two build jobs with the `platformVersionedOs` matrix type: one for full Mariner and one for the distroless variant. Due to test dependencies, the distroless build job was configured to also build the full Mariner images. The changes to fix https://github.com/dotnet/dotnet-docker/issues/3870 caused both distroless and full Mariner to have their tests executed. As result of …
> Combine build legs which share Dockerfile paths

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestCommand.cs
Fixes https://github.com/dotnet/docker-tools/issues/1094
> Fix concurrency issue w/ manifest list tag publishing

- src/Microsoft.DotNet.ImageBuilder/src/DockerService.cs
> Handle retry attempts to create manifest list tags

- eng/common/Install-DotNetSdk.ps1
- eng/src/file-pusher/Dockerfile
- eng/src/file-pusher/file-pusher.csproj
- eng/src/yaml-updater/Dockerfile
- eng/src/yaml-updater/yaml-updater.csproj
- src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
- src/Microsoft.DotNet.ImageBuilder/Dockerfile.windows
- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
- src/Microsoft.DotNet.ImageBuilder/tests/Microsoft.DotNet.ImageBuilder.Tests.csproj
Part of https://github.com/dotnet/docker-tools/issues/1078
> Update to ImageBuilder and tools to .NET 7

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishMcrDocsCommand.cs
Reverts the changes from #520 since .NET Core 3.1 is EOL. This actually was able to be done prior to 3.1 EOL because we long ago removed having multiple product families in the manifest. We consolidated 2.1 and 3.1 out of the "core" repositories in https://github.com/dotnet/dotnet-docker/pull/2340.
Reverts commit 6a11ac6
Fixes https://github.com/dotnet/docker-tools/issues/523
> Reverts "Fix publishMcrDocs to handle different product repos (#520)"

- eng/common/templates/variables/docker-images.yml
Updates the image tag for the test runner to the new floating tag to ensure it's kept up to date.
> Update testrunner tag

- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
See https://github.com/dotnet/dotnet-docker/pull/4542#issuecomment-1496488896
> Update Dockerfile FROM regex to accept --platform args

- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
Updating package references to hopefully take care of some component governance alerts.
> Upgrade package versions referenced by Image Builder

- src/Microsoft.DotNet.ImageBuilder/src/DockerService.cs
- src/Microsoft.DotNet.ImageBuilder/src/ExecuteHelper.cs
This is needed to facilitate https://github.com/dotnet/dotnet-docker/issues/4447 and https://github.com/dotnet/dotnet-docker/pull/4542
> Enable BuildKit in ImageBuilder

- src/Microsoft.DotNet.ImageBuilder/src/DockerService.cs
This should fix the CI failure in https://github.com/dotnet/docker-tools/pull/1129
> Disable BuildKit on Windows

- eng/common/templates/variables/docker-images.yml
- src/Microsoft.DotNet.ImageBuilder/src/DockerService.cs
- src/Microsoft.DotNet.ImageBuilder/src/ExecuteHelper.cs
See https://github.com/dotnet/docker-tools/pull/1132#issuecomment-1538760029
> Revert "Enable BuildKit in ImageBuilder"

- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
Resolves some component governance issues.
> Update Image Builder package dependencies

- eng/common/templates/jobs/build-images.yml
Workaround for https://github.com/dotnet/docker-tools/issues/1152
> Pin to specific version of ManifestGeneratorTask

- src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
- src/Microsoft.DotNet.ImageBuilder/manifest.json
- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Helpers/ManifestHelper.cs
This should fix #1161 and #1159
I am listening for feedback on how else I can validate that this change won't cause problems.
> Move back to alpine floating tag and don't check variant for arm64/(v8)

- eng/common/templates/stages/dotnet/build-test-publish-repo.yml
Migrating to a new pool for Linux arm agents.
> Linux Arm pool update

- CODEOWNERS
- eng/src/file-pusher/file-pusher.csproj
- eng/src/yaml-updater/yaml-updater.csproj
- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
- Update file-pusher and dependencies
- Update yaml-updater and dependencies
- Update ImageBuilder dependencies
Part of https://github.com/dotnet/docker-tools/issues/1181
> Update projects to .NET 8 and update project dependencies

- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
Fixes https://github.com/dotnet/docker-tools/issues/1207
> Update Microsoft.DotNet.Git.IssueManager to pick up new version of OctoKit

- eng/common/templates/variables/common.yml
- eng/common/templates/variables/dotnet/common.yml
- eng/pipelines/templates/variables/common.yml
- eng/pipelines/upload-file.yml
Related to https://github.com/dotnet/dotnet-docker-internal/issues/4475
[Validation run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2403475&view=logs&j=acccb8e6-9ace-59e9-8731-557829c86058&t=ee06ff9a-8fe5-5f6a-a117-fbf889bf7dc3) (internal Microsoft link) - note I didn't want to actually upload a file so the actual upload step fails.
> Convert upload-file pipeline to use 1ES templates

- eng/common/templates/steps/copy-base-images.yml
- eng/common/templates/steps/init-docker-linux.yml
- eng/common/templates/steps/set-dry-run.yml
- eng/pipelines/check-base-image-updates.yml
- eng/pipelines/templates/jobs/check-base-image-updates.yml
Related to: https://github.com/dotnet/dotnet-docker-internal/issues/4475
Test run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2404434 (internal Microsoft link)
> Convert the check-base-image-updates pipeline to use 1ES templates

- eng/common/templates/stages/dotnet/build-test-publish-repo.yml
Related: 
- https://github.com/dotnet/dotnet-docker-internal/issues/4475
- https://github.com/microsoft/dotnet-framework-docker/pull/1116
> Use WS2016 image with support for 1ES Pipeline Templates

- eng/common/templates/jobs/build-images.yml
- eng/common/templates/jobs/post-build.yml
- eng/common/templates/jobs/publish.yml
- eng/common/templates/steps/test-images-linux-client.yml
Test run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2412507&view=results [internal link]
Fixes https://github.com/dotnet/docker-tools/issues/1216
> Always publish in directories instead of publishing individual files

- eng/common/templates/stages/dotnet/build-test-publish-repo.yml
Related: https://github.com/microsoft/dotnet-framework-docker/pull/1116
> Backport changes from dotnet-framework-docker PR #1116

- eng/common/templates/jobs/publish.yml
> Use correct path to image-info for wait-for-image-ingestion step

- eng/src/file-pusher/FilePusher.cs
Fixes #1224 
Confirmed that the project can now give a non-zero exit code even when run from Docker.
> Set exit code in FilePusher

- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
Related to https://github.com/dotnet/dotnet-docker/issues/5331
> Add support for Azure Linux to ImageBuilder

- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
Updates per comments at https://github.com/dotnet/docker-tools/pull/1240#pullrequestreview-1998238959
> Update azurelinux os name

- eng/common/templates/jobs/publish.yml
> Authenticate kusto command

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesOptions.cs
> Add Registry credential options back to GetStaleImages command

- eng/common/templates/variables/dotnet/build-test-publish.yml
- eng/common/templates/variables/dotnet/common.yml
> Switch to new secret variable group

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateArtifactsCommand.cs
Our previous error reporting only reported the file that template errors are in and then dumped some of the template text out.
This PR improves it by actually printing which line and column the errors are on. The error location format is `{startLine},{startColumn},{endLine},{endColumn}`, in order to comply with VS Code's problem matching syntax.
With a custom template generation task and problem matcher, this allows us to get accurate error reporting for template generation:
```json
{
"label": "Generate Dockerfiles",
"type": "shell",
"command": "pwsh ./eng/dockerfile-templates/Get-GeneratedDockerfiles.ps1",
"group": "build",
"problemMatcher": [
{
"owner": "generate-dockerfiles",
"fileLocation": [
"relative",
"${workspaceFolder}"
],
"pattern": [
{
"regexp": "^(?: )*Template parsing error …
```
> Improve templating error reporting

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateReadmesCommand.cs
This ports the code that was originally in mcr.microsoft.com/mcr/renderingtool:1.0 so that it's contained within Image Builder itself. This is needed because the rendering tool is deprecated.
I've tested this logic against the readmes for both dotnet-docker and dotnet-framework-docker. It produces identical output.
Fixes dotnet/dotnet-docker#5561
> Replace rendering tool w/ custom implementation

- eng/common/templates/jobs/build-images.yml
- eng/common/templates/variables/docker-images.yml
- eng/common/templates/variables/dotnet/common.yml
- eng/tests/pipeline-validation/1.0/focal/amd64/Dockerfile
- eng/tests/pipeline-validation/1.0/focal/arm64v8/Dockerfile
Fixes https://github.com/dotnet/dotnet-docker-internal/issues/5504
> Use cache ACR for building images in public PR validation

- src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
Update ORAS to the latest version 1.2.0.
> Update ORAS to the latest version 1.2.0

- eng/common/templates/variables/common.yml
> Remove hard-coded `overrideOfficialBranchValidation` variable

- eng/common/templates/steps/test-images-linux-client.yml
- eng/common/templates/steps/test-images-windows-client.yml
Backport changes to eng/common from https://github.com/dotnet/dotnet-docker/pull/5738
This will unblock https://github.com/dotnet/dotnet-docker/pull/5736
> Backport dotnet-docker changes to test arguments variables

- src/Microsoft.DotNet.ImageBuilder/src/MarImageIngestionReporter.cs
- src/Microsoft.DotNet.ImageBuilder/tests/MarImageIngestionReporterTests.cs
There's an issue with the logic that waits for an annotation to be ingested into MAR. The command ends up immediately returning success regardless of the current status of the ingestion.
The issue is with this line:
https://github.com/dotnet/docker-tools/blob/e133aec556c5ff364d7bb43ea46b0e8c8682c8af/src/Microsoft.DotNet.ImageBuilder/src/MarImageIngestionReporter.cs#L78
By definition, annotations do not have a tag associated with them. So `RemainingTags` is always empty. Because it's empty, it doesn't attempt to continuously query for the status until success or failure. So even when the status is "not started" or "processing", it simply stops processing and declares victory.
I've fixed this by introducing an `IsComplete` property that will be checked instead of `RemainingTags`. This will …
> Fix for waiting on annotation ingestion

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateReadmesCommand.cs
Related to https://github.com/dotnet/dotnet-docker/issues/5316
The following changes were made to the way the tags table is generated.
1. Add blank link after all headers
2. Removed the "You can retrieve a list of all available tags..." at the end of the generated comment.  This allows the statement to be combined with the "Tags not listed in the table above are not supported...." statement added at the repo level.
3. Changes the heading levels to be sequential and to allow for a top level heading for the GH readmes which is now the only place where the tables are included.
You can see the results of these changes in https://github.com/dotnet/dotnet-docker/pull/5768 which also includes some complimentary changes.
> Tweaks to the generated tags table documentation

- src/Microsoft.DotNet.ImageBuilder/src/Commands/CleanAcrImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CleanAcrImagesOptions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/CleanAcrImagesCommandTest.cs
Fixes: https://github.com/dotnet/docker-tools/issues/1383
We need to login to Docker CLI, so Oras command can run authenticated.
> Login to Docker CLI in CleanAcrImagesCommand

- eng/check-base-image-subscriptions-buildtools.json
Related to https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/1174
> Remove FloatingTagSuffix infrastructure

- eng/src/file-pusher/AzDoSafeTraceListenerWrapper.cs
- eng/src/file-pusher/FilePusher.cs
- eng/src/yaml-updater/YamlUpdater.cs
> Fix file-pusher pipeline failure when pushing files that contain `##vso` tasks

- eng/pipelines/cleanup-acr-images.yml
Updates the cleanup pipeline to target EOL images.
Related to https://github.com/dotnet/docker-tools/issues/1201
> Clean EOL images

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
> Remove build hooks functionality

- eng/common/templates/jobs/publish.yml
Port the changes from https://github.com/dotnet/dotnet-docker/pull/5875
> Switch arg order to fix EOL publishing

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateEolAnnotationDataCommand.cs
There can be scenarios where the pipeline ends up not publishing any images. This is true in the case of PR builds, for example, where all the images are cached (see [example build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=813530&view=results)). This means that no image info files are output by the `publishImageInfo` command. This then causes a failure in the `generateEolAnnotationData` because these image info files are expected to exist:
```
Unhandled exception: System.IO.FileNotFoundException: Could not find file '/artifacts/eol-annotation-data/image-info-old.json'.
File name: '/artifacts/eol-annotation-data/image-info-old.json'
at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
at …
```
> generateEolAnnotationData: handle missing image info files

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageCacheService.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Manifest/Tag.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
> Remove local tag logic

- eng/common/Install-DotNetSdk.ps1
- eng/src/file-pusher/Dockerfile
- eng/src/file-pusher/file-pusher.csproj
- eng/src/yaml-updater/Dockerfile
- eng/src/yaml-updater/yaml-updater.csproj
- src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
- src/Microsoft.DotNet.ImageBuilder/Dockerfile.windows
- src/Microsoft.DotNet.ImageBuilder/src/Commands/AnnotateEolDigestsCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CommandExtensions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/IngestKustoImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishMcrDocsCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/CopyImageService.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageNameResolver.cs
- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
- src/Microsoft.DotNet.ImageBuilder/src/StringExtensions.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Helpers/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Microsoft.DotNet.ImageBuilder.Tests.csproj
Part of https://github.com/dotnet/dotnet-docker/issues/5056
> Update projects to .NET 9

- .github/ISSUE_TEMPLATE/releases/new-windows-release.md
- eng/common/templates/stages/build-test-publish-repo.yml
- eng/common/templates/stages/dotnet/build-test-publish-repo.yml
- eng/common/templates/variables/common.yml
- eng/common/templates/variables/dotnet/common.yml
> Add pipeline support for Windows Server 2025

- eng/common/templates/1es-official.yml
- eng/common/templates/1es-unofficial.yml
These are required compliance steps.
> Enable tsa and policheck in pipelines

- eng/common/Install-DotNetSdk.ps1
Hopefully this fixes https://github.com/dotnet/dotnet-docker/issues/5991
> Increase NuGet Chain Build Retry Policy

- eng/common/templates/variables/dotnet/common.yml
Test run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2572760&view=results
> Use new Server 2016 VM Image

- src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
Changelog: https://github.com/oras-project/oras/releases/tag/v1.2.2
Related: https://github.com/dotnet/dotnet-docker-internal/issues/7005#issuecomment-2557293708
> Update ORAS to 1.2.2

- .github/dependabot.yml
> Use solution directories for dependabot

- .devcontainer/devcontainer.json
- src/Microsoft.DotNet.ImageBuilder/.devcontainer/devcontainer.json
Related: https://github.com/dotnet/dotnet-docker/pull/6238
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/dotnet/docker-tools/pull/1601?shareId=b61153af-875c-470e-a214-3834000d7c56).
> Add devcontainer config

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
> Print image size (disk size) during build

- eng/common/templates/1es-official.yml
- eng/common/templates/1es-unofficial.yml
> Enable binskim in 1es pipelines

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GitOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/OctokitClientFactory.cs
fixes: https://github.com/dotnet/docker-tools/issues/1670
> Add installation ID parameter for GitHub App auth

- src/Microsoft.DotNet.ImageBuilder/tests/Microsoft.DotNet.ImageBuilder.Tests.csproj
> Replace FluentAssertions with AwesomeAssertions

- eng/common/templates/variables/dotnet/build-test-publish.yml
This change is currently being tested in [this pipeline run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2697597&view=results) - that will make sure that the arguments go through correctly.
> Use GitHub App to run PublishMcrDocs command

- eng/common/templates/1es-official.yml
- eng/common/templates/1es-unofficial.yml
- eng/common/templates/jobs/publish.yml
- eng/common/templates/task-prefix-decorator.yml
> Add common prefix to all pipeline steps

- eng/common/templates/stages/publish.yml
Backport of some changes from https://github.com/dotnet/dotnet-docker/pull/6435
> Optimize stage dependencies for standalone publish

- eng/common/templates/jobs/build-images.yml
- eng/common/templates/stages/build-and-test.yml
- eng/common/templates/steps/common-init-for-matrix-and-build.yml
This is the docker-tools component of https://github.com/dotnet/dotnet-docker-internal/issues/7413
The other part of the release staging pipeline changes is at https://github.com/dotnet/dotnet-docker/pull/6485
> Enable internal builds in release staging pipeline

- eng/common/templates/jobs/publish.yml
Due to https://github.com/dotnet/dotnet-docker/issues/6588.
> Temporarily disable Publish Readmes step

- eng/common/templates/jobs/publish.yml
Reverts dotnet/docker-tools#1757 since https://github.com/dotnet/dotnet-docker/issues/6588 was mitigated
> Revert "Temporarily disable Publish Readmes step"

- src/Microsoft.DotNet.ImageBuilder/src/Commands/MergeImageInfoCommand.cs
There was a problem with the MergeImageInfo command when publishing .NET 10 Preview 7 images today.
We ran the publish pipeline against the latest commit of dotnet-docker's `main` branch, which had [this manifest.json](https://github.com/dotnet/dotnet-docker/blob/97eede849eddb8c42983d7421684ed8a6b8b51b0/manifest.json).
My best guess as to why this happened is that when loading the original image info (from dotnet/versions), because the latest manifest had all Preview 6 images replaced with Preview 7, for some reason ImageBuilder was unable to match up the Preview 6 images with Preview 7 in order to fill out the initial image's `ManifestImage` fields.
I still need more time to figure out why the mismatch happens and prevent it permanently, but this PR fixes the immediate symptom. It's …
> Account for removed/new images when overriding commit in MergeImageInfo command

- src/Microsoft.DotNet.ImageBuilder/src/AzureTokenCredentialProvider.cs
> Condition out DefaultAzureCredential in release builds

- eng/common/templates/jobs/publish.yml
Updates the pipeline to react to the changes made in https://github.com/dotnet/docker-tools/pull/1778
> Update EOL command usage

- eng/common/templates/jobs/publish.yml
Updates the references to task names that were changed by https://github.com/dotnet/docker-tools/pull/1810.
> Update EOL task name references

- src/ImageBuilder/ViewModel/PlatformInfo.cs
Fixes #1822
#1814 made all the ImageBuilder Windows versions have the same OsVersion because they all build on the same OS (Nano Server 2025). After that, they only differed by their build args in manifest.json. This caused all of their platforms to be incorrectly merged together into one after the build stage, resulting in the problem described in #1822. Essentially the tags from 2/3 of the Windows versions got squashed into one because ImageBuilder mistakenly thought they were the same image. Accounting for build args when comparing platforms should fix this problem.
> Add build args to platform unique key
