dotnet/docker-tools

- src/Microsoft.DotNet.ImageBuilder/ImageBuilder.cs
- src/Microsoft.DotNet.ImageBuilder/Model/Manifest.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/ImageInfo.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/ManifestInfo.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/ModelExtensions.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/PlatformInfo.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/RepoInfo.cs
Added support for tagVariables within the manifest that can be referenced within the various tags.
```
"tagVariables": {
"nanoServerVersion": "10.0.14393.1198"
}
...
"windows": {
"dockerfile": "1.0/runtime/nanoserver",
"tags": [
"1.0.5-runtime-nanoserver",
"1.0.5-runtime-nanoserver-$(nanoServerVersion)",
"1.0-runtime-nanoserver",
"1.0-runtime-nanoserver-$(nanoServerVersion)"
]
}
```
fixes #5
>  Add support for tag variables within manifest

- src/Microsoft.DotNet.ImageBuilder/Dockerfile
Modified the Dockerfile to utilize the manifest-tool's released artifacts.  This greatly simplifies the Dockerfile as well as ties the it to a set version of the manifest-tool.
Fixes #13
> Make manifest-tool version explicit

- src/Microsoft.DotNet.ImageBuilder/DockerHelper.cs
- src/Microsoft.DotNet.ImageBuilder/ImageBuilder.cs
- src/Microsoft.DotNet.ImageBuilder/Model/Architecture.cs
- src/Microsoft.DotNet.ImageBuilder/Model/Image.cs
- src/Microsoft.DotNet.ImageBuilder/Model/Platform.cs
- src/Microsoft.DotNet.ImageBuilder/Options.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/ImageInfo.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/ManifestInfo.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/RepoInfo.cs
This required a schema change to the manifest.  The following is an example of the new schema used in the dotnet-docker-nightly repo.
```
{
"sharedTags": [
"2.0.0-preview3-runtime",
"2.0-runtime",
"2-runtime"
],
"platforms": [
{
"dockerfile": "2.0/runtime/stretch",
"os": "linux",
"tags": [
"2.0.0-preview3-runtime-stretch"
]
},
{
"architecture": "arm",
"dockerfile": "2.0/runtime/stretch/arm32v7",
"os": "linux",
"tags": [
"2.0.0-preview3-runtime-stretch-arm32v7",
"2.0-runtime-stretch-arm32v7",
"2-runtime-stretch-arm32v7"
],
"variant": "armv7"
},
{
"dockerfile": "2.0/runtime/nanoserver",
"os": "windows",
"tags": [
"2.0.0-preview3-runtime-nanoserver",
"2.0.0-preview3-runtime-nanoserver-$(nanoServerVersion)",
"2.0-runtime-nanoserver",
"2.0-runtime-nanoserver-$(nanoServerVersion)", …
```
> Add support for building ARM images

- src/Microsoft.DotNet.ImageBuilder/DockerHelper.cs
- src/Microsoft.DotNet.ImageBuilder/ImageBuilder.cs
- src/Microsoft.DotNet.ImageBuilder/Options.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/ManifestInfo.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/RepoInfo.cs
Looking for feedback on the new option.  I can imagine a scenario in which specifying an entirely different repo may be useful.  That would require the mapping of old repo to new repo since the manifest can contain multiple repos.  The repo owner functionality I added satisfies the current requirements from the dotnet core repos.  Having to specify a map makes it clunky for this scenario which is why I didn't add it.  Adding another option down the road to specify a completely different repo is certainly possible.
> Add support for changing the repo owner via options

- src/Microsoft.DotNet.ImageBuilder/ImageBuilder.cs
This change is needed because the Docker manifest tool used for publishing the multi-arch tags is case sensitive.
> ToLower arch when creating manifest for publish

- src/Microsoft.DotNet.ImageBuilder/Commands/GenerateTagsReadmeCommand.cs
- src/Microsoft.DotNet.ImageBuilder/Commands/GenerateTagsReadmeOptions.cs
- src/Microsoft.DotNet.ImageBuilder/Commands/PublishManifestCommand.cs
- src/Microsoft.DotNet.ImageBuilder/Dockerfile
- src/Microsoft.DotNet.ImageBuilder/Dockerfile.nanoserver
- src/Microsoft.DotNet.ImageBuilder/ImageBuilder.cs
- src/Microsoft.DotNet.ImageBuilder/Microsoft.DotNet.ImageBuilder.csproj
- src/Microsoft.DotNet.ImageBuilder/Model/Image.cs
- src/Microsoft.DotNet.ImageBuilder/Model/Platform.cs
- src/Microsoft.DotNet.ImageBuilder/Model/Tag.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/ImageInfo.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/ManifestFilter.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/ManifestInfo.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/PlatformInfo.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/TagInfo.cs
This required a change to the manifest schema in order to capture the required metadata.  I applied the needed [changes](https://github.com/MichaelSimons/dotnet-docker-nightly/commit/39741d5a206239d795e732087f367d6cf18ce472#diff-4b1eb3dc48c4e16d49db5b42298fe654) to the microsoft/dotnet-nightly repo if you want to take a look.  I'm not crazy about the verbosity of the tags element but I can see benefits to being able to add additional metadata over time.  I'm certainly open to feedback.
related #10
> Add command to generate tags section of readme

- src/Microsoft.DotNet.ImageBuilder/Commands/BuildOptions.cs
- src/Microsoft.DotNet.ImageBuilder/Commands/Command.TOptions.cs
- src/Microsoft.DotNet.ImageBuilder/Commands/GenerateTagsReadmeOptions.cs
- src/Microsoft.DotNet.ImageBuilder/Commands/PublishManifestCommand.cs
- src/Microsoft.DotNet.ImageBuilder/Commands/UpdateVersionsCommand.cs
- src/Microsoft.DotNet.ImageBuilder/Commands/UpdateVersionsOptions.cs
- src/Microsoft.DotNet.ImageBuilder/ImageBuilder.cs
- src/Microsoft.DotNet.ImageBuilder/Microsoft.DotNet.ImageBuilder.sln
- src/Microsoft.DotNet.ImageBuilder/Model/Tag.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/ManifestFilter.cs
These changes add regex support on _path_ argument in _ImageBuilder_. Wildcard characters `*` and `?` are supported. For example, passing `build --repo microsoft/dotnet-nightly --path "*sdk*"` would build all images that contain the word `sdk` in Dockerfile path.
Changes also include -
- A solution file to open ImageBuilder project in Visual Studio
- Remove and sort _using_ across the solution
> Add regex support on path argument in ImageBuilder

- src/Microsoft.DotNet.ImageBuilder/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/ImageInfo.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/ManifestFilter.cs
- src/Microsoft.DotNet.ImageBuilder/ViewModel/ManifestInfo.cs
These changes allow for manifest tag to reference to more than one image per platform which will be for different OS versions.
This functionality is need as part of https://github.com/dotnet/dotnet-docker/issues/298.
> Add support for multiple os images per multi-arch tag

- src/Microsoft.DotNet.ImageBuilder/Commands/GenerateTagsReadmeCommand.cs
Related to #58 
This issue was detected while rolling out the initial update-readme functionality.  When running generateTagsReadme within a Linux container on a Windows host utilizing a host volume, the resulting readme line endings are not correct.
> Refactor GenerateTagsReadme to match line endings of readme

- .gitignore
- Microsoft.DotNet.ImageBuilder/src/GitHelper.cs
- Microsoft.DotNet.ImageBuilder/src/Utilities.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestFilter.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ModelExtensions.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/TagInfo.cs
Adds the ability to _ImageBuilder_ to substitute global variables with corresponding values in manifest.json. Dockerfile commit SHA and timestamp variable substitution is enabled.
Refer to https://github.com/dotnet/docker-tools/issues/63
> Support for global variable substitution

- Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
Currently, _ImageBuilder_ does not offer any hooks.  A hook enables running a custom script before or after a Docker command. Refer to https://github.com/dotnet/docker-tools/issues/65
These changes add support for `pre-build` and `post-build`.  Contract for `InvokeBuildHook`, is -
1. Check if the named script is available in a folder named `hooks` in the build content. If yes, then executes the script as a Shell script.
2. If the script was not found in step-1, then look for a PowerShell script. This means named script with an extension `.ps1`.  If found , then execute that PowerShell script.
> Enable build hooks in ImageBuilder

- Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/DockerRegistryOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestCommand.cs
- Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
This is needed in order to use ImageBuilder to push images to an Azure Container Registry.
> Add support to login to registry server other than Docker Hub

- Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Model/Platform.cs
- Microsoft.DotNet.ImageBuilder/src/Model/Tag.cs
- Microsoft.DotNet.ImageBuilder/src/Utilities.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
This also includes variable support for referencing tags - e.g. $(tagRef:debian-8.2)
Sample Manifest Usage:
```
{
"platforms": [
{
"dockerfile": "debian/8.2",
"os": "linux",
"tags": {
"debian-8.2-$(DockerfileGitCommitSha)-$(TimeStamp)": {
"id": "debian-8.2"
}
}
}
]
},
{
"platforms": [
{
"buildArgs": {
"BASE_IMAGE":"$(tagRef:debian-8.2)"
},
"dockerfile": "debian/8.2/debpkg",
"os": "linux",
"tags": {
"debian-8.2-debpkg-$(system:DockerfileGitCommitSha)-$(system:TimeStamp)": {}
}
}
]
},
```
> Add support for modeled docker build args

- Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/BuildOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/Command.TOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/Options.cs
- Microsoft.DotNet.ImageBuilder/src/Model/Manifest.cs
- Microsoft.DotNet.ImageBuilder/src/Utilities.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ImageInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/RepoInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/TagInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/VariableHelper.cs
1. Made the `TagVariables` property in the model generally applicable to anywhere variables are used in the model.  As part of this the `TagVariables` property was renamed to `Variables`.
2. Refactored the `build` command's `test-var` option to be generally applicable to any command.  The option was renamed to `var`.
3. Added a prefix to all built in variables to make the manifest easier to read in that it is clear where the variable values come from.
4. Refactored the variable substitution logic so that it is more centrally located within one class.  This refactoring should make it easy to add additional built in variables in the future in addition to adding more places within the manifest that support referencing variables.
> Variable refactoring

- Microsoft.DotNet.ImageBuilder/src/Commands/Command.TOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/DockerRegistryOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/Options.cs
- Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- Microsoft.DotNet.ImageBuilder/src/ValidationException.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ModelExtensions.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/VariableHelper.cs
This change is to support tests that need to know the repo owner in order to test the images.  Hard coding the owner within the tests is undesirable as the name would need to be updated if using the `--repo-owner` option to push to a staging docker registry.  
[These changes](https://github.com/Microsoft/dotnet-framework-docker/compare/master...MichaelSimons:RepoOwner?expand=1) show how this new functionality would be used.
> Add RepoOwner built in variable

- Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ModelExtensions.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/VariableHelper.cs
A base image can contain a [build-arg](https://docs.docker.com/engine/reference/builder/#arg). For example -
```
ARG  CODE_VERSION=latest
FROM base:${CODE_VERSION}
```
Pulling `base:${CODE_VERSION}` would fail if the build-arg is not replaced with the corresponding value. Hence these changes enable _ImageBuilder_ to skip pulling base images that contains a build-arg.
A related change is validating the uniqueness of tag IDs.
> Ignore pulling base images if name contains a build-arg

- Microsoft.DotNet.ImageBuilder/Dockerfile
Include Git in _ImageBuilder_ image.  Git is needed for getting a Dockerfile's commit SHA.
> Install Git in ImageBuilder image

- Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Model/Tag.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
Introduces an `IsLocal` property for a tag.  This is to enable the scenario where a local or transient image is used to build an image. Only the final image should be pushed to the registry, and the transient image should not be included in the push. In such a case, setting `IsLocal` to `true` on a tag will skip pushing the corresponding tag (image) to a Docker registry.
A related change is to set the `WorkingDirectory` property to build context path while invoking a build hook. This ensures that the hook can find all the files and directories it needs.
> Ignore pushing images that have IsLocal as true

- Microsoft.DotNet.ImageBuilder/src/ViewModel/VariableHelper.cs
Date-time format used in `TimeStamp` is incorrect.  Correct format should include month `MM` and not `mm`, which is minute.  Also, updated to 24-hour format i.e, `HH` in place of `hh`.
> Update datetime format

- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateTagsReadmeCommand.cs
Fixes the following error 
```
System.InvalidOperationException: Sequence contains no elements
at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
at Microsoft.DotNet.ImageBuilder.Commands.GenerateTagsReadmeCommand.GetTagsDocumentation(RepoInfo repo) in /image-builder/Commands/GenerateTagsReadmeCommand.cs:line 68
at Microsoft.DotNet.ImageBuilder.Commands.GenerateTagsReadmeCommand.ExecuteAsync() in /image-builder/Commands/GenerateTagsReadmeCommand.cs:line 28
at Microsoft.DotNet.ImageBuilder.ImageBuilder.Main(String[] args) in /image-builder/ImageBuilder.cs:line 53
```
> Fix InvalidOperationException when there are no documented tags for an image

- Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/DockerRegistryCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/DockerRegistryOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestCommand.cs
Fixes #69
- Add validation to ensure both username and password are specified if one is specified.
- If a username and password are not specified, skip docker registry login.  This is useful when running locally.
> Refactor username/password option validation

- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateTagsReadmeCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateTagsReadmeOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Model/Image.cs
- Microsoft.DotNet.ImageBuilder/src/Model/Repo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/TagInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/VariableHelper.cs
Fixes #89 
I decided to try a readme template approach.  I'm not really in love with this but it does address the issues discussed in #89.  You can see an example [here](https://github.com/MichaelSimons/dotnet-docker/blob/issue-337/manifest.json#L520).  I had thought about using something like a T4 template but it is far more complicated and expensive to implement/maintain than I felt was needed.   I would like to keep this as simple as possible, yet allow PMs/repo owners the flexibility in changing the readme format yet still get the benefit of having a tool generate the individual tag lines.
@natemcmaster - I would like to get your feedback on this.
> Refactor GenerateTagsReadmeCommand to support user defined templates

- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateTagsReadmeCommand.cs
Per discussion with @richlander, we want to remove the term supported as it gets confusing with the "preview 1" tags.
> Reword tag headings to remove 'supported'

- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateTagsReadmeCommand.cs
Fixes #97 
This is a change that will hopefully cover the next versions of Windows Server assuming they stay with the `Windows Server, version N` naming scheme. 
Note: we are now only setting the version number in the manifests to the shortened stable release version - e.g. 1803, 1709, etc.)
> Update generateTagsReadme command to handle new windows versions

- Microsoft.DotNet.ImageBuilder/Dockerfile.debian
- Microsoft.DotNet.ImageBuilder/Dockerfile.nanoserver
- Microsoft.DotNet.ImageBuilder/NuGet.config
- Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
- Microsoft.DotNet.ImageBuilder/tests/Microsoft.DotNet.ImageBuilder.Tests.csproj
I also made use of the IL linker.  The primary purpose of this is to reduce the size of the resulting image.  With the combination of 2.1 and the IL linker, the Linux image size (extracted on disk) dropped from 520 MB to 457 MB.
> Update to .NET Core 2.1

- Microsoft.DotNet.ImageBuilder/.dockerignore
- Microsoft.DotNet.ImageBuilder/src/Commands/UpdateReadmeCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
The only required change is to upgrade the ILLink.Tasks package.  The version being used was trimming some required components for this scenario.  The other changes are related cleanup I discovered while I was debugging this issue.
Fixes #101
> Upgrade ILLink.Tasks to fix HttpClient SSL bug

- Microsoft.DotNet.ImageBuilder/Dockerfile.nanoserver
- Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/Options.cs
- Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/IOptionsInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/RepoInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/VariableHelper.cs
This is needed so that we can build and push the images to a staging repo prior to publishing to the public repo (e.g. Docker Hub). Previously there was support for overriding the repo owner (e.g. `microsoft` in `microsoft/dotnet`).
> Refactor logic to support overriding the repo at build/publish time

- Microsoft.DotNet.ImageBuilder/Dockerfile.nanoserver
- Microsoft.DotNet.ImageBuilder/src/Commands/BuildOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/CopyImagesCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/CopyImagesOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/DockerRegistryCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/IManifestFilterOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/Options.cs
- Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- Microsoft.DotNet.ImageBuilder/src/ImageBuilder.cs
This command is intended to be used to copy images from a staging repo to the public repo (e.g. Docker Hub).
The primary changes are in CopyImagesCommand.cs and CopyImagesOptions.cs.  The rest of the changes are misc refactorings to share common code with existing commands.
> Add copyImages command

- Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ModelExtensions.cs
There is a new usage scenario in which there is a desire to have a manifest with multiple repo owners/no owners (e.g. ACR).  This validation logic doesn't provide significant value and therefore I decided to remove it.
Fixes #108
> Remove common repo owner validation

- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateTagsReadmeCommand.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/VariableHelper.cs
Add support to the generatedTagsReadme command to specify an explicit set of tags.  This support is needed for the .NET Core 2.2 release where a common runtime-deps image is shared between 2.1 and 2.2.  With this scenario, the requirement is to list the image twice in the readme as we believe this will make it easier for users to find the images they are looking for.
```
...
- [`2.1.3-runtime-deps-bionic`, `2.1-runtime-deps-bionic` (*2.1/runtime-deps/bionic/amd64/Dockerfile*)](https://github.com/dotnet/dotnet-docker/blob/nightly/2.1/runtime-deps/bionic/amd64/Dockerfile)
...
- [`2.2.0-preview1-runtime-deps-bionic`, `2.2-runtime-deps-bionic` (*2.1/runtime-deps/bionic/amd64/Dockerfile*)](https://github.com/dotnet/dotnet-docker/blob/nightly/2.1/runtime-deps/bionic/amd64/Dockerfile)
...
```
I …
> Add support for TagDocList variable

- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateTagsReadmeCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateTagsReadmeOptions.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/VariableHelper.cs
These are the changes needed to support https://github.com/dotnet/dotnet-docker/pull/665
- Add support for a SourceUrl variable that can be referenced in a readme template.
- Add support to specify a custom `readme` file to update.
- Refactored the pattern to search and replace in the readme to be based on the `## Complete set of Tags` header section.
- Add an option to skips tag validation to support generating a partial tag list.
> Add support for generating a TAGS.md with the generateTagsReadme command

- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildQueueCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildQueueOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateTagsReadmeCommand.cs
- Microsoft.DotNet.ImageBuilder/src/GraphExtensions.cs
- Microsoft.DotNet.ImageBuilder/src/ImageBuilder.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ModelExtensions.cs
Added a command that reads the manifest and generates the VSTS build queue variables.  The generated legs are the smallest possible dependency graphs as defined by the intra-repo Dockerfile depencencies.
Currently the output from this command can be copied and pasted into the VSTS build definitions.  Eventually I would like to invoke this command directly from the build to make everything dynamic.
> Add generateBuildQueue command

- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- Microsoft.DotNet.ImageBuilder/src/Model/Architecture.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ModelExtensions.cs
Minor tweaks to support Windows Arm32 and Linux Arm64.
> Add support for Windows arm32 and Linux arm64

- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateTagsReadmeCommand.cs
This was done for two reasons
1. Our readmes are exceeding the 25 k limit on Docker Hub and this change helps reduce this size significantly.
1. This simplifies the tags section and reduces the number of multi-line image entries.
> Remove full Dockerfile path from tags readme

- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
This makes the Azure DevOps build output more readable.
> Update generatedBuildMatrix cmd to always emit readable log output

- Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/BuildOptions.cs
This is to help reduce intermittent build failures do to network related hiccups during the build such as the inability to install apt packages or download a resource.
> Add retry build option

- Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
ImageBuilder no longer works with the latest version of Docker which doesn't have a suffix.
> Patch to handle latest version format without a '-suffix'

- Microsoft.DotNet.ImageBuilder/Dockerfile.debian
This is blocking the release of the microsoft/dotnet-nightly Windows Arm32 images.
> Update manifest-tool in order to support windows/arm

- Microsoft.DotNet.ImageBuilder/Dockerfile.debian
v0.9.0 was released therefore the temporary source built workaround can be removed.
> Update manifest-tool to v0.9.0

- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixOptions.cs
This will allow us to specify build time parameters to only build a subset of the images.  For example we can utilize this functionality to only build the 3.0 Jessie images.
> Add support for generating a subset of the build matrix

- Microsoft.DotNet.ImageBuilder/src/Model/Repo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/RepoInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/VariableHelper.cs
This adds support for referencing any repo by id.  This supports cross repo dependencies which are needed for the move to MCR where the .NET Core repos are broken apart by image type.  There will be a separate repo for both runtime-deps and runtime images.  
Sample Usage:
```
"id" : "runtime",
"name": "mcr.microsoft.com/dotnet/core-nightly/runtime",
"readmePath": "README.runtime.md",
"images": [
{
"sharedTags": {
"$(1.0-RuntimeVersion)": {},
"1.0": {}
},
"platforms": [
{
"buildArgs": {
"REPO": "$(Repo:runtime-deps)"
},
"dockerfile": "1.0/runtime/jessie/amd64",
"os": "linux",
"tags": {
"$(1.0-RuntimeVersion)-jessie": {},
"1.0-jessie": {}
}
},
{
"dockerfile": "1.0/runtime/nanoserver-sac2016/amd64",
"os": "windows",
"osVersion": "nanoserver-sac2016",
"tags": { …
```
> Refactor repo variable support

- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/MatrixType.cs
The publish build matrix has a single entry for each platform type.
Sample output for microsoft/dotnet repo
```
Linux-amd64:
imageBuilderPaths: --path 1.0/runtime-deps/jessie/amd64/Dockerfile --path 1.0/runtime/jessie/amd64/Dockerfile --path 1.1/runtime/jessie/amd64/Dockerfile --path 1.1/sdk/jessie/amd64/Dockerfile --path 1.1/runtime-deps/stretch/amd64/Dockerfile --path 1.1/runtime/stretch/amd64/Dockerfile --path 1.1/sdk/stretch/amd64/Dockerfile --path 2.1/runtime-deps/stretch-slim/amd64/Dockerfile --path 2.1/runtime/stretch-slim/amd64/Dockerfile --path 2.1/aspnetcore-runtime/stretch-slim/amd64/Dockerfile --path 2.1/sdk/stretch/amd64/Dockerfile --path 2.1/runtime-deps/alpine3.7/amd64/Dockerfile --path 2.1/runtime/alpine3.7/amd64/Dockerfile --path …
```
> Add support for a publish build matrix type

- Microsoft.DotNet.ImageBuilder/Dockerfile.debian
- Microsoft.DotNet.ImageBuilder/src/AzureHelper.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/BuildOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/CopyAcrImagesCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/CopyAcrImagesOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/CopyImagesOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/DockerRegistryCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/DockerRegistryOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/IManifestFilterOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/Options.cs
- Microsoft.DotNet.ImageBuilder/src/Model/Manifest.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/IOptionsInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestFilter.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/RepoInfo.cs
- Add options for overriding the registry and specifying a repo prefix.
- Removed the server options since they were redundant with the new registry option.
- Add support for FROM references across repos within the manifest.
- Upgraded the manifest-tool to pick up an ACR bug fix.
- Changed the source-repo option of the ACR copy command to be source-repo-prefix.
- Added an option to specify the os-type.  This is needed in order to run the ACR copy command on linux when coping Windows images.
- Refactored the publish matrix to be more fine grained.  The Linux amd64 copy leg was taking 1/2 hr and the goal for publish is ~5 mins.
> Misc changes to support MCR

- Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/BuildOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/CopyAcrImagesCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/CopyAcrImagesOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/CopyImagesCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/CopyImagesOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateTagsReadmeCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/IManifestFilterOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/Options.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/UpdateReadmeCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/UpdateVersionsOptions.cs
- Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ImageInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestFilter.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/RepoInfo.cs
The underlying problem that needed to be fixed was that when initializing the PlatformInfo instances, the InitializeBuildArgs logic needs to access the unfiltered Repo view model which didn't exist.  This lead me to realize the messiness of the view model in that it did not consistently expose the filtered and unfiltered items.  I decided to standardize around the terms 'filtered' and 'all' in order to make it unambiguous as to what the properties/members mean.
> Standardize around 'filtered' and 'all' view model properties

- Microsoft.DotNet.ImageBuilder/src/Commands/PublishMcrReadmesCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/PublishMcrReadmesOptions.cs
- Microsoft.DotNet.ImageBuilder/src/ImageBuilder.cs
- Microsoft.DotNet.ImageBuilder/src/Model/Manifest.cs
This command is needed in order to publish the readmes that reside in the product github repos to the mcrdocs repo.  This is where MCR gets the readmes that it pushes to Docker Hub.
> Add PublishMcrReadmesCommand

- Microsoft.DotNet.ImageBuilder/src/Commands/BuildOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/CopyAcrImagesOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/CopyImagesOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateTagsReadmeOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/IManifestFilterOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/ManifestFilterOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/Options.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/PublishMcrReadmesOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/UpdateReadmeOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/UpdateVersionsOptions.cs
- Compute CommandName from class name instead of having it declared on each Options class.
- Encapsulate manifest options in a single composed class vs an interface implemented numerous times.
> Misc cleanup of Options classes

- Microsoft.DotNet.ImageBuilder/src/Commands/ValidateImageSizeCommand.cs
Misc refactoring to make the output more friendly to scan.  The results are no longer intermixed with the docker pull output.  I also added more classification to the results - exact match, in range variance, out of range variance, no baseline data.
> Refactoring validateImageSize output

- README.md
This is just very basics about the tool.   We can add more to this over time.  The primary reason for adding it now is to document where the Docker images are being published.
@dotnet-bot skip ci please.
> Updating readme to describe the basics of the image-builder tool

- Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/ManifestFilterOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestCommand.cs
- Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- Microsoft.DotNet.ImageBuilder/src/ExecuteHelper.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestFilter.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ModelExtensions.cs
Ensures the build command on ImageBuilder will produce an image whose architecture matches the expected value in case Docker decides to misrepresent it.
> Update build command to update architecture metadata if necessary

- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/ManifestFilterOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestCommand.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestFilter.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ModelExtensions.cs
The primary issue being addressed here is to fixup the dotnet/core/samples build.  The publish matrix is invalid in that there are multiple entries with the same name.  The reason for this is that with the samples the same Dockerfiles are used/built on each platform
Current:
```
publishMatrix:
samples-Dockerfile-amd64:
dotnetVersion: samples
osType: linux
osVariant: Dockerfile
osVersion: *
architecture: amd64
samples-Dockerfile-amd64:
dotnetVersion: samples
osType: windows
osVariant: Dockerfile
osVersion: nanoserver-sac2016
architecture: amd64
samples-Dockerfile-amd64:
dotnetVersion: samples
osType: windows
osVariant: Dockerfile
osVersion: nanoserver-1809
architecture: amd64
samples-Dockerfile-amd64:
dotnetVersion: samples
osType: windows
osVariant: Dockerfile
osVersion: nanoserver-1803 …
```
> Refactor build and publish matrices to include platform variables

- .vsts-pipelines/dotnet-buildtools-image-builder-official.yml
- .vsts-pipelines/dotnet-buildtools-image-builder-pr.yml
- Microsoft.DotNet.ImageBuilder/Dockerfile.debian
- Microsoft.DotNet.ImageBuilder/Dockerfile.nanoserver
- Microsoft.DotNet.ImageBuilder/src/Commands/ValidateImageSizeCommand.cs
1. Refactor the ValidateImageSize command to not write the validation error detailed output to stdout as stdin and stdout get separated when looking at AzDO build output.  The headers were getting separated which made it very confusing to read.  Instead if there are any errors detected a failure message is written to stdout at the end of the processing.
2. Fixed an issue in the official builds that was causing the images to not get pushed.
3. Refactored the Dockerfiles to pull images from MCR.
> Refactor validateImageSize errors to work with AzDO pipelines

- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/MatrixType.cs
- Microsoft.DotNet.ImageBuilder/src/StringExtensions.cs
For the PR builds, we need to be able to build and test within a single job.  But the build matrix that is currently generated is not suited for that scenario because it is grouped on OS/arch.  This splits out the building of images like runtime and sdk that have a dependency on each other.  This won't work for the PR builds because the tests will require the set of images (runtime, sdk, etc) to be available which means that the build phase must have built all of those images in that job.
To accomplish this, we need to just use the same matrix as is generated for tests but use it as a build matrix instead.  A new option is added for the generateBuildMatrix command to indicate that it is for a PR build.  If that option is set, it will return a build matrix that is shaped just like the test …
> Update build matrix to support PR builds

- .vsts-pipelines/dotnet-buildtools-image-builder-official.yml
- .vsts-pipelines/dotnet-buildtools-image-builder-pr.yml
- .vsts-pipelines/jobs/build-image-builder-image.yml
- .vsts-pipelines/jobs/build-image-builder.yml
- Microsoft.DotNet.ImageBuilder/build.ps1
Currently the timestamp portion of the linux and windows images are different.  It would be nice if they aligned as it helps to consumption story.  This change defines a shared timestamp variable that the linux and windows build legs consume.  
I'm open to suggestions to simplify the pattern used here.
> Refactor build to use the same tag timestamp across images

- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/MatrixType.cs
- Microsoft.DotNet.ImageBuilder/src/Model/CustomBuildLegGrouping.cs
- Microsoft.DotNet.ImageBuilder/src/Model/Platform.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/CustomBuildLegGroupingInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
In order to build and test the images in a given .NET version/OS leg in a single job, we need to ensure that all of images that are needed in order to tests are included in that leg.  In the case of .NET Core 1.0, the 1.1 SDK image is required in order to run the test.  But the platformVersionedOs matrix that is output by ImageBuilder doesn't include the 1.1 SDK Dockerfile path when generating the set of Dockerfile paths for the 1.0 legs.  The manifest doesn't currently have a mechanism for describing such a dependency that is required solely for testing.
These changes update the manifest schema such that a platform can have a set of test dependencies (i.e. image tags required by the platform in order to test it).  Here's a snippet of the manifest for the 1.0 section illustrating how this …
> Add TestDependencyGraph matrix type

- Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestCommand.cs
In my local benchmark, this cut the Publish Manifest time for dotnet-docker from 2 min 35 sec down to 37 sec.
Related to #165
> Refactor PublishManifestCommand to utilize parallel processing

- Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestOptions.cs
You can now run the following command in the dotnet-docker repo
`-- publishManifest --path '3.0*'`
to publish the 3.0 related multi-arch tags.
```
MANIFEST TAGS PUBLISHED
-----------------------
mcr.microsoft.com/dotnet/core-nightly/runtime-deps:3.0.0-preview5
mcr.microsoft.com/dotnet/core-nightly/runtime-deps:3.0
mcr.microsoft.com/dotnet/core-nightly/runtime:3.0.0-preview5
mcr.microsoft.com/dotnet/core-nightly/runtime:3.0
mcr.microsoft.com/dotnet/core-nightly/aspnet:3.0.0-preview5
mcr.microsoft.com/dotnet/core-nightly/aspnet:3.0
mcr.microsoft.com/dotnet/core-nightly/sdk:3.0.100-preview5
mcr.microsoft.com/dotnet/core-nightly/sdk:3.0
```
> Refactor PublishManifestCommand to support image filters

- .vsts-pipelines/validate-remote-docker-config.yml
- .vsts-pipelines/variables/docker-images.yml
This is a build definition that will up us and DDFUN validate the build agents that are configured to use a remote ARM docker daemon.
The build definition validates the following:
1. Remote daemon is reachable (validates the cert configuration) 
1. Remote daemon can run a container and that it has network access.
We can add more to this over time as we see fit.
> Introduce build definition to validate remote Docker daemon config

- .vsts-pipelines/validate-remote-docker-config.yml
I overlooked that the pr validation agent pool does not have the same machines as the official build.
> Add support for RPI agents in validate-remote-docker pipeline

- Microsoft.DotNet.ImageBuilder/src/ViewModel/ImageInfo.cs
Fixes #182 
The ImageInfo.AllPlatforms member was incorrectly getting populated off of the filtered model.
> Fix AllPlatforms member to not be filtered

- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateTagsReadmeCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateTagsReadmeOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/McrTagsMetadataGenerator.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/Options.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/PublishMcrDocsCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/PublishMcrDocsOptions.cs
- Microsoft.DotNet.ImageBuilder/src/ImageBuilder.cs
- Microsoft.DotNet.ImageBuilder/src/Model/Platform.cs
- Microsoft.DotNet.ImageBuilder/src/Model/Repo.cs
- Microsoft.DotNet.ImageBuilder/src/ReadmeHelper.cs
- Microsoft.DotNet.ImageBuilder/src/StringExtensions.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestInfo.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/VariableHelper.cs
Related to https://github.com/dotnet/dotnet-docker/issues/990
- Refactor the GenerateTagsReadmeCommand to generate the MCR tags metadata and use the MCR tool to generate the tags table off of the MCR metadata.
- Refactor the PublishMcrReadmeCommand (renamed to PublishMcrDocsCommand) to generate the MCR tags metadata, strip out the tags listing in the readme, and publish the artifacts to McrDocs
- In support of the previous two commands, two model schema changes were introduced.  First the osVersion is now a required property.  Second the McrTagsMetadataTemplatePath was added to the Repo.
A sample of the output can be view at https://hub.docker.com/_/microsoft-dotnet-core-nightly-aspnet/.
The repo changes to consume this can be viewed at …
> Add support for generating MCR tags YAML and producing tags listing from it

- Microsoft.DotNet.ImageBuilder/src/Commands/RebuildStaleImagesCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/RebuildStaleImagesOptions.cs
The RebuildStaleImages command currently enumerates all images in the manifest and attempts to pull them to get their base image digest value.  This can't be done when there is a mix of Linux and Windows images because you can't pull a Windows image from a Linux Docker host, for example.  For that reason, there needs to be filtering options for the command that are applied to the manifests that are consumed.
> Enable manifest filtering for RebuildStaleImages command

- scripts/Invoke-AcrCleanup.ps1
Deletion of the repository requires the `-y` flag to confirm the deletion in an automated scenario.
> Add switch to confirm repo deletion

- Microsoft.DotNet.ImageBuilder/src/Commands/ShowImageStatsCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/ShowImageStatsOptions.cs
- Microsoft.DotNet.ImageBuilder/src/ImageBuilder.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ViewModelExtensions.cs
I've had a variation of this command in my local fork and find it useful from time to time.  I decided to check it in to make is generally available.  It is helpful for seeing the total number of images within a repo and what the external image dependencies are.  We should add to it going forward as needed.
Sample output of running the command on https://github.com/dotnet/dotnet-docker/tree/nightly
```
IMAGE STATISTICS
----------------
Total Unique Images:  129
Total Concrete Tags:  304
Total Undocumented Concrete Tags:  6
Total Multi-Platform Tags:  36
Total Tags:  340
External Base Images (36)                            Dependent Images   Dependent Concrete Tags  Dependent Multi-Platform Tags  Total Dependent Tags
-------------------------------------------------------------------------- …
```
> Add a showImageStats command that displays various image statistics

- Microsoft.DotNet.ImageBuilder/src/Commands/ShowImageStatsCommand.cs
This aligns the nomenclature used by the Official Repositories on Docker Hub to differentiate the two types of tags.
> Change showImageStats nomenclature from concrete tags to simple tags

- eng/common/templates/jobs/build-images.yml
- eng/common/templates/jobs/post-build.yml
- eng/common/templates/jobs/publish.yml
- eng/common/templates/stages/build-test-publish-repo.yml
- eng/common/templates/steps/download-build-artifact.yml
- eng/common/templates/steps/init-docker-linux.yml
- eng/common/templates/steps/init-docker-windows.yml
- eng/common/templates/steps/test-images-linux-client.yml
- eng/common/templates/steps/test-images-windows-client.yml
- eng/common/templates/variables/docker-images.yml
These changes update the build pipeline to provide support for the scenario described by #218. The goal is for the test stage to be able to run tests for an image that was built by the build but the test requires images that were not built during the build. An example of this is provided in #218.
To solve this, the image info files produced by the build are being utilized to track image tag information that can then be read by the test project to determine which images were actually produced by the build. For those images, the test code will pull them from the staging location, where they were pushed during the build stage. For any other images that the test requires, it will pull them from the public MCR location.
A new Post_Build stage has been added which calls Image Builder to …
> Pipeline changes to support testing partial graph

- Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoCommand.cs
- Microsoft.DotNet.ImageBuilder/src/GitHelper.cs
Updates the PublishImageInfoCommand class to include logging messages regarding whether the image info file was updated.  If the file was updated, a link to the commit is provided.
Fixes #202
> Add better logging to PublishImageInfo command

- Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
- Microsoft.DotNet.ImageBuilder/tests/MergeInfoFilesCommandTests.cs
Ensures that simple tags gets merged appropriately when merging image info data.  I've generalized the algorithm to use reflection to ensure that every property is accounted for to prevent issues like this in the future.  Updates unit tests to verify the scenario.
Fixes #233
> Include simple tags when merging image info

- Microsoft.DotNet.ImageBuilder/src/Commands/CopyAcrImagesCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/CopyAcrImagesOptions.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/TagInfo.cs
Updates the CopyAcrImages command to optionally incorporate the data from the image info file.  This is necessary to handle image tags that make use of dynamically generated values, such as timestamps.  Without these changes, Image Builder would calculate a new tag value each time it is invoked.  This is obviously not good when we're trying to reference the tag of an image that was built in a separate build step.
By making use of the image info file that was generated when the image was built, we know the exact static value of the tag that needs to be referenced.  So when the CopyAcrImages command runs and finds a Platform to process, it looks up the tag value in the image info file instead of using the value that was calculated when parsing the manifest.
> Image info file support for CopyAcrImages cmd

- eng/Invoke-AcrCleanup.ps1
The cleanup-acr-images pipeline recently broke because of a [change in the version](https://github.com/microsoft/azure-pipelines-image-generation/compare/ubuntu16/156.2...releases/ubuntu16/156#diff-f87405c9dd43f633a04dd078666d61afR7) of the az CLI used in the Hosted Ubuntu 16.04 pool.  The build was failing attempting to call `az login`.  This command no longer accepts a `subscription` parameter.  The fix is to remove that argument and set the subscription in a separate command.
I also removed the other condition when the `ServicePrincipalName` is not set since that's not a scenario that the pipeline uses.
> Remove subscription parameter to az login

- Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
The `PublishTrimmed` option in the ImageBuilder project is causing the resulting image to be inoperable.  It causes the following exception:
```
System.TypeLoadException: Could not load type 'System.Collections.Immutable.ImmutableDictionary`2' from assembly 'System.Diagnostics.TextWriterTraceListener, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
at Microsoft.DotNet.ImageBuilder.ViewModel.PlatformInfo.InitializeBuildArgs()
at Microsoft.DotNet.ImageBuilder.ViewModel.PlatformInfo.Initialize(IEnumerable`1 internalRepos, String registry)
at Microsoft.DotNet.ImageBuilder.ViewModel.ManifestInfo.Create(String manifestPath, ManifestFilter manifestFilter, IManifestOptionsInfo options)
at Microsoft.DotNet.ImageBuilder.ViewModel.ManifestInfo.Load(IManifestOptionsInfo options) …
```
> Disable publish trimming

- eng/common/templates/steps/test-images-windows-client.yml
* This is a port of changes made in https://github.com/microsoft/dotnet-framework-docker with the addition of the WCF and Asp.Net repos to be able to use a test argument to filter and only run applicable tests.
> Support providing additional test args.

- eng/pipelines/check-base-image-updates.yml
- eng/pipelines/templates/steps/queue-build-for-stale-images.yml
The check-base-image-updates wasn't checking whether ARM-based images had been updated.  This updates the pipeline to run the check on ARM hardware for both Linux and Windows.
Fixes #237
> Add ARM support for check-base-image-updates pipeline

- Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/RebuildStaleImagesCommand.cs
- Microsoft.DotNet.ImageBuilder/src/GitHelper.cs
- Microsoft.DotNet.ImageBuilder/tests/RebuildStaleImagesCommandTests.cs
The PublishImageInfoCommand is writing status messages indicating that the _source_ image file was either updated or not, when in fact it should be referring to the _destination_ image file (the one in GitHub).  Fixed this and also centralized the construction of GitHub URLs into the GitHelper class.
> Update PublishImageInfoCommand messages

- eng/common/templates/jobs/publish.yml
When the different .NET Docker repos build images and publish the results to the [image-info.json](https://github.com/dotnet/versions/blob/master/build-info/docker/image-info.json) file, it is possible they can be overwriting data if not all of the repos are using the same image info schema.  In addition, it'd also be beneficial from a readability perspective, to view the image info content for just a single GitHub repo.
For those reasons, we're going to split the existing [image-info.json](https://github.com/dotnet/versions/blob/master/build-info/docker/image-info.json) into a set of image info files, each one specific to a particular GitHub repo and branch.  Until this is completely rolled out, we're going to maintain the original image info file but also introduce each of these new …
> Integrate image info split publish change

- eng/common/templates/jobs/build-images.yml
- eng/common/templates/steps/cleanup-docker-linux.yml
- eng/common/templates/steps/init-docker-linux.yml
- eng/common/templates/steps/test-images-linux-client.yml
- eng/common/templates/variables/common.yml
Integrates the changes that were made in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/168 to support custom `docker run` options.
> Support for custom docker run options

- Microsoft.DotNet.ImageBuilder/src/Commands/MergeImageInfoCommand.cs
- Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
- Microsoft.DotNet.ImageBuilder/tests/ImageInfoHelperTests.cs
- Microsoft.DotNet.ImageBuilder/tests/MergeInfoFilesCommandTests.cs
There's an issue with the image info merging logic that was exposed when moving a shared tag.  In this case, the shared tag `3.0-alpine` was moved from the Alpine 3.9-based images to Alpine 3.10 in the manifest.  The images were tagged appropriately but when the image info file was updated during the publish stage, the Alpine 3.9-based images in the image info continued to list `3.0-alpine` as a tag in addition to the Alpine 3.10-based images correctly listing `3.0-alpine`.  See this [commit](https://github.com/dotnet/versions/blob/31981d050666cd82e6dc472223ebf2908a916041/build-info/docker/image-info.dotnet-dotnet-docker-nightly.json#L185) for the issue.
To fix this, the merge logic is updated to always replace the `SimpleTags` list such that the source image's tag always overwrite the …
> Replace tags when merging image info

- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/QueueBuildCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/QueueBuildOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/SubscriptionImagePaths.cs
- Microsoft.DotNet.ImageBuilder/src/Models/Subscription/Subscription.cs
- Microsoft.DotNet.ImageBuilder/src/PipelineHelper.cs
- Microsoft.DotNet.ImageBuilder/tests/GetStaleImagesCommandTests.cs
- Microsoft.DotNet.ImageBuilder/tests/QueueBuildCommandTests.cs
These changes break apart the RebuildStaleImagesCommand into two separate commands: GetStaleImagesCommand and QueueBuildCommand.  This is necessary for the check-base-image-updates pipeline so that it can determine which images need to be rebuilt across both Windows and Linux as well as the different architectures before actually queuing a build.  Once all the image paths have been determined, then the final part of the build should actually queue the necessary builds.
A given job that executes GetStaleImagesCommand will be looking for changes to images across all the subscribing Git repos/branches.  And the command will produce an output variable to be consumed by the pipeline.  So there will be four such variables whose data represents the same sets of subscriptions amongst all of them. …
> Separate RebuildStaleImagesCommand into two separate commands

- Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- Microsoft.DotNet.ImageBuilder/tests/GenerateBuildMatrixCommandTests.cs
Allows images to be built without forcing the images they depend on to be built.  For example, we sometimes want to be able to publish an update to the SDK image but do not need to update the runtime image it depends upon.  This currently isn't possible because the matrix that gets generated will automatically include the base image(s).
These changes fix this by only including the base image graph in the outputted matrix if they match the path filter that was provided as input to the generateBuildMatrix command.
Fixes #186
> Build matrix fix: Don't include dependencies if not in context

- Microsoft.DotNet.ImageBuilder/src/GitHelper.cs
The `GitHelper.ExecuteGitOperationsWithRetryAsync` call results in usage of a `GitHubClient` instance that has been disposed.  This results in a `TaskCanceledException` for any calling code.
This is caused by returning the task without awaiting it.  This allows the `GitHubClient` instance to be disposed before the code which uses it to get a chance to execute.  Once it does execute, the instance is disposed and bad things happen.
Fixes #296
> Fix GitHelper operation execution code

- Microsoft.DotNet.ImageBuilder/src/ExecuteHelper.cs
Fixes #298 
Sample output for pulling a Docker image
```
-- EXECUTING: docker pull alpine:3.9
3.9: Pulling from library/alpine
e7c96db7181b: Already exists                                                                                     
Digest: sha256:7746df395af22f04212cd25a92c1d6dbc5a06a0ca9579a229ef43008d4d1302a
Status: Downloaded newer image for alpine:3.9
docker.io/library/alpine:3.9
-- EXECUTION ELAPSED TIME: 00:00:05.7446610
```
> Add logging to capture process execution time

- Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- Microsoft.DotNet.ImageBuilder/src/Commands/ManifestFilterOptions.cs
- Microsoft.DotNet.ImageBuilder/src/Models/Subscription/Subscription.cs
- Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestFilter.cs
- Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
- Microsoft.DotNet.ImageBuilder/tests/CopyAcrImagesCommandTests.cs
- Microsoft.DotNet.ImageBuilder/tests/GenerateBuildMatrixCommandTests.cs
- Microsoft.DotNet.ImageBuilder/tests/GetStaleImagesCommandTests.cs
- Microsoft.DotNet.ImageBuilder/tests/Helpers/ManifestHelper.cs
As described in #288, we need a way for the call to GetStaleImages to filter platforms by OS type with each subscription optionally declaring which OS type it wants to filter on.  
Fixes #288
> Filter by OSType for GetStaleImages subscriptions

- eng/file-pusher/FilePusher.cs
The FilePusher utility did not support pushing changes to multiple branches of a single repo concurrently.  What would happen is the tool would create a PR for one branch and then when processing the subsequent branches, it would overwrite the previous changes.
Fixes:
1. Use a unique fork branch name per upstream branch
1. Add the branch name to the beginning of the PR title
> FilePusher enhancements to support pushing to multiple branches of a repo

- eng/common/templates/jobs/build-images.yml
- eng/common/templates/stages/build-test-publish-repo.yml
Allows build jobs to run a set of custom build init steps defined by consuming pipelines.
See https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/191
> Update to support custom build init steps

- eng/pipelines/push-common-updates.yml
This defines a build pipeline which will run the FilePusher utility that pushes any updates to the eng/common to the subscribing repos.  The build gets automatically triggered whenever a change is made within the eng/common folder.  I'm proposing that we have just one build definition that references this pipeline and, by default, it will use an empty `$(filters)` variable.  If there's ever an issue with one of the subscribing repos that requires temporarily disabling syncing, we can just modify the variable appropriately.
> Pipeline to push common updates to other repos

- eng/pipelines/templates/variables/common.yml
Fixes the pipeline by adding some missing variables.  This was broken by #209.
Fixes #227
> Fix validate-remote-docker-config pipeline

- eng/common/templates/stages/build-test-publish-repo.yml
Currently there is a queue-time variable named `singlePhase` that can be used to run specific pipeline stages.  When left empty, it runs all the stages.  The problem is that there's not a way to run more than one stage other than all of them (e.g. run just the test _and_ publish phases).
These changes replace the `singleStage` variable with a new one called `stages` that can used to list which stages the pipeline should run.  By default, the pipelines will predefine this variable with all of the stages listed: "build;test;publish".  At queue time, a person can modify this to specify which stages should be run.
Fixes #295
> Allow multiple pipeline stages to be explicitly defined to run

- eng/pipelines/templates/jobs/build-image-builder.yml
Currently the `Hosted Windows Container` pool contains 1803 which is now EOL.  Because of this, the .NET SDK image can no longer be pulled.
Workaround for https://github.com/dotnet/core-eng/issues/8339
> Change Windows build pool used by image-builder pools

- eng/common/templates/stages/build-test-publish-repo.yml
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
There is essentially duplication in the pipeline in the build and test stages for the Windows jobs because there are sections for handling both a NanoServer-labeled matrix and ServerCore-labeled matrix.  Both of these use the same type of agent pool for their respective Windows version.  These are being consolidate with these changes.  For 1809 amd64, this will now be labeled as ltsc2019.
What this looks like from a consuming perspective is that the manifest must change from using `nanoserver` or `windowsservercore` to just `windows`.
Example (nanoserver):
* Old: `"osVersion": "nanoserver-1909"`
* New `"osVersion": "windows-1909"`
Example (servercore using 1809):
* Old: `"osVersion": "windowsservercore-1809"`
* New `"osVersion": "windows-ltsc2019"`
Fixes #278
> Consolidate Windows-based job pools in pipeline

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GetStaleImagesCommandTests.cs
The GetStaleImagesCommand recently started failing after the change to update the samples to 3.1 (https://github.com/dotnet/dotnet-docker/pull/1517).  When processing those changed Dockerfiles, the command was throwing a `KeyNotFoundException` when trying to lookup the base image data for `mcr.microsoft.com/dotnet/core/sdk:3.1` from the image info.  But no such data existed because a build hasn't yet run to produce the new sample images and update the image info file.  The command needs to gracefully handles this and mark such an image as needing to be rebuilt.
> GetStaleImagesCommand fix for unknown base images

- eng/pipelines/check-base-image-updates.yml
- eng/pipelines/templates/steps/get-stale-images.yml
The `check-base-image-updates` pipeline is not scanning ARM32 Linux base images.  In order to check for both ARM32 and ARM64 base images, the logic needs to explicitly set the `architecture` option when calling the `getStaleImages` command.  Otherwise, it'll end up using the default architecture of the daemon: AArch64 => ARM64.
Fixes #342
> Fix ARM-based base image checks

- eng/common/templates/steps/test-images-linux-client.yml
Provides support for a pipeline to pass in additional test arguments when calling the `run-tests.ps1` script in Linux scenarios.  This functionality already exists for Windows scenarios, so this is just providing parity.
> Support for optional test args for Linux

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyAcrImagesOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/DockerRegistryOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateTagsReadmeOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GitOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/ImageSizeOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/ManifestFilterOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/ManifestOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/MergeImageInfoOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/Options.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishMcrDocsOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/QueueBuildOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/ShowImageStatsOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/UpdateImageSizeBaselineOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/ValidateImageSizeOptions.cs
The changes from https://github.com/dotnet/docker-tools/pull/350 are broken due to defining command options before the command has been defined in the `ArgumentSyntax` object.  The problem in resolving this is that options need to be defined before parameters and the `ImageSizeOptions` base class defines both options and parameters.  So deriving classes need to call the base `ParseCommandLine` method in order to define the command but doing so prevents them from adding additional options because the base class added a parameter.
To solve this, I've update the `Options` class to split apart the defining of options and parameters into separate virtual methods.  It first defines all options, allowing all classes in the inheritance hierarchy to add their options, and then similarly follows …
> Fix option/parameter ordering for commands

- src/Microsoft.DotNet.ImageBuilder/src/Commands/ImageSizeOptions.cs
Commands deriving from `ImageSizeCommand` did not have their filtering options applied.  This is because the property was reinstatiating the `ManifestFilterOptions` class each time the property was accessed.
> Fix FilterOptions in ImageSizeOptions class

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/IGitOptionsHost.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/IOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/Options.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishMcrDocsCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/GitHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/GitHubClientFactory.cs
- src/Microsoft.DotNet.ImageBuilder/src/IGitHubClientFactory.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/IManifestOptionsInfo.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GetStaleImagesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishImageInfoCommandTests.cs
Updates the ImageBuilder commands to ensure they do not execute any git commands that have side effects when the `dry-run` option is used.  This is specifically for the `publishImageInfo` and `publishMcrDocs` commands.  These changes are necessary in order to support the fix for #371.
Each command is implemented to explicitly account for the scenario when `dry-run` is true.  But in addition to that, a safeguard is added by implementing a wrapper around `GitHubClient` that will throw if an attempt is made to execute an operation with side effects when `dry-run` is enabled.
> Prevent git repo side effects when dry-run is used

- eng/common/templates/jobs/publish.yml
- eng/common/templates/variables/common.yml
* Uses the `--dry-option` option when invoking the `publishMcrDocs` and `publishImageInfo` commands when not running production builds.
* Changed the task that invokes `publishImageInfo` to always be invoked in order to better exercise the command.
* Removed the `publishReadme` variable since it was always set to `true`.
Fixes #371
> Prevent publishing of git assets on test build

- eng/common/templates/jobs/build-images.yml
2.2 Dockerfiles are no longer built because it is EOL so this task in the pipeline can be deleted.
Fixes #363
> Remove 2.2 workaround in build-images.yml

- eng/common/templates/jobs/publish.yml
- eng/common/templates/variables/common.yml
The changes in https://github.com/dotnet/docker-tools/pull/377 caused a regression in the build for the https://github.com/dotnet/dotnet-buildtools-prereqs-docker repo when running the publish stage. It attempts to publish a readme but that repo has no associated readme so the task fails. Adding back the logic to conditionally execute the task to publish a readme.
> Revert change that removed publishReadme condition from task

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyAcrImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishMcrDocsCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/McrTagsMetadataGenerator.cs
- src/Microsoft.DotNet.ImageBuilder/src/PathHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestInfo.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/ModelExtensions.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
- src/Microsoft.DotNet.ImageBuilder/tests/CopyAcrImagesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/McrTagsMetadataGeneratorTests.cs
Updates ImageBuilder logic to support a manifest file being located in a different folder from the current working directory (i.e. the root of the repo in most cases).  This is needed in order to support #305 where we want to make use of a fake manifest file located in a test folder.
All file paths referenced from within the manifest file (e.g. readme files) should be relative to the location of the manifest file.  Similarly, the `--path` filter options that can be passed to various ImageBuilder commands should also be relative to the manifest file.
Fixes #370
> Support non-root folder for manifest file

- eng/common/templates/jobs/publish.yml
The condition for determining whether to use a dry run for the publish stage is incorrectly.  It's not referencing the `PUBLISHREPOPREFIX` variable with the correct syntax.  This causes official builds to use dry runs for certain tasks, not updating the appropriate GitHub files.
> Fix publish condition for calculating whether to do a dry run

- src/Microsoft.DotNet.ImageBuilder/src/McrTagsMetadataGenerator.cs
The motivation for this change is that when there is a validation error, it is very helpful to see the generated yaml which is invalid.
> Tweak McrTagsMetadataGenerator to dump out generated metadata before validating

- .dockerignore
- eng/common/templates/steps/test-images-linux-client.yml
- eng/common/templates/steps/test-images-windows-client.yml
- eng/common/templates/variables/common-paths.yml
- eng/pipelines/dotnet-docker-tools-eng-validation.yml
- eng/pipelines/dotnet-docker-tools-pr.yml
- test/pipeline-validation/1.0/focal/amd64/Dockerfile
- test/pipeline-validation/1.0/focal/arm64v8/Dockerfile
- test/pipeline-validation/1.0/nanoserver-1809/amd64/Dockerfile
- test/pipeline-validation/1.0/nanoserver-1809/arm32v7/Dockerfile
- test/pipeline-validation/README.placeholder.md
- test/pipeline-validation/run-tests.ps1
- test/pipeline-validation/test-manifest.json
- test/pipeline-validation/test-tags.yml
Defines a pipeline for testing the pipeline infrastructure.  This uses a set of fake files (manifest, Dockerfiles, etc) to run a build with.  This is intended to mainly test the pipeline YAML infrastructure but also does a run through the relevant logic of ImageBuilder that gets invoked by the tasks in the pipeline.  This is not a comprehensive test that will validate everything and should be considered to be more of a smoke test.  When pipeline changes get propagated to the other Docker repos (dotnet-docker, etc) those PRs will do the ultimate verification for those specific repos.
Examples of issues that would be caught by this pipeline before changes are propagated to other repos:
* https://github.com/dotnet/docker-tools/pull/361
* https://github.com/dotnet/docker-tools/pull/336
Fixes …
> Add build infra testing pipeline

- eng/common/build.ps1
The common build script no longer needs to implement testing logic because this is handled by each consuming repo's build script.
* Remove test logic and associated parameters from the build script
* Renamed script to `build.ps1`
* Added script documentation
Fixes #364
> Remove testing logic from common build script

- eng/common/templates/jobs/publish.yml
- eng/common/templates/jobs/validate-image-sizes.yml
- eng/common/templates/steps/publish-readmes.yml
- eng/common/templates/steps/validate-image-sizes.yml
These changes add support for the following:
1. A pipeline that just publishes the readmes.
2. A pipeline that runs the image size validation tests.
> backporting eng\common changes from the dotnet-docker repo

- src/Microsoft.DotNet.ImageBuilder/src/Commands/UpdateImageSizeBaselineCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/ValidateImageSizeCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/ValidateImageSizeOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/ReadmeHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/StringExtensions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/ValidateImageSizeCommandTests.cs
Adds an option to the `validateImageSize` command to skip the baseline integrity check.  This is needed to support https://github.com/dotnet/dotnet-docker/issues/1588 so that a build job can validate a partial set of images and not run into issues with the baseline integrity check.
> Option to skip baseline integrity check for size validation

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/releases/new-windows-release.md
- eng/pipelines/dotnet-buildtools-image-builder-pr.yml
Defines an issue template for tracking the common set of tasks (between both .NET Core and .NET Fx) that need to be done in preparation for a new version of Windows.
Also defines a default bug template.
Related to #383
> Issue template for new Windows release

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetBaseImageStatusCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetBaseImageStatusOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerService.cs
- src/Microsoft.DotNet.ImageBuilder/src/IDockerService.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
Defines an ImageBuilder command that will display the "created date" status for external base images referenced by the Dockerfiles.
Related to #402
> Command to display base image status

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetBaseImageStatusCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetBaseImageStatusOptions.cs
Adds an option to the `getBaseImageStatus` command to allow the operation to run continuously.  This is useful so that the user can be assured that new images will be pulled down when they become available without needing to constantly pay attention and re-running the command manually.
Related to #402
> Continuous mode option for GetBaseImageStatus cmd

- eng/common/Get-BaseImageStatus.ps1
- eng/common/templates/variables/docker-images.yml
Adds a wrapper script for the `getBaseImageStatus` command (see https://github.com/dotnet/docker-tools/pull/410) to allow callers to get the status of base images.
Fixes #402
> Common script to get base image status

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GetStaleImagesCommandTests.cs
The `getStaleImages` command was incorrectly marking images to be rebuilt when they should not have been.  This was a regression from https://github.com/dotnet/docker-tools/pull/412 that caused it to include internal FROM images in its processing.
Fixed by updating the logic to only include external FROM images.
Also fixed a logic issue in the output logging.
> Fix stale image check to not include internal images

- eng/common/templates/steps/test-images-windows-client.yml
- src/Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/ExecuteHelper.cs
Fixes two cases where we execute `docker login` with no retry logic.
Fixes #403
> Retry docker login

- eng/common/templates/jobs/publish.yml
- eng/common/templates/steps/publish-readmes.yml
- eng/common/templates/variables/common.yml
- eng/pipelines/templates/steps/get-stale-images.yml
A new variable group has been defined that are connected to a key vault specific to .NET Docker: `DotNet-Docker-Secrets-New`.  In addition, a new bot account has been created for .NET Docker usage which resulted in new variable names so a new variable group, `DotNet-Docker-Common-New`, has been defined for that as well.
These changes update the infra to reference these new variable groups and variable names.  Once things have been validated and everything is migrated over to the new groups, we can then rename them back to the original names.
Related to #380 and #381
> Reference new variable groups

- eng/common/templates/variables/common.yml
Finishes up the work of migrating to the new Key Vault for .NET Docker by renaming the temporary variable groups back to their original names.
Fixes #380 
Fixes #381
> Reset variable group names back to original value

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/ExecuteHelper.cs
Fixes `BuildCommand` to gracefully handle processing a base image that does not have a digest value.
Fixes #322
> Gracefully handle base images w/o a digest

- eng/common/templates/variables/docker-images.yml
- eng/pipelines/templates/jobs/build-image-builder.yml
Also updates the `Initialize` job in the pipeline to no longer use `Hosted Windows Container` because that pool is being [removed](https://aka.ms/removing-older-images-hosted-pools).
> Update ImageBuilder tags

- src/Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/ExecuteHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/GitHelper.cs
Not all code paths that call into `ExecuteHelper.Execute` set `ProcessStartInfo.RedirectStandardError` to `true` but the method relies on it being set to construct an error message.  If `RedirectStandardError` is `false`, it will cause an error saying `System.InvalidOperationException: StandardError has not been redirected.`.
To fix this, the method will ensure that `RedirectStandardError` is set to `true` whenever it's called.
> Ensure std err is redirected

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyAcrImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/MergeImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/MergeImageInfoOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/McrTagsMetadataGenerator.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/ImageData.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/PlatformData.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/RepoData.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/CopyAcrImagesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GetStaleImagesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Helpers/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Helpers/ManifestHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/ImageInfoHelperTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/MergeImageInfoFilesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishImageInfoCommandTests.cs
In order to support data like shared tags in the image info file, the schema needs to be updated to group Dockerfiles associated with a single manifest tag just as the manifest does.  This grouping is referred to as an image while each of the underlying items are referred to as a platform.  I've updated the schema to reflect this by renaming the previously named `ImageData` to `PlatformData` because that is really what it represents now and introducing a new `ImageData` class that groups the `PlatformData` instances.
OLD schema example:
```
[
{
"repo": "repo2",
"images": [
{
"1.0/repo2/os1/Dockerfile": {
"simpleTags": [
"tag1"
],
},
"1.0/repo2/os2/Dockerfile": {
"simpleTags": [
"tag2"
],
}
}
]
}
]
```
NEW schema example:
```
[
{
"repo": "repo2",
"images": [
{
"platforms": { …
```
> Update image info schema to have image/platform concepts

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyAcrImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/MergeImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/ImageArtifactDetails.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/RepoData.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/CopyAcrImagesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GetStaleImagesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/ImageInfoHelperTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/MergeImageInfoFilesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishImageInfoCommandTests.cs
Stores a schema version in the image info file.  The previous root element of the image info file was a `RepoData` array which prevents a scalar property from being set on it.  So a new `ImageArtifactDetails`  element was defined as the root which contains a list of `RepoData` objects and the schema version.
> Store a schema version in the image info file

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/ImageData.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Manifest/Image.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/ImageInfo.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestInfo.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateBuildMatrixCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Helpers/ManifestHelper.cs
This allows us to associate each image defined in the image info file with a specific product version.  Having this data will allow for telemetry correlation between image pulls and product version.  The product version will need to be defined in the manifest which will then flow into the outputted image info file.
Related to #438
> Store product version in image info

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/ImageInfo.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/VariableHelper.cs
References to variables in the ProductVersion of the manifest were not being resolved to their underlying values.  This caused the consumers of the value from using the raw variable reference syntax value instead of the variable value.  Fixed by making the call to substitute variable values.
> Resolve variable refs in ProductVersion

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/ExecuteHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/IManifestToolService.cs
- src/Microsoft.DotNet.ImageBuilder/src/ManifestToolService.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/ManifestData.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishManifestCommandTests.cs
Adds the manifest digest to the data being tracked in image info.
Related to #438
> Include manifest digest in image info

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateBuildMatrixCommandTests.cs
Matrix generation logic doesn't correctly handle parsing of the product versions defined in the manifest if the version string contains extra text besides digits and periods (e.g. 5.0.0-preview).
Fixed the parsing to use a regex for parsing instead so that it only grabs the first portion of the string.
> Fix parsing of product version

- eng/check-base-image-subscriptions.json
The subscription is causing failures in the pipeline to check base image updates because the image info schema has changed.  Disabling for now.
> Disable dotnet-docker/nightly branch subscription

- eng/pipelines/check-base-image-updates.yml
The changes in https://github.com/dotnet/docker-tools/pull/452 were intended to setup scheduled builds for the feature/image-info-schema branch but AzDO doesn't support defining new build definitions that target a pipeline YAML file in a non-master branch if the same path exists in the master branch.  At least, that's my guess.  I had setup a new build definition that referenced the pipeline YAML file in that branch but it just ends up defaulting to the master branch where the scheduled trigger is defined for the feature/image-info-schema branch.  I've actually verified this by looking at the definition of the pipeline from the REST API and it doesn't even mention the feature/image-info-schema branch.  This resulted in no scheduled builds running for that branch.
To fix this, I'm updating …
> Update schedule trigger for base image update pipeline

- eng/common/templates/jobs/build-images.yml
- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/GitServiceExtensions.cs
- src/Microsoft.DotNet.ImageBuilder/src/McrTagsMetadataGenerator.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/PlatformData.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
Includes a `commitUrl` field in the image info file to provide a link to the specific Dockerfile the image was built from.
Fixes #438
> Store commit URL in image info file

- eng/common/templates/stages/build-test-publish-repo.yml
This allows pipelines to customize which agent pool is used for building the Linux AMD64 legs.
This is related to https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/277 since those changes caused an issue with running out of disk space on the Hosted Ubuntu 16.04 pool.  These changes will allow a different pool to be used for that pipeline.
> Parameterize Linux AMD64 pool reference

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/ImageData.cs
- src/Microsoft.DotNet.ImageBuilder/tests/ImageInfoHelperTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishImageInfoCommandTests.cs
We want to ensure the published image info files contain data only for currently supported images.  The manifest represents what is currently supported.  This updates the publish logic to remove any content from the target image info file that isn't represented in the manifest.
Related to #436
> Clean old data from image info file on publish

- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
Adds support for display names of operating systems used by https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/master/manifest.json.
> Add OS display names

- eng/common/templates/jobs/post-build.yml
- eng/common/templates/jobs/publish.yml
The changes in #437 caused `MergeImageInfoCommand` to consume a manifest.  But the pipeline YAML wasn't updated to specify a manifest option.  So, by default, the command uses `manifest.json` as the manifest path.  This will break any scenario where the manifest is not at that path.
Updating the pipeline to explicitly set the manifest option.
> Explicitly define manifest for merging image infos

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixOptions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateBuildMatrixCommandTests.cs
The current logic for consuming the productVersion attribute from the manifest is broken because it only makes use of the major/minor components of the value.  That's fine for .NET Core but doesn't work for .NET Framework for framework versions like 4.7.2 where the "2" is significant in the generation of the matrix.  This results in incorrectly defined build/test legs.
Fixing this by adding an option to specify how many components of the product version are significant.
> Adds option to specify which version components are significant

- eng/common/templates/jobs/generate-matrix.yml
- eng/common/templates/variables/common.yml
Set the product version components option as part of the pipeline when generating the build matrix.
> Specify product version components option for matrix

- eng/common/build.ps1
The way the `Path` filter was being appended to the ImageBuilder args made it difficult and confusing to use.  The `--path` option wasn't being prepended so the user needed to include it in the arg value. It was in a way behaving no different than the `OptionalImageBuilderArgs` except that it overrode the `Version` arg.  I changed the behavior so that `--path` gets prepended to the arg value.
> Update common build.ps1 scipt's handling of path arg

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateBuildMatrixCommandTests.cs
Fix a parsing issue with the product version when generating a build matrix.  `Version.ToString(int)` doesn't allow a number to be passed that's greater than the number of components in the version.
> Fix product version parsing for build matrix

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GetStaleImagesCommandTests.cs
The logic in `GetStaleImagesCommand` produced an incorrect set of Dockerfile paths to be rebuild in the case where image info data didn't exist for a Dockerfile which other Dockerfiles were dependent upon.  For example, it there was no image data for a runtime-deps Dockerfile, then the command would only output that the runtime-deps Dockerfile needed to be rebuilt.  It didn't walk the graph and also output that runtime and aspnet also needed to be rebuilt.
There already existed logic for handling the graph walking when the image info _did_ exist but that wasn't executed for the scenario where it didn't exist.  Updated the logic to fix this.
Other changes:
* Added a test to catch this case and also fixed the logic in another test because it wasn't correctly constructing a graph of …
> Fix graph generation for base image change detection

- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyAcrImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/CopyAcrImagesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GetStaleImagesCommandTests.cs
An issue was identified where not all sample images are being published.  The issue occurs in the `CopyAcrImagesCommand` logic that attempts to find the associated image info's platform with a platform from the manifest.  This was only using the Dockerfile path for the comparison. But it should be comparing all the distinct aspects that make up a platform.  This is fixed by using the `PlatformData.Equals(PlatformInfo)` method which correctly encapsulates this logic.
I also searched for other other that was incorrectly making this comparison and found logic in `GetStaleImagesCommand` that also needed to be updated.
> Fix comparison of platforms in commands

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyAcrImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateTagsReadmeCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/ImageSizeCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/ManifestOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishMcrDocsCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/McrTagsMetadataGenerator.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/IManifestOptionsInfo.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestInfo.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/RepoInfo.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/VariableHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/McrTagsMetadataGeneratorTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishImageInfoCommandTests.cs
We want to ensure the published image info files contain data only for currently supported images. The manifest represents what is currently supported. This updates the publish logic to remove any content from the target image info file that isn't represented in the manifest.
This is mostly just restoring the code from https://github.com/dotnet/docker-tools/pull/459 but fixes the bug that was contained in it and updates the test to account for the bug.  The bug was that it was ending up not finding any matching content between the manifest and target image info file because repo names weren't being compared correctly.  This meant that the source image info would simply overwrite the contents of the target image info.
Fixes #436
> Clean out-of-date image info content on publish

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GitOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/QueueBuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/GitHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Subscription/GitFile.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Subscription/Subscription.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GetStaleImagesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishImageInfoCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/QueueBuildCommandTests.cs
The changes in https://github.com/dotnet/docker-tools/pull/478 provide the logic to remove any content in an image file that isn't represented in the manifest.  The problem is that sample images are contained in a separate manifest but have their image info contained in the same file as the product.  This would cause the clean-up logic for publishing sample images to blow away the product image info content because it doesn't exist in the sample's manifest file (and vice versa with publishing product images).
This can be solved by having separate image info files that each correspond to a single manifest.  There should be a 1:1 correspondence to avoid issues.  These changes update Image Builder to support this.  The previous implementation was never great because knowledge of the image …
> Support manifest-specific image infos in ImageBuilder

- src/Microsoft.DotNet.ImageBuilder/tests/GetStaleImagesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishImageInfoCommandTests.cs
The changes between #478, #482, and #484 were all merged without re-running the PR build.  These PRs all had changes that caused build errors when combined with the others.  Fixing those errors to get the build working again.
> Fix broken tests due to incompatible code changes

- eng/check-base-image-subscriptions.json
- eng/common/templates/jobs/publish.yml
- eng/common/templates/variables/common.yml
- eng/common/templates/variables/docker-images.yml
- eng/pipelines/templates/steps/get-stale-images.yml
Updates pipeline-related files to support the manifest-specific image info design defined by Image Builder in #482.
> Support manifest-specific image infos in pipeline

- eng/check-base-image-subscriptions.json
The schema for the subscriptions file was updated in https://github.com/dotnet/docker-tools/pull/482.  During the PR review process, the name of the `GitFile.RepoName` property was renamed to `GitFile.Repo`.  But the subscriptions file wasn't updated to reflect that change.  Updating that here.
> Fix field name used in subscriptions file

- src/Microsoft.DotNet.ImageBuilder/src/Commands/ImageInfoOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/IngestKustImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/IngestKustoImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/IngestKustoImageInfoOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
- src/Microsoft.DotNet.ImageBuilder/src/Services/IKustoClient.cs
- src/Microsoft.DotNet.ImageBuilder/src/Services/KustoClient.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Helpers/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/IngestKustoImageInfoCommandTests.cs
Add IngestImageInfoTelemetryCommand that is intended to ingest the image-info into Kusto for reporting purposes.  The data that gets imported is only for the concrete images.
> Add IngestImageInfoTelemetryCommand

- eng/check-base-image-subscriptions.json
The branch for the .NET Core samples subscription was incorrectly defined to target the nightly branch.  Fixed it to target the master branch instead.
> Fix subscription branch for .NET Core samples

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateBuildMatrixCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Helpers/ManifestHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/IngestKustoImageInfoCommandTests.cs
An issue exists with the matrix generation logic that consumes the customBuildLegGrouping from the manifest.  It doesn't walk the parent graph to produce the full set of images that should be built.
An example is with 5.0 Alpine on ARM where there exists no SDK image.  The manifest is defined in a way such that the 5.0 Alpine on ARM platform depends on the buster-slim ARM SDK image: https://github.com/dotnet/dotnet-docker/blob/402a1591e224b681015be628986eefa5012e940e/manifest.json#L1495.  The error in the logic causes the SDK image's parent dependencies to not be included in the imageBuilderPaths output.  
Fixed this by walking the parent graph and collecting all parents to be included in the imageBuilderPaths.
> Fix matrix generation to walk graph for customBuildLegGrouping

- src/Microsoft.DotNet.ImageBuilder/src/AcrClient.cs
- src/Microsoft.DotNet.ImageBuilder/src/AcrClientFactory.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CleanAcrImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CleanAcrImagesOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/IAcrClient.cs
- src/Microsoft.DotNet.ImageBuilder/src/IAcrClientFactory.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Acr/Catalog.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Acr/DeleteRepositoryResponse.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Acr/GetTagsResponse.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Acr/Manifest.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Acr/ManifestAttributes.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Acr/OAuthExchangeResult.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Acr/OAuthTokenResult.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Acr/Repository.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Acr/RepositoryManifests.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Acr/TagDetails.cs
- src/Microsoft.DotNet.ImageBuilder/tests/CleanAcrImagesCommandTest.cs
Adds a command that is intended to replace the logic in https://github.com/dotnet/docker-tools/blob/master/eng/Invoke-AcrCleanup.ps1.  It provides a parallel implementation to query and delete all unnecessary images from ACR in a much faster execution time.
There doesn't exist a .NET library for communicating with the ACR REST API so I had to implement my own.  Note that the [Container Registry REST API](https://docs.microsoft.com/en-us/rest/api/containerregistry/) isn't actually sufficient because that API only provides access for managing Azure resources.  But the things that we need to access are within the registry itself which is outside the jurisdiction of Azure resources.
Related to #419
Related to #461
> Command to delete unnecessary images from ACR

- src/Microsoft.DotNet.ImageBuilder/tests/CleanAcrImagesCommandTest.cs
CredScan incorrectly flagged this test file as containing secrets.  Updated the file to use the recommended value of `PLACEHOLDER` to avoid being flagged.
> Fix credscan issue with test file

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GitOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishMcrDocsCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/GitHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/IGitBranchRef.cs
- src/Microsoft.DotNet.ImageBuilder/src/IGitFileRef.cs
- src/Microsoft.DotNet.ImageBuilder/src/IGitRepoRef.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Subscription/GitFile.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishImageInfoCommandTests.cs
The `publishImageInfo` and `publicMcrDocs` commands did not support the `dry-run` option very well because they required GitHub credentials in order to read some files.  This is problematic as part of the work to support #474 because no credentials will be available in such a scenario.  So in order to still exercise these commands in that scenario, the commands need to be updated.
I've refactored the commands so that they now do all of their processing logic that generates the file content to be pushed before accessing GitHub.
> Fix commands to support dry-run option better

- eng/common/templates/stages/build-test-publish-repo.yml
This eliminates the redundancy in the various build UI like `Build Build_Linux_arm64v8 3.1-alpine3.11` which shows up in GH PRs. The shortened name helps reduce the amount of clipping especially in the Azure DevOps pipeline UI.
> Refactor build job names to remove containing stage name

- src/Microsoft.DotNet.ImageBuilder/src/AcrClient.cs
- src/Microsoft.DotNet.ImageBuilder/src/AcrClientFactory.cs
- src/Microsoft.DotNet.ImageBuilder/src/ExecuteHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
- src/Microsoft.DotNet.ImageBuilder/src/RetryHelper.cs
When running the `cleanAcrImages` command, it can result in there being too many requests to the ACR REST endpoint, resulting in HTTP status 429 errors.  This occurs because there are so many requests occurring in parallel.  To mitigate this, I've added retry logic to attempt retries if this error is encountered.  I've refactored things to make use of the Polly library since it is well-suited for retry logic.
> Add retry logic for ACR cleanup

- src/Microsoft.DotNet.ImageBuilder/src/Commands/IngestKustoImageInfoCommand.cs
These changes are in support of https://github.com/dotnet/docker-tools/issues/474 to allow commands executed in the publish stage to be done so with the `dry-run` option and not require authenticated connections.
The issue is that `KustoClient` currently will attempt to connect to a Kusto service even if the `dry-run` option is set, although it doesn't end up executing any write operations.  But since we're not able to provide any credentials in this scenario, the connection attempt to the Kusto service will never work.  
To fix this, the call to ingest from the CSV is completely skipped in the `dry-run` scenario to avoid any Kusto connection attempt.
> Don't connect to Kusto on dry runs

- eng/common/templates/jobs/build-images.yml
- eng/common/templates/jobs/publish.yml
- eng/common/templates/stages/build-test-publish-repo.yml
- eng/common/templates/steps/init-docker-linux.yml
- eng/common/templates/steps/init-docker-windows.yml
- eng/common/templates/steps/publish-readmes.yml
- eng/common/templates/variables/common.yml
Updates the pipeline workflow to execute the Post_Build and Publish stages as part of PR builds.  This provides more coverage of the pipeline when validating PRs and should help to expose issues that have otherwise gotten through to internal builds.  
Fixes #474
> Run publish stage in PR builds

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/ManifestToolService.cs
When executing a build with the `dry-run` option, the `publishManifest` command will fail with an `ArgumentNullException` when it attempts to inspect the image to get its digest value. Since it's a dry run, the output of the `manifest inspect` command returns null and the code tries to deserialize that as JSON.  This issue only occurs if the build is publishing manifest tags.
Fixed this to check for a dry run and not attempt to deserialize the value.
> Fix publishManifestCommand to handle dry run

- eng/common/templates/jobs/publish.yml
- eng/common/templates/variables/common.yml
Now that PR builds run the publish stage in the build pipeline, the `publicSourceBranch` variable needs to be set correctly in order to target the correct image info file.  The `Build.SourceBranchName` variable is always set to `merge` for PR builds so that's not useful.  For PRs, the `System.PullRequest.TargetBranch` variable should be used.  In addition, even if the PR is targeting the nightly branch, builds for samples should still use master as the public source branch.
Fixes #496
> Fix publicSourceBranch variable for PR builds

- eng/check-base-image-subscriptions.json
Renames the image info files for the microsoft/dotnet-framework-docker repo so that the 'M' in Microsoft is lowercase. There are currently issues with the internal mirrored repo using capital M but the GitHub repo using lowercase. Getting this resolved to have consistent casing between the two.
> Updates the repo name for the .NET Fx subscription

- src/Microsoft.DotNet.ImageBuilder/src/McrTagsMetadataGenerator.cs
- src/Microsoft.DotNet.ImageBuilder/tests/McrTagsMetadataGeneratorTests.cs
If a platform defined in the manifest doesn't have any documented tags, it results in a "Sequence contains no elements" exception when attempting to call `McrTagsMetadataGenerator`.  This happens because the logic calls the Enumerable.Aggregate method which throws if the sequence is empty.  Fixed the code to use `String.Join` instead which results in an empty string return value if the array is empty.
> Fix tags metadata generator to handle undocumented platform

- eng/common/templates/jobs/validate-image-sizes.yml
The image size validation tests require the Windows build agent to be the latest Windows version so that it can pull down all supported versions of Windows images.
> Update image size validation to use latest Windows version agent

- eng/common/templates/jobs/build-images.yml
- eng/common/templates/jobs/post-build.yml
- eng/common/templates/jobs/publish.yml
A retry of a job that has already published the image info artifact will result in a failure because an artifact with the same name already exists.  Pipeline artifacts cannot be overwritten or deleted.  So the only option is to use a unique name to prevent a conflict.  This is done by appending the `System.JobAttempt` variable to the artifact name.  In the post-build stage, we collect all the image info artifacts and combine them into one image info file.  There needs to be a way to ignore the image info artifacts that were published by failed jobs.  This is done by a script which deletes all the artifacts from those failed jobs.
Fixes #519
> Add uniqueness to artifact names to fix retry attempts

- eng/common/templates/jobs/build-images.yml
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
The [dotnet-buildtools-preqreqs-docker](https://github.com/dotnet/dotnet-buildtools-prereqs-docker) repo now builds both a Nano Server and Windows Server Core image in the same [pipeline](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/master/eng/pipelines/dotnet-buildtools-prereqs-eng.yml).  There's an issue with this because the build leg that's supposed to build the Windows Server Core image ends up not being anything.  This is caused by the parameters used to invoke the Image Builder `build` command.  It's passed an `os-version` parameter that, in this case, is set to `nanoserver-1809` instead of `windowsservercore-ltsc2019`.  The reason for this is due to the need to treat those two OS versions as equivalent in that they require the same build agent version.  However, …
> Remove osVersion parameter when building

- src/Microsoft.DotNet.ImageBuilder/src/Commands/CleanAcrImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CleanAcrImagesOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/ValidateImageSizeOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/EnumHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/CleanAcrImagesCommandTest.cs
In order to better allow for more ad-hoc deletion of images in ACR, these changes update the `cleanAcrImages` command to specify what and how the deletions should be made by using the command parameters instead of having repo-specific logic embedded in the command.
Related to #504
> Update ACR cleanup to be driven from cmd options

- eng/pipelines/dotnet-docker-tools-eng-validation.yml
Reference the new filename of the image info file (see https://github.com/dotnet/versions/pull/610).
> Ref the new image info variant for docker-tools test builds

- src/Microsoft.DotNet.ImageBuilder/src/AcrClient.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CleanAcrImagesCommand.cs
Fixes an issue where querying for ACR repo manifests would sometimes result in a `SocketException`.  It's not exactly clear why this happens but it's definitely related to the amount of records that are being requested as defined by the URL.  This is done in order to page through the results.  The max value, 999, was being used which has been problematic.  I've moved this down to 500 and consistently seen good results.  I've also added some code to the retry logic to handle the case where a `SocketException` gets thrown.  My testing found that retries would work if a SocketException was ever thrown.
> Fix ACR querying issue

- eng/common/templates/variables/docker-images.yml
- eng/pipelines/cleanup-acr-images-custom.yml
- eng/pipelines/cleanup-acr-images.yml
- eng/pipelines/templates/steps/clean-acr-images.yml
Updates the pipelines that cleanup ACR images to consume the updated command API from https://github.com/dotnet/docker-tools/pull/541.  This requires defining which images are to be cleaned up through the command parameters instead of defined within the command logic itself.  In order to provide a means to cleanup images in an ad hoc fashion (such as Image Builder images, #504), an additional pipeline is added for executing custom cleanup operations where the parameters can be defined at queue time.
Fixes #504
> Update Clean ACR image pipelines

- eng/common/Invoke-ImageBuilder.ps1
- eng/common/templates/steps/init-docker-linux.yml
- eng/common/templates/steps/init-docker-windows.yml
- eng/common/templates/variables/docker-images.yml
Updates the infra to reference the new multi-arch tag of Image Builder instead of platform-specific tags.
> Use Image Builder multi-arch tag

- eng/common/templates/jobs/build-images.yml
The changes in https://github.com/dotnet/docker-tools/pull/557 break internal build legs on a Windows agent.  I thought I had tested my changes on that, but I targeted the wrong branch when queueing the build.
The issue is that there is a difference between Linux and Windows in how handles variables that are defined in code.  So this [change](https://github.com/dotnet/docker-tools/pull/557/files#diff-db2f1628b602c431239729498ca85ec6) ends up producing a `"` at the end of the actual value of the variable.  This causes the rest of the arguments after it to get cut off and not used by the command which breaks things
This behavior occurs when using `script` on a Windows agent and can be fixed by not including the ending `"` character or by using PowerShell.  Both those solutions require a …
> Fix image info arg for build

- eng/common/templates/stages/build-test-publish-repo.yml
These changes allow the pipeline to make use of ARM-based Linux machines that are directly running as build agents.  This is a change compared to how things worked in the past when AzDO didn't have support for the agent software to run on an aarch64 machine.  It was necessary to use a AMD64 proxy machine that sent Docker commands remotely to the aarch64 machine.  But now the agent software is capable of running on this architecture (https://github.com/microsoft/azure-pipelines-agent/issues/1911).
This implementation is using a staged approach to only have this hardware configuration done within the Dotnet-Docker-Public agent pool.
These changes won't be merged until the hardware has been updated appropriately.
Related to https://github.com/dotnet/docker-tools/issues/486
> Support ARM-based Linux build agents

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateBuildMatrixCommandTests.cs
I made a mistake with #566.  We need to include all osVersions in the build matrix generated variable so that the `-slim` variables do not get filtered out even though they are included in the `path` variables.
> Include all osVersions in build matrix common Variables

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Manifest/Manifest.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestInfo.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/ModelExtensions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Helpers/ManifestHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/ManifestInfoTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/McrTagsMetadataGeneratorTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Microsoft.DotNet.ImageBuilder.Tests.csproj
This PR adds an `import' concept to the manifest.  This allows the manifest.json to be split across multiple files.  This is being added to support the [Dockerfile templates feature](https://github.com/dotnet/dotnet-docker/issues/1933).
The initial implementation only supports variables.  This is a scoping decision based on what is currently required.  There is nothing that prevents future expansion to support other model types.
> Add 'import' concept to manifests

- src/Microsoft.DotNet.ImageBuilder/src/Commands/WaitForMcrDocIngestionCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/WaitForMcrImageIngestionCommand.cs
We don't want to attempt to make calls to the MCR service if the `dry-run` option is enabled when calling the `waitForMcrDocIngestion` and `waitForMcrImageIngestion` commands.
> Support for dry-run option for MCR wait commands

- eng/common/templates/jobs/publish.yml
- eng/common/templates/jobs/wait-for-ingestion.yml
- eng/common/templates/steps/download-build-artifact.yml
- eng/common/templates/steps/publish-readmes.yml
- eng/common/templates/steps/wait-for-mcr-doc-ingestion.yml
- eng/common/templates/steps/wait-for-mcr-image-ingestion.yml
- eng/common/templates/variables/docker-images.yml
Updates the publish stage of the pipeline to wait for MCR image and doc ingestion after they've been published.  This is an opt-in model that will be enabled by setting the `waitForIngestionEnabled` variable to `true`.  Also included is a job template that can be used by each repo to wait for ingestion as a standalone pipeline.
Related to #547
> Wait for MCR image/doc ingestion in pipeline

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateDockerfilesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateDockerfilesOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
- src/Microsoft.DotNet.ImageBuilder/src/Models/Manifest/Platform.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/ModelExtensions.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateDockerfilesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Helpers/DockerfileHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Helpers/ManifestHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/ModelExtensionsTests.cs
Related to dotnet/dotnet-docker#1933
This command will generated the Dockerfiles from a template specified in the manifest.  The template technology used is http://r3c.github.io/cottle/.  There is a set of predefined symbols that can be substituted as well as any manifest variables.  The command also supports a validation mode which can be used by unit tests to ensure all Dockerfiles are in-sync with the templates.
> Add generateDockerfiles command

- eng/pipelines/dotnet-docker-tools-eng-validation-pr.yml
- eng/pipelines/templates/variables/eng-validation.yml
Define separate pipeline YAML file for eng validation: an internal one to trigger from commits and a public one to trigger from PRs.  There's not a way to define a single file with conditional logic around the `trigger` and `pr` keywords because AzDO doesn't support that.
Fixes #549
> Split off PR-specific eng validation pipeline

- eng/common/templates/jobs/wait-for-ingestion.yml
- eng/common/templates/steps/wait-for-mcr-doc-ingestion.yml
- eng/common/templates/steps/wait-for-mcr-image-ingestion.yml
- eng/common/templates/variables/common.yml
- src/Microsoft.DotNet.ImageBuilder/src/Commands/WaitForMcrDocIngestionOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/WaitForMcrImageIngestionCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/WaitForMcrImageIngestionOptions.cs
* Logic to calculate image info directory name doesn't work if there's only one file matching the search pattern. This is because the result is a single value, not an array, and it's being dereferenced as an array.  Fixed to wrap it in an array (this works even if the returned value is an array; it doesn't create a nested array).
* Set the `timeout` option for the MCR image and doc ingestion commands so that pipelines can customize that value.
* Update the ingestion commands to allow empty timeout values to be passed for the options, which will cause the command to just use the default value.
* Fixed the summary output to list the image tags correctly.
> Fix various issues with waiting for MCR ingestion

- eng/common/templates/steps/wait-for-mcr-image-ingestion.yml
The `manifestVariables` variable needs to be passed to the `waitForMcrImageIngestion` since it's a manifest command.  This is needed in order to pass custom state.  An example that requires this is the build for Image Builder that needs to set the `UniqueId` state: https://github.com/dotnet/docker-tools/blob/92ef21737f934add62745a505a3d795e88313325/eng/pipelines/templates/variables/image-builder.yml#L8
> Pass manifest variables to waitForMcrImageIngestion cmd

- src/Microsoft.DotNet.ImageBuilder/src/Commands/ShowImageStatsCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/McrTagsMetadataGenerator.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Manifest/Tag.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Manifest/TagDocumentationType.cs
- src/Microsoft.DotNet.ImageBuilder/tests/McrTagsMetadataGeneratorTests.cs
If a platform defined in the manifest has no documented tags of its own but is defined within an image that has shared tags, tag generation will fail here: https://github.com/dotnet/docker-tools/blob/92ef21737f934add62745a505a3d795e88313325/src/Microsoft.DotNet.ImageBuilder/src/McrTagsMetadataGenerator.cs#L62
This happens because the `ImageDocumentationInfo` objects that were generated include the platform that has no documented platform tags and it never gets removed from the set because there isn't a readme template that references one of its tags.
This is fixed by only generating an `ImageDocumentationInfo` object if a platform has any documented _platform_ tags.
> Handle undocumented platform tag generation

- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyAcrImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/HttpPolicyBuilder.cs
- src/Microsoft.DotNet.ImageBuilder/tests/CopyAcrImagesCommandTests.cs
Fixes #563
While not ideal, I decided to keep things simple with `HttpPolicyBuilder`.  It is currently implemented to only handle `HttpResponseMessage` results.  In the case of the call to `ImportImageAsync`, there is no return object.  The Polly API is implemented in a way that there is not a reasonable common base type between `AsyncPolicy` and `AsyncPolicy<T>` that could be used in order to have shared logic between a policy that has a `HttpResponseMessage` return type and one that does not.  For that reason, I decided to just explicitly return null in the delegate that calls `ImportImageAsync` and have the policy gracefully handle nulls.
> Add retry logic to copyAcrImages cmd

- eng/common/Invoke-ImageBuilder.ps1
This is needed for dotnet/dotnet-docker#1933 so that a unit test can be created to ensure the Dockerfiles and templates are in sync.
> Set exit code within Invoke-ImageBuilder script

- src/Microsoft.DotNet.ImageBuilder/run-tests.ps1
This is a follow up change to https://github.com/dotnet/docker-tools/pull/590.  Those changes broke the official build.  The reason this was passing before is because this script declared no parameters and no parameter validation was performed.  The build as always passing parameters to the script but they were silently ignored.
> Add missing run-tests parameters

- eng/common/templates/jobs/generate-matrix.yml
- eng/common/templates/stages/build-test-publish-repo.yml
When calling the `generateBuildMatrix` command, we need to be able to pass in an arbitrary number of custom-build-leg-group args now that the arg has changed to an option list from https://github.com/dotnet/docker-tools/pull/594.
> Support arbitrary number of custom-build-leg-group args

- src/Microsoft.DotNet.ImageBuilder/src/Commands/ManifestOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestFilter.cs
I encountered this limitation in a local dev scenario where I wanted to run a command on a subset of the repos and discovered it wasn't supported.
> Add support for multiple repo filters

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/IngestKustoImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/ImageInfoHelperTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishManifestCommandTests.cs
In order to be able to implement the build caching logic documented in #186, there needs to be a way to look up the digest of the base image for each of the published images.  Currently this is tracked in the image info file but only for base images that are external (those which we do not build); we don't track the digests of base images that have been built internally from our own Dockerfiles.  These changes add logic to be able to track these digests.
It's not as simple as getting the digest after having pushed the images because the images are pushed to a staging location and so the digest would be based off of that registry/repo name.  Instead, we need to manually construct what the eventual registry/repo name is and append it to the SHA value to get the digest value that we actually …
> Store digests of internal FROM images in image info

- src/Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
The changes from https://github.com/dotnet/docker-tools/pull/600 cause an issue when running dry-runs in the publish stage of PR builds.  The `ingestKustoImageInfo` command will encounter a NRE when attempting to extract the SHA from a digest value of the generated image info.  The digest value will be null in such a dry-run build because no image was pushed.  Fixed the code to gracefully handle a null digest value.
> Handle null digest value

- src/Microsoft.DotNet.ImageBuilder/src/Commands/WaitForMcrImageIngestionCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/WaitForMcrImageIngestionCommandTests.cs
Due to the changes from https://github.com/dotnet/docker-tools/pull/600, the logic in the `waitForMcrImageIngestion` command is constructing web request URLs that contain a fully-qualified digest value to get the status of the image ingestion when it should be just using the digest's SHA value.
> Fix MCR ingestion wait logic to parse digest correctly

- src/Microsoft.DotNet.ImageBuilder/src/Commands/WaitForMcrImageIngestionCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/McrStatus/StageStatus.cs
Fixing up a couple issues that were identified with the logic to wait for MCR ingestion:
* StageStatus enum should include an Unknown value since that is a valid case.
* When reporting on the details of failed status, the image statuses being enumerated weren't correctly filtered.  They should be filtered in the same way as they are when waiting for the result.
> Fix up issues in wait for MCR ingestion logic

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/PlatformData.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
Fixes two issues that were identified in how `BuildCommand` handles tags that are marked as `IsLocal`:
* Local tags were being pushed to the staging location but not actually being made public.  This was due to an issue in the `PushImages` method that was enumerating built tags but not filtering out those marked as local: https://github.com/dotnet/docker-tools/blob/8c270da5124f32ce1a407f977817e31c7bba113e/src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs#L386
* Another issue was that an exception would be thrown when trying to find the digest of a tag that is marked as local: https://github.com/dotnet/docker-tools/blob/8c270da5124f32ce1a407f977817e31c7bba113e/src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs#L120
This occurred because when constructing the lookup …
> Fix IsLocal tag issues in BuildCommand

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerService.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerServiceCache.cs
- src/Microsoft.DotNet.ImageBuilder/src/GitHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/IDockerService.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/ManifestToolService.cs
- src/Microsoft.DotNet.ImageBuilder/src/ManifestToolServiceExtensions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/PlatformData.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishManifestCommandTests.cs
Adds caching logic to Image Builder's `build` command.  This helps to avoid building and publishing images that have not changed since they were last published.  The criteria for determining whether an image has changed is the following:
* The image it's based on has a current digest value that differs from the base image digest value from the previous publish.
* The Dockerfile's commit SHA is different than what it was when the image was previously published.
The published image info files contain the state that is used here for getting the information on the previous publishing of the image.  That file is passed as input for the `build` command.
In order to simplify testing logic, the image info output of a build job will contain data for images that were pulled from the cache.  They …
> Build caching logic for Build command

- src/Microsoft.DotNet.ImageBuilder/src/DockerServiceCache.cs
Excludes null values from the caches maintained by `DockerServiceCache`.  This is important for a scenario like image digests where a locally built image will not have a digest value yet.  So an attempt to gets its digest would result in a null value being stored in the cache.  After pushing the image and attempting to retrieve the digest again, it would return the null value from the cache.
> Don't cache null values

- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/PlatformData.cs
We don't want the image info files published to the dotnet/versions repo to include a bunch of `"isCached": false` lines because they will all have that value.
> Prevent default value of IsCached property from being serialized

- eng/common/templates/jobs/build-images.yml
- eng/common/templates/variables/docker-images.yml
Fixes an issue from https://github.com/dotnet/docker-tools/pull/618 because it didn't override the `testResultsDirectory` variable causing the tests to be unable to copy test results for the pipeline.
Related to #186
> Override testResultsDirectory in case of multiple repos

- src/Microsoft.DotNet.ImageBuilder/Dockerfile.windows
- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
Fixes a couple issues introduced from https://github.com/dotnet/docker-tools/pull/620.
Now that the manifest tool is called in Windows scenarios as well, the manifest tool needs to be contained in the Windows version of the Image Builder image.
And since the manifest tool is also being called for images that exist in the staging location, there needs to be an authenticated connection for those scenarios.  To fix that, I've updated `BuildCommand` to be logged into the Docker registry for more of its work.
> Fix manifest tool issues

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateImageGraphCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateImageGraphOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
- src/Microsoft.DotNet.ImageBuilder/src/Models/Docker/Descriptor.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Docker/Manifest.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Docker/Platform.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Docker/SchemaV2Manifest.cs
This command generates a DOT (graph description language) file illustrating the image and layer hierarchy.  This command is not intended for any production scenarios it is intended for local desktop usages to generate visualizations of the images within a manifest.
> Add GenerateImageGraph command

- src/Microsoft.DotNet.ImageBuilder/src/Commands/ShowImageStatsCommand.cs
This was introduced by https://github.com/dotnet/docker-tools/pull/584 when the documentation metadata was changed from a Boolean property to an enum.
> Fix bug in showImageStats related to counting undocumented tags

- src/Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/ManifestToolService.cs
- src/Microsoft.DotNet.ImageBuilder/src/ManifestToolServiceExtensions.cs
Fixes an issue with parsing the digests returned from the `docker inspect` command.  A locally built image will have an empty array returned for its `RepoDigests` field.  When trimming the array characters, it's left with an empty string.  Calling `Split` on an empty string produces an array with a single empty string rather than an empty array.  Fixed the code to return an empty enumerable in that case.
The namespaces were reordered according to Visual Studio's sorting.  Without fixing the sorting, it couldn't automatically place new namespaces in the correct order.
> Fix digest parsing

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerService.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerServiceCache.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageDigestCache.cs
- src/Microsoft.DotNet.ImageBuilder/src/LockHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/ManifestToolServiceExtensions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
This is basically just a repeat of https://github.com/dotnet/docker-tools/pull/617 that had gotten broken again by further changes.  I've captured this logic in a single class to help avoid this happening again.
> Don't cache null image digests

- eng/common/templates/jobs/publish.yml
The changes in https://github.com/dotnet/docker-tools/pull/629 caused there to be a change in the order of parameters for the copyAcrImages command that needs to be fixed in the pipeline.
> Fix order of copyAcrImages params

- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyAcrImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/IngestKustoImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/TrimCachedPlatformsCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/TrimCachedPlatformsOptions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishManifestCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/TrimCachedPlatformsCommandTests.cs
The `copyAcrImages` command ends up publishing images that were retrieved from the cache which is unnecessary.  The problem is that the image info file that this command consumes has not had the cached platforms trimmed from it yet.  This gets done by the `publishManifest` command.  Rather than have the `copyAcrImages` ignore the cached platforms, I've instead added a new command that will trim out any cached platforms from the image info file.  This should be called before `copyAcrImages`.
In addition, the `ingestKustoImageInfo` command will result in an error if it is called in the scenario where no images have been built.
> Trim cached platforms

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
Fixes #639 
This is needed in order to unblock https://github.com/dotnet/dotnet-docker/pull/2226.
> Disable image-info validation during build initialization

- .editorconfig
The goal of adding this is to get more consistency in the code style used.  This editor config is a copy of what is used in the dotnet/runtime repo.  Right now there are 479 problems reported.  I propose we work on bringing these down by proactively addressing the problems within the files we touch.
> Add .editorconfig to the repo

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/ImageData.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishManifestCommandTests.cs
Fixes the `publishManifest` command to use the image info content for determining which manifests to publish.  Previously it was using the filtered manifest data.  But that is not representative of what needs to be published not that we have image caching functionality.
> Base manifest publishing on image info content

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixOptions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateBuildMatrixCommandTests.cs
Updates the `generateBuildMatrix` command to exclude any leg from the matrix that consists only of images that came from the cache.  An image info file would need to be passed to the command to provide this information.
Related to #632
> Support test job trimming from cached images

- eng/common/templates/jobs/build-images.yml
Migrating the changes from https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/370.
> Set buildRepoName variable to allow other build tasks to consume it

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
Related to https://github.com/dotnet/dotnet-docker/issues/2122
Fixes the issue described in this comment: https://github.com/dotnet/dotnet-docker/pull/2260#discussion_r492816689.
This is fixed by tracking info about the images that have been retrieved from the cache.  Regardless of whether an image has an entry in the image info file, it will get a cache hit if it shares the same Dockerfile path as an image that has been retrieved from the cache and tagged appropriately.
Note that this does not handle the scenario where there's a shared Dockerfile and neither of the platforms result in cache hits.  In that scenario, the first platform will end up having its image built as part of the normal cache miss processing.  The second platform will also get a cache miss even though technically its …
> Build support for shared Dockerfiles

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/ImageInfoHelperTests.cs
An issue was introduced by https://github.com/dotnet/docker-tools/pull/655 that caused the build to break when processing a manifest image that contained multiple platforms.  The new code that had been added made use of the `PlatformData.PlatformInfo` property which actually isn't being set correctly as part of the loading of an image info file.  It resulted in a null reference when trying to access that property in order to generate the cache key.  There had just not been any code path which exposed this null value before.
I've fixed the issue with the image info loading so that PlatformInfo is now set correctly across all platforms within an image.  I've also changed the caching code because it actually never even needed to make use of the `PlatformData.PlatformInfo` property at all, so …
> Fix caching info caused by multi-platform scenario

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/ImageInfoHelperTests.cs
There was an issue with the changes from #655 in the logic which attempts to rewrite the image name of a digest to be based on a different repo.  This logic targeted the repo from the tag which is actually the overriden (staging) registry and repo location, rather than the MCR location.  This causes the incorrect image name to be stored in the image info file which messes things up.
I've fixed this by using the raw registry and repo names of the target repo in order to build up the correct image name.
> Fix issue with digest renaming in caching logic

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateDockerfilesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateDockerfilesOptions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateDockerfilesCommandTests.cs
For the changes being made for #2182, there needs to be a way to generate Dockerfiles from a template that makes use of the `ARCH_TAG_SUFFIX` variable which is always populated.  Currently, it defaults to an empty value if the architecture is AMD64.
This is fixed by including an option to set the default architecture that, if set, will be excluded as a tag suffix.  For 2.1/3.1 Dockerfile templates, this will be set to "AMD64".  For 5.0, this option will not be set.
Related to https://github.com/dotnet/dotnet-docker/issues/2182
> Dockerfile generation support for amd64 tag suffix

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/McrTagsMetadataGenerator.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/PlatformData.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
- src/Microsoft.DotNet.ImageBuilder/tests/ImageInfoHelperTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/MergeImageInfoFilesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishImageInfoCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishManifestCommandTests.cs
With the changes being done for dotnet/dotnet-docker#2182, it will cause a platform to be defined multiple times in a manifest, contained in separate images. This requires changes to `PublishManfiestCommand` in order to correctly handle this scenario because it will otherwise throw an exception when it encounters a platform with no concrete platform tags.
This is solved by finding the matching platform that does contain a concrete tag and using that as the reference tag for the manifest creation.
> Manifest publishing support for duplicated platforms

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateBuildMatrixCommandTests.cs
The `platformVersionedOs` matrix generation doesn't generate the correct matrix when a platform has been duplicated in the matrix.  It ends up generating one leg for each of those platforms, each having the same name.  What it should do is to combine things into one leg.
These changes refactor the matrix generating logic to reuse similar logic that exists for combining distinct platforms that share a Dockerfile into a single leg and repurposes it to be used for this scenario as well.
> Fix matrix generation for duplicated platforms

- eng/common/templates/jobs/generate-matrix.yml
- eng/common/templates/jobs/publish.yml
- eng/common/templates/steps/validate-branch.yml
- eng/common/templates/variables/common.yml
Adds a validation step that would get executed in all stages of the build.  This validates that the build is running on an official branch if it's an official build.  Official branches are defined in a common variable that each pipeline can override if necessary.
I also added a variable that would allow this validation to be overriden.  This variable is intended as an escape hatch for now and would need to be explicitly added to a build run.
Fixes #605
> Disallow official builds from non-official branches

- src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/ImageInfoHelperTests.cs
The changes to add shared tags for each Linux distro end up exposing an issue in the image info merging logic.  The issue occurs when the image info file in the versions repo has an image without any manifest data (no shared tags) and the image info to be merged in does define manifest data for that same image.  It results in an [exception](https://github.com/dotnet/docker-tools/blob/5745c5c78a481ae76f3993b889114505989b595d/src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs#L87) because the logic doesn't account for the scenario of merging a property value where the source and target have differing "nullness".
I've fixed the logic to handle this case as well as the reverse case where the image's manifest had been removed.
> Fix image info merging of new or removed image manifest

- src/Microsoft.DotNet.ImageBuilder/src/Commands/ImageSizeCommand.cs
The changes being made for dotnet/dotnet-docker#2182 require defining platforms in the manifest that do not contain any simple tags.  This breaks the `ImageSizeCommand` class because it's always expecting at least one tag in a platform.  I've fixed the logic to ignore such platforms.
> Fix image size validation to handle tagless platforms

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
The changes in https://github.com/dotnet/docker-tools/pull/672 had an issue that caused the logic to not work in PR builds.  In PR builds, the image info is output but images are not pushed.  This messes up the logic which intends to find a matching platform that has its digest set because since the image wasn't pushed, it doesn't have its digest set.
Fixed the logic to not base its lookup on the state of the digest/created fields but rather whether it has tags which would imply that the state is set correctly.
> Fix image info generation

- eng/common/templates/jobs/generate-matrix.yml
- eng/common/templates/stages/build-test-publish-repo.yml
When generating the matrix for the test stages, this passes the image info file produced by the build stage to the `generateBuildMatrix` command.  That command is already configured to filter out test legs for those legs consisting only of unchanged images.
Fixes #632
> Trims test jobs consisting of only unchanged images

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateReadmesCommand.cs
These containers get left on the machine after running the GeneratedReadmesCommand.
> Delete the renderingtool containers in the GeneratedReadmesCommand

- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyAcrImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateImageGraphCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/IngestKustoImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/WaitForMcrImageIngestionCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/McrTagsMetadataGenerator.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/ImageData.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Manifest/Tag.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/TagInfo.cs
- src/Microsoft.DotNet.ImageBuilder/tests/CopyAcrImagesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateBuildMatrixCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/ImageInfoHelperTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/IngestKustoImageInfoCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishManifestCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/WaitForMcrImageIngestionCommandTests.cs
Updates the manifest schema to allow each tag to be syndicated to an additional repository.  That means the tag will be published both to the repository in which it's contained as well as the repository that it's configured to be syndicated to.  This supports dotnet/dotnet-docker#2317 by allowing, for example, the `2.1` tag to be published to both the `dotnet/core/runtime` and `dotnet/runtime` repositories.
This syndicated repository only applies to the publish logic.  Images are not tagged with these syndicated repositories at build time.  Specifically, it impacts the following commands:
* `copyAcrImages`
* `ingestKustoImageInfo`
* `publishManifest`
* `waitForMcrImageIngestion`
> Support tag syndication

- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyAcrImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/IngestKustoImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/WaitForMcrImageIngestionCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Manifest/Tag.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Manifest/TagSyndication.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/TagInfo.cs
- src/Microsoft.DotNet.ImageBuilder/tests/CopyAcrImagesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/IngestKustoImageInfoCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishManifestCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/WaitForMcrImageIngestionCommandTests.cs
In order to syndicate the 2.1 and 3.1 images to the original "core" repos, we must handle the case of the `latest` tag (see https://github.com/dotnet/dotnet-docker/pull/2340#pullrequestreview-517090038).  In the new repos, 5.0 should be latest but in the original "core" repos, 3.1 should be latest.  That means we can't simply syndicate the `latest` tag with the same name.  To handle this, I've updated the manifest model to include a `destinationTags` concept for syndication that allows custom tag names to be defined for the syndicated destination.  For example, this allows the `dotnet/runtime:3.1` tag to be syndicated as both `dotnet/core/runtime:3.1` and `dotnet/core/runtime:latest` with a definition like the following:
```
"3.1": {
"syndication": {
"repo": "$(syndicatedRuntimeRepo)", …
```
> Support custom destination tag names for syndication

- src/Microsoft.DotNet.ImageBuilder/src/Commands/WaitForMcrImageIngestionCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/WaitForMcrImageIngestionCommandTests.cs
I'm not sure what I was thinking for the logic to wait for MCR ingestion in https://github.com/dotnet/docker-tools/pull/682.  It attempts to query the image digest of a syndicated tag in order to get the SHA it needs to query MCR for.  It's completely unnecessary (and incorrect because of publishing latency) to query for it because the digest is already known.  The digest will be the same as the digest of the corresponding manifest tag pushed to the primary repo.  For example, the digest for the `dotnet/runtime:3.1` tag will be the same as the digest for the `dotnet/core/runtime:3.1` tag.  Since the digest for the `dotnet/runtime:3.1` tag is known from the image info file, there's no need to query for it.
> Fix MCR ingestion wait logic for syndicated tags

- eng/common/templates/jobs/validate-image-sizes.yml
Now that Windows Server, version 2009 images have been published, the image size validation pipeline needs to be updated to use the latest version of Windows in order to pull those 2009 images.
> Fix Windows build leg for image size validation

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishMcrDocsCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
- src/Microsoft.DotNet.ImageBuilder/src/ReadmeHelper.cs
The logic to generate the `Full Tag Listing` section in the readme aggressively replaces all content between `# Full Tag Listing` and the next header.  Because of that it's not possible to include additional content to the `Full Tag Listing` section.  It will just be overridden by the replacement logic.  I've fixed this by only replacing the `# Full Tag Listing` header and any following whitespace.
> Update readme generation of full tags section

- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyAcrImagesCommand.cs
In cases where a dynamically named tag is defined in the manifest, such as with the use of `$(System:TimeStamp)`, there's likely to be discrepancies in the tag names between the manifest and the tag names defined in the image info file that was generated during the build.  The logic in `CopyAcrImagesCommand` doesn't handle this and explicitly expects there to be a matching tag name.  When it can't find one, an exception occurs.
I've updated the logic to gracefully handle this scenario by simply ignoring the fact that it couldn't find a match and not attempt to process the syndication data.  I think it's fine to say that, for now, syndication won't be supported for such dynamically named tags.  I do think this could eventually be supported with the [manifest …
> Handle non-matching tag names between manifest and image info file

- eng/common/templates/variables/common-paths.yml
This variable should not be defined in the comment set of variables because the path is specific to each consuming repo.
> Remove common testResultsDirectory variable

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishImageInfoCommandTests.cs
The changes made in https://github.com/dotnet/docker-tools/pull/698 aren't going to work.  While the same changes will be made to each repo, the way in which the changes are made will result in different commit SHAs.  This will then break the code-mirror pipeline that runs when attempting to mirror the changes from GitHub to AzDO.  The changes need to have identical commit SHAs in order for the code mirroring to execute successfully.
I'm temporarily disabling this functionality until a new implementation can be made.
> Temporarily disable publishing image info to AzDO repo

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishManifestCommandTests.cs
Manifest publishing doesn't correctly handle the new changes related to https://github.com/dotnet/dotnet-docker/pull/2405.  It ends up producing a manifest like the following in order to syndicate images to the old "core" repos.:
```
image: dotnetdocker.azurecr.io/public/dotnet/core-nightly/aspnet:3.1.10
tags: [3.1,latest]
manifests:
- image: dotnetdocker.azurecr.io/public/dotnet/core-nightly/aspnet:3.1.10-buster-slim
platform:
architecture: amd64
os: linux
- image: dotnetdocker.azurecr.io/public/dotnet/core-nightly/aspnet:3.1.10-buster-slim-arm32v7
platform:
architecture: arm
os: linux
variant: v7
- image: dotnetdocker.azurecr.io/public/dotnet/core-nightly/aspnet:3.1.10-buster-slim-arm64v8
platform:
architecture: arm64
os: linux
variant: v8
- image: …
```
> Fix manifest publish for syndicated tags

- eng/common/templates/jobs/publish.yml
I had originally created the `BotAccount-dotnet-docker-dnceng-code-rw` secret but I then I realized that PAT was associated with my domain account when it should be a bot.  Eng Services has an existing bot domain account that can be used for these purposes and has a PAT for it at `dn-bot-devdiv-dnceng-rw-code-pat`.
> Update PAT used for accessing dotnet-versions repo

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyAcrImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/TrimUnchangedPlatformsCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/PlatformData.cs
- src/Microsoft.DotNet.ImageBuilder/tests/CopyAcrImagesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/ImageInfoHelperTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/MergeImageInfoFilesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishImageInfoCommandTests.cs
Publishing of images that share runtime-deps between different product versions is currently broken.  As an example, for the sharing of 3.1 and 5.0 runtime-deps for Focal, it results in the 3.1 images being published but not the 5.0 images.  This happens because the comparison logic of the `PlatformData` class doesn't take into account the product version of the image that it's contained within.  This leads to two different platforms (3.1 vs 5.0) as being considered equal when they are not.  Because of that `CopyAcrImagesCommand` ends up publishing runtime-deps 3.1 tags twice rather than the 3.1 tags followed by the 5.0 tags.
This has been broken since the release of 5.0.  It wasn't known at that time because of a specific scenario where this issue doesn't occur.  For the 5.0 release, the …
> Fix runtime-deps sharing

- src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/PlatformData.cs
- src/Microsoft.DotNet.ImageBuilder/tests/ImageInfoHelperTests.cs
`ImageInfoHelper` was incorrectly setting the `ImageInfo` state on `ImageData` objects in cases of duplicated platforms (where a platform is defined multiple times but in different images).
> Fix platform comparison to handle duplicated platforms

- eng/common/templates/stages/build-test-publish-repo.yml
- eng/pipelines/check-base-image-updates.yml
For check-base-image-updates.yml, I decided to replace 1903 with 2019 LTSC instead of 20H2 because 2019 LTSC will be around a lot longer and not require updating for a long time.  It doesn't matter what version the agent pool is anymore because we no longer pull images, only use the manifest tool.
> Remove pipeline support for Windows Server 1903

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GitOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/FileHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/GitHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/GitService.cs
- src/Microsoft.DotNet.ImageBuilder/src/IGitHubBranchRef.cs
- src/Microsoft.DotNet.ImageBuilder/src/IGitHubFileRef.cs
- src/Microsoft.DotNet.ImageBuilder/src/IGitHubRepoRef.cs
- src/Microsoft.DotNet.ImageBuilder/src/IGitService.cs
- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
- src/Microsoft.DotNet.ImageBuilder/src/Models/Subscription/GitFile.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishImageInfoCommandTests.cs
Due to the issue identified by https://github.com/dotnet/docker-tools/pull/705, `PublishImageInfoCommand` has been rewritten to correctly handle pushing the same commit to two git repositories (GitHub and AzDO).  To do this, it was necessary to remove the usage of the `Microsoft.DotNet.VersionTools` library for pushing changes because that is only capable of working with GitHub.  This has been replaced with an implementation that uses `LibGit2Sharp` which clones the GitHub repo, makes the necessary changes, and pushes that single commit to both the GitHub and AzDO repositories.  This ensures the same commit SHA exists between the two repositories, allowing code mirroring to not be interfered with.
Fixes #642
> Publish image info to AzDO dotnet-versions repo

- eng/file-pusher/Dockerfile
- eng/file-pusher/file-pusher.csproj
- src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
- src/Microsoft.DotNet.ImageBuilder/Dockerfile.windows
- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
- src/Microsoft.DotNet.ImageBuilder/tests/Microsoft.DotNet.ImageBuilder.Tests.csproj
Image Builder tests currently fail because the infra is configured to install .NET 5.0 on the machine running the tests: https://github.com/dotnet/docker-tools/blob/fb70fa59252fa72773f248afce37d4fbb4d7cb8a/eng/common/Install-DotNetSdk.ps1#L40
But the projects are still targeting .NET Core 3.1, so this ends up with a test failure because the required runtime framework version is not available.  
Fixes #691
> Upgrade ImageBuilder to .NET 5

- src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
- src/Microsoft.DotNet.ImageBuilder/Dockerfile.windows
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoCommand.cs
The `publishImageInfo` command does not work when executing Image Builder in a container.  It runs into the same problem described by https://github.com/dotnet/dotnet-docker/pull/2111.  To resolve this, the alpine rid needs to be used when publishing.
Also fixed an issue in the command itself which prevented the error being surfaced because an exception was happening in a `finally` block.
> Fix image info publishing

- eng/common/Install-DotNetSdk.ps1
Explicitly setting the TLS version to handle running this on machines that have a minimum TLS version configured.  See https://github.com/microsoft/dotnet-framework-docker/pull/488
> Set TLS version when downloading .NET install script

- src/Microsoft.DotNet.ImageBuilder/src/ImageBuilder.cs
This fixes the issue of the help info not being output when running Image Builder.  The problem was the configuration of `System.CommandLine.Builder.CommandLineBuilder`.  The builder is used in order to setup some middleware.  But when using a builder, you're starting from scratch and need to build up all functionality that the CLI should use, including the help.  This is easily accomplished by calling the `UseDefaults` extension method which is what is implicitly used when a CommandLineBuilder is not explicitly created.  This sets up all the functionality that we'd want, including other functionality like tab suggestion support.
Fixes #731
> Fix help output for Image Builder

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
Related to #719
The original fix in https://github.com/dotnet/docker-tools/pull/729 does not work properly in our production builds.  The image digest from the image info was used to retrieve layers.  In production builds the image digest is set to the destination repo - e.g. MCR.  The local image digests are in terms of the staging repos.  To correct this, a tag must be used to retrieve the layer info.
> Refactor image-info logic to retrieve layers

- eng/common/Install-DotNetSdk.ps1
The SDK install script is failing on the Windows build agents. It fails with the error: `The variable '$LASTEXITCODE' cannot be retrieved because it has not been set.`.  This happens because the script has `Set-StrictMode` and apparently the built-in `LASTEXITCODE` variable isn't set.
It's not completely clear why this started happening.  It works on some build machines but fails on others. I did find that updating the build agent to latest causes the script to start failing on the same machine that it was previously working on.  So it seems related to the build agent version which could have a different version of PowerShell associated with it.
After further [reading up](https://devblogs.microsoft.com/scripting/powershell-error-handling-and-why-you-should-care/) on the `LASTEXITCODE` …
> Fix sdk install script

- src/Microsoft.DotNet.ImageBuilder/src/Commands/CleanAcrImagesOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyImagesOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateDockerfilesOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateImageGraphOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetBaseImageStatusOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/ImageSizeOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/IngestKustoImageInfoOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishMcrDocsOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/ShowImageStatsOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/WaitForMcrDocIngestionOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/WaitForMcrImageIngestionOptions.cs
All the options classes that compose sub-options need to have setters defined for those properties.  Without the setter, the binding logic is unable to set them and the properties are left to their default values instead of the ones provided via command line.
> Sub-options need setters

- eng/pipelines/check-base-image-updates.yml
- eng/pipelines/cleanup-acr-images.yml
- eng/pipelines/dotnet-buildtools-image-builder-official.yml
- eng/pipelines/dotnet-buildtools-image-builder-pr.yml
- eng/pipelines/dotnet-docker-tools-eng-validation-pr.yml
- eng/pipelines/dotnet-docker-tools-eng-validation.yml
- eng/pipelines/push-common-updates.yml
This is the first stage in renaming `master` branch to `main`.  This is just adding `main` to the list of branches but doesn't remove `master` yet.
Related to https://github.com/dotnet/docker-tools/issues/742
> Add 'main' branch to list of pipeline triggers

- eng/common/templates/variables/common.yml
This variable is used by all repos which now have a mix of both `master` and `main` branches.  So the list of official branches should now include both of them until all the repos have transitioned.
Related to https://github.com/dotnet/docker-tools/issues/742.
> Add main branch to list of official branches

- eng/common/Get-ImageBuilder.ps1
Ports the change from https://github.com/dotnet/dotnet-docker/pull/2580 to docker-tools.
> Fix script to pull Image Builder

- src/Microsoft.DotNet.ImageBuilder/src/Commands/CliHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyBaseImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyBaseImagesOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/DockerRegistryCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/DockerRegistryOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/RegistryCredentialsOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageBuilder.cs
- src/Microsoft.DotNet.ImageBuilder/src/StringExtensions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/CopyBaseImagesCommandTests.cs
* Renames `CopyDockerHubBaseImagesCommand` to `CopyBaseImagesCommand`.
* Provides source credentials options on a per-registry basis that the command will pass along to the ACR Import operation.
* Dynamically determines source registry from the image tag.
Related to #613
> Provide source credentials for copying base images

- eng/common/templates/jobs/build-images.yml
The changes from https://github.com/dotnet/docker-tools/pull/758 weren't working properly on Windows because of the parsing of the `registry-creds` argument.  I've fixed this so that it works on both Windows and Linux.
> Fix call to build command to work on both Windows and Linux

- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyAcrImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyBaseImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyBaseImagesOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/ManifestCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/SubscriptionOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageBuilder.cs
- src/Microsoft.DotNet.ImageBuilder/src/SubscriptionHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/CopyBaseImagesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GetStaleImagesCommandTests.cs
Updates the `copyBaseImages` command to optionally consume a subscriptions file instead of a local manifest.  This is needed in the scenario where this command will be run as part of checking for any base image updates, which occurs from the dotnet/docker-tools repo. In that case, the subscription is used to determine all the manifests from all the product repos that are participating in the base image check logic and copies those base images to the mirroring location.  
Related to #613
> Copy base images using subscriptions

- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyBaseImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/CopyBaseImagesCommandTests.cs
The mirror logic has the potential for running into repo collisions because the logic strips out the registry name.  While this wouldn't happen today since all of the images we'd be mirroring are coming from Docker Hub, it could happen if we also mirrored from another external registry.
For example, let's say we have two Dockerfiles like this:
Dockerfile 1:
```Dockerfile
FROM amd64/alpine:3.13
```
Dockerfile 2:
```Dockerfile
FROM other-registry.com/amd64/alpine:3.13
```
Mirroring these base images would cause a collision.  They'd both end up being mirrored to `dotnetdocker.azurecr.io/mirror/amd64/alpine:3.13`, for example.
To handle this, I've updated the code to not strip out the registry.  Using the example above, the tags would be mirrored to the following:
* …
> Use registry name as part of repo name for mirrored tags

- eng/common/templates/variables/docker-images.yml
- eng/pipelines/check-base-image-updates.yml
- eng/pipelines/templates/steps/copy-base-images.yml
Updates the pipeline which rebuilds any out-of-date images when a base image changes to include an additional step to copy all external base images to a mirror location.  This is just one of the phases in implementing the full solution for #613.  The intent is to just have this additional step executed but for the rest of the pipeline to continue as usual and not to actually consume the mirrored images.  Once we've determined that the mirror logic is working properly within the pipeline, then we can proceed with consuming it.
Related to #613
> Copy base images as part of stale image check

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/EnumerableExtensions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Helpers/ReturnsExtensions.cs
This updates the `build` command so that it can handle pulling base images from a specified mirror location instead of directly from an externally-owned registry like Docker Hub.
This defines an additional option, `source-repo-prefix`, to the `build` command. When that option is set, it pulls any external base images by constructing a tag that represents the mirror location.
For example, consider the following scenario:
* Dockerfile has `FROM amd64/alpine:3.13`
* `source-repo-prefix` is set to `mirror/`
* `registry-override` is set to `dotnetdocker.azurecr.io`
When pulling base images the `build` command will pull from `dotnetdocker.azurecr.io/mirror/amd64/alpine:3.13` instead of from `amd64/alpine:3.13`.  It then tags the pulled image as `amd64/alpine:3.13` so that the Dockerfile can be …
> Support pulling from mirror location during build

- eng/pipelines/cleanup-acr-images.yml
Updates the ACR cleanup pipeline to include images contained in the `mirror` repository.  This will clean-up all untagged images in that repository.
Related to #613
> Prune dangling mirrored images

- eng/pipelines/cleanup-acr-images.yml
The pipeline to clean out unneeded images in ACR has a job to target sample images.  But it is configured to only target samples in the `dotnet/core/samples` and `dotnet/framework/samples` repos.  It doesn't take into account the the `dotnet/samples` repo that was added a while back.  I've fixed the repo string to account for this.
> Clean images in dotnet/samples repo

- eng/common/templates/jobs/publish.yml
A failure occurs running the Component Detection step in PR builds with the error:
```
Microsoft.TeamFoundation.Core.WebApi.ProjectDoesNotExistException: VS800075: The project with id 'vstfs:///Classification/TeamProject/9ee6d478-d288-47f7-aacc-f6e6d082ae6d' does not exist, or you do not have permission to access it.
```
The reason for this is unclear but is related to it being based on a GitHub repo rather than AzDO.  So it works correctly in AzDO builds.  It also doesn't happen when the task is auto-injected into a build.  We explicitly disable the auto-injection across the board in order to avoid have it appear in our all jobs redundantly.
The mitigation to this is to avoid executing the task in public builds.
Related to https://github.com/dotnet/core-eng/issues/12353.
> Only execute component detection on internal builds

- eng/pipelines/cleanup-acr-images.yml
Ensures that the pipeline will always run on schedule rather than the default behavior which is to skip a scheduled run if there hasn't been a commit since the last run.
> Set image cleanup pipeline to always run on schedule

- eng/tests/pipeline-validation/1.0/focal/amd64/Dockerfile
The `dotnet-docker-tools-eng-validation` pipeline is failing now that builds are pulling from the ACR mirror location because the test Dockerfile is referencing a tag that is not mirrored and the build itself doesn't mirror the referenced tag because it's a dry run.  
To fix this, I've updated the Dockerfile to reference a tag that does get mirrored instead.
> Update test Dockerfiles to use mirrored tags

- eng/common/templates/jobs/cg-detection.yml
- eng/common/templates/jobs/publish.yml
- eng/common/templates/steps/test-images-linux-client.yml
- eng/common/templates/variables/common.yml
- eng/pipelines/cg-detection.yml
The CG component detection task that gets [executed in the publish job](https://github.com/dotnet/docker-tools/blob/main/eng/common/templates/jobs/publish.yml#L105-L106) isn't actually doing what we think it's doing.  It was thought that this could just scan the source code and detect components.  But it actually requires the source to be built, at least it does to detect NuGet packages that are referenced from projects.  So it's not actually reporting any NuGet package references from our repos.
Another problem is that we build all of our jobs within a container.  And the component detection task is run on the agent where it scans the agent's source directory.  Since the project is built in a container, it's outside the context of the agent's file system and the component detection will …
> Common component governance detection job

- eng/common/templates/stages/build-test-publish-repo.yml
Builds in the dotnet-buildtools-prereqs-docker repo are silently failing when calling the copyBaseImages command because the `UniqueId` variable being used in the manifest doesn't have a value provided for it.
The setting of this variable is embedded in the common `manifestVariables` variable which is passed to other manifest-based commands but it isn't being passed to the copyBaseImages command.
I've fixed the pipeline so that this `manifestVariables` variable does get passed, allowing the `UniqueId` variable in the manifest to be resolved to a value.
> Pass manifest variables to copyBaseImages command

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyBaseImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/CopyBaseImagesCommandTests.cs
The [dotnet-buildtools-prereqs-docker](https://github.com/dotnet/dotnet-buildtools-prereqs-docker) repo uncovered two issues with how tags are mirrored from the DH registry to ACR:
* If a `FROM` instruction references the base tag as `alpine:3.13` instead of `<arch>/alpine:3.13`, for example, it results in an error during the call to ACR's import because there isn't actually a repository name `alpine` in `docker.io`.  That's just a shortcut for referencing the actual repository name of `library/alpine`.  This is fixed by checking whether the registry being targeted is DH and doesn't have a multi-segment repository name. If so, then `library/` should be prepended.
* In some cases, a `FROM` instruction references a non-DH external registry, such as `registry.fedoraproject.org`. The logic to …
> Fix tag mirroring for non-standard tag variations

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/StringExtensions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Helpers/ManifestHelper.cs
There's an issue with the base image digest values that get stored in the image info files.  The repo portion of the string includes the repo prefix that was defined for the build.  See https://github.com/dotnet/versions/blob/fe78c22877055de295c38b9b3d606bf1ba04af69/build-info/docker/image-info.dotnet-dotnet-docker-nightly.json#L17
This specifically occurs for the base image digests that represent internally built images, not for external images.  So this doesn't impact the behavior of the automated builds from base image updates.
This issue was introduced by the changes in https://github.com/dotnet/docker-tools/pull/765.  When a base image digest gets translated from the internal ACR value to the public MCR value, there's code which strips off the ACR name and replaces it with the MCR …
> Omit repo prefix from base image digest

- eng/common/templates/jobs/validate-image-sizes.yml
- eng/common/templates/stages/build-test-publish-repo.yml
We now have public scale set agent pools available for Windows build agents.  For Windows scenarios, these replace the static `DotNetCore-Docker-Public` pool.  Because each Windows version has its own agent pool, there's no longer a need for a `demand` to restrict the type of agent that is used (the demand is still used for the internal pool).
Once this configuration has been tested out, we'll continue to roll it out to the internal builds as well.
Related to #532
> Reference public scale set agent pools

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishMcrDocsCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishMcrDocsOptions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishMcrDocsCommandTests.cs
In order to complete the work for dotnet/dotnet-docker#2361, we need to be able to exclude the publishing of the product family readme in the nightly branch. This adds an option to the `publishMcrDocs` command that allows the product family readme to be excluded.
> Option to exclude publishing of product family readme

- eng/common/templates/jobs/validate-image-sizes.yml
- eng/common/templates/stages/build-test-publish-repo.yml
- eng/pipelines/check-base-image-updates.yml
Rolls out the changes to use scale set agent pools for internal builds in the common infra.
Related to dotnet/docker-tools#532
> Use scale set agent pools for internal builds

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateDockerfilesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateDockerfilesCommandTests.cs
Updates Image Builder to handle a new distro: [CBL-Mariner](https://github.com/microsoft/CBL-Mariner).
The changes that were made:
* `PlatformInfo.GetOSDisplayName` updated to provide a display name for this distro.
* Refactored `PlatformInfo.GetOSDisplayName` to have a generic algorithm for pulling out the version name from the distro name.
* Updated regex in `GenerateDockerfilesCommand` for parsing the OS version number so that it can support OS names that contain a `-` character.
Related to https://github.com/dotnet/dotnet-docker/issues/2837
> Support for CBL-Mariner

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateBuildMatrixCommandTests.cs
When attempting to implement a dependency between a 6.0 Dockerfile and a 5.0 Dockerfile within the same Docker repository (in order to satisfy https://github.com/dotnet/dotnet-docker/pull/2841#discussion_r641771618), I discovered an issue in the matrix generation. It generates an incorrect matrix for the platformVersionedOs matrix type.
In the specific example, the runtime-deps Dockerfile for 6.0 is based on the runtime-deps image for 5.0 via its `FROM` instruction.  The matrix generation will produce a matrix that groups 5.0 and 6.0 together.  This is incorrect for this matrix type because 5.0 and 6.0 should be tested in separate build jobs.
The reason they are grouped together is because it simply sees that the 6.0 Dockerfile has a dependency on a 5.0 image.  But for this matrix type, …
> Fix matrix generation for intra-repo dependency

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateBuildMatrixCommandTests.cs
This reverts commit 394953c9b2ae150076ec916ca5b6515db0bf0fcd.
I'm reverting this because there's an issue in the logic.  It ends up splitting sdk into a separate job from the other image variants because the product versions are different (the version number is a 3-part version so 5.0.6 would end up differing from 5.0.300, for example) when they should actually be seen as belong to the same product version.  Besides, there are no plans for using intra-repo dependencies anymore.
> Revert "Fix matrix generation for intra-repo dependency (#795)"

- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PlatformInfoTests.cs
For Windows Server 2022, Nano Server won't have a SAC version.  It'll just be Nano Server 2022.  These changes update the display name for Nano Server to support this rather than only the SAC version pattern.  The logic is now shared with Windows Server Core.
> Update display name for Nano Server

- eng/pipelines/cleanup-acr-images.yml
This is a stop-gap solution for #797.  It disables the cleanup of mirrored images because some of them may be the result of importing a multi-arch tag which causes the underlying image to be untagged and subject to deletion.  For now, we'll disable this cleanup until a workable solution can be implemented.
> Disable cleanup of mirrored images

- src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
- src/Microsoft.DotNet.ImageBuilder/Dockerfile.windows
- src/Microsoft.DotNet.ImageBuilder/manifest.json
This produces an image of Image Builder for each version of Windows.  Doing this allows us to target `servercore:ltsc2016` instead of `nanoserver:sac2016` and still target Nano Server for the other versions.
Fixes #721
> Add Windows version-specific images of Image Builder

- src/Microsoft.DotNet.ImageBuilder/NuGet.config
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GitOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/NotificationLabels.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishMcrDocsOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/QueueBuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/QueueBuildOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/EnumerableExtensions.cs
- src/Microsoft.DotNet.ImageBuilder/src/INotificationServices.cs
- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
- src/Microsoft.DotNet.ImageBuilder/src/NotificationService.cs
- src/Microsoft.DotNet.ImageBuilder/src/Services/IBuildHttpClient.cs
- src/Microsoft.DotNet.ImageBuilder/src/Services/VssConnectionFactory.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GetStaleImagesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/QueueBuildCommandTests.cs
This implements a basic notification service within Image Builder that allows notifications to be posted as issues in a GitHub repo.  The use of the service will be expanded in the future but for now I've configured it so that a notification will be sent whenever AutoBuilder queues a build.
Related to https://github.com/dotnet/docker-tools/issues/394
> Add build notifications for AutoBuilder

- eng/common/templates/steps/publish-readmes.yml
The microsoft/mcrdocs repo is renaming master to main. The default branch value set in Image Builder is set to master.  I'm updating the pipeline to explicitly set these options rather than use the default.
> Set target branch to main for mcrdocs repo

- src/Microsoft.DotNet.ImageBuilder/src/Commands/IngestKustoImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Services/IKustoClient.cs
- src/Microsoft.DotNet.ImageBuilder/src/Services/KustoClientWrapper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/IngestKustoImageInfoCommandTests.cs
An [earlier change](https://github.com/dotnet/docker-tools/pull/804) for retrying Kusto ingestion doesn't work properly because of the use of a Stream object. When the throttling exception occurs, another attempt is made to run the ingestion but the KustoClient returns the result immediately with a status of Skipped because the stream that's passed in has already been read from and is positioned at the end of the stream.  Because the status is Skipped and not Succeeded, an exception is later thrown.
I've fixed this by moving the creation of the stream right up to the point where it's needed to pass it to the ingestion method.  The retry behavior wraps this, allowing for a new stream object to be created with each retry attempt.
I also fixed an error in the logic for handling a timeout. …
> Fix retry behavior for Kusto ingestion

- src/Microsoft.DotNet.ImageBuilder/src/Commands/AzdoTags.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/QueueBuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/PipelineHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/QueueBuildCommandTests.cs
This adds logic to ensure we don't have builds being automatically queued continuously over and over even when they are failing.  For now, a simple test is used to check whether the last 3 builds queued by Auto Builder have failed. If so, it won't queue a build and will fail the scheduled build instead, as well as logging a notification. The only way to get back into a good state is to resolve whatever the issue is and have a human manually queue a build to produce a successful build.
Fixes #715
> Stop queuing builds if there are recent failures

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishMcrDocsOptions.cs
Removing the hardcoded default git options for the publishMcrDocs command. It's better to not have these defined in code and instead explicitly set by the pipeline (already done by https://github.com/dotnet/docker-tools/pull/811).
> Remove custom default options for publishMcrDocs cmd

- src/Microsoft.DotNet.ImageBuilder/src/Models/Subscription/Subscription.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Subscription/SubscriptionManifest.cs
- src/Microsoft.DotNet.ImageBuilder/src/SubscriptionHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GetStaleImagesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/QueueBuildCommandTests.cs
In order to add docker-tools to the subscription file to allow Image Builder to be checked for rebuilds, we need the ability to load its manifest file. The manifest file requires a value for the `UniqueId` variable in order to be loaded. The `getStaleImages` command doesn't provide a value for that variable when it loads the manifest, causing the load to fail.
To fix this, I've updated the subscription schema to support the ability to define manifest variables which will be passed along to the manifest loading logic.  This will allow the docker-tools manifest to be loaded.
For the purposes of the `getStaleImages` command, it's only necessary to have _some_ value defined for `UniqueId`; it doesn't actually matter what that value is because the tags which consume the variable are not …
> Support manifest variables when loading manifests from subscription

- eng/check-base-image-subscriptions.json
- eng/common/templates/variables/docker-images.yml
Adds a subscription to ensure that the Image Builder image is monitored for base image updates.
Fixes #807
> Add docker-tools to check-base-image-subscriptions

- eng/common/templates/jobs/generate-matrix.yml
- eng/common/templates/jobs/publish.yml
- eng/common/templates/steps/init-common.yml
- eng/common/templates/steps/init-docker-linux.yml
- eng/common/templates/steps/init-docker-windows.yml
- eng/common/templates/steps/publish-readmes.yml
- eng/common/templates/steps/set-image-info-path-var.yml
- eng/common/templates/steps/validate-branch.yml
Several parts of the pipeline infra rely on the source branch name that determines which action to take.  A false assumption is made with the value of the `Build.SourceBranchName` variable, however.  It is assumed that the full branch name would be included but it only takes the last segment of the branch name.  For example, a branch name of `dev/mthalman/branch` will have a value of `branch` for the `Build.SourceBranchName` variable.  This is not what we want.
To workaround this, I've change the usage of  `Build.SourceBranchName` to `Build.SourceBranch` instead.  This value is fully-qualified, such as `refs/head/dev/mthalman/branch`.  A common build task was defined to parse that value down to `dev/mthalman/branch`.
Fixes #828
> Fix usage of source branch name

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishManifestCommandTests.cs
The new tags for WS 2022 are not configured to be syndicated to the old "core" repositories. This exposes a bug in Image Builder when publishing the manifest tags that are being syndicated. The logic attempts to find the syndicated tag for each of the platforms that are within the manifest tag. Because the WS 2022 tags aren't being syndicated, this fails to find any match wrt to the syndicated repo value.  Because the `First` LINQ method is used, it causes an exception because no match is found.
I've updated the logic to use `FirstOrDefault` and to compensate for a null value to be returned.
> Fix manifest publishing for syndicated tags

- src/Microsoft.DotNet.ImageBuilder/manifest.json
Related to https://github.com/dotnet/docker-tools/issues/798
> Include WS 2022 version of Image Builder

- src/Microsoft.DotNet.ImageBuilder/src/Commands/QueueBuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Services/IBuildHttpClient.cs
- src/Microsoft.DotNet.ImageBuilder/src/Services/VssConnectionFactory.cs
The samples build for the dotnet-docker repo has been failing after the introduction of Windows Server 2022.  It had failed 3 consecutive times which mean the next time AutoBuilder attempted to queue a build, it should have not done so because the failure limit had been reached.  Instead, it continued to queue a build.
The cause of this is because the builds which had been queued were not tagged as intended.  Because the failed builds had not been tagged with `autobuilder`, the logic which queried for builds was not including them.  The assumption was that we could tag a build at the time it is queued but that is not the case.  A separate call must be made to tag a build _after_ it has been queued.  I've updated the logic to do this.
> Fix tagging of AutoBuilder builds

- src/Microsoft.DotNet.ImageBuilder/src/Commands/ManifestFilterOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/ManifestOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/ImageInfo.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestFilter.cs
This adds support for filtering the manifest by product version since the only way currently to filter by product version is with the `--path` option.  The problem with the `--path` option being the only way is that it hampers the ability to provide common scripts that can be used across any repo's folder structure.
Related to https://github.com/dotnet/docker-tools/issues/836
> Support product version for manifest filter

- src/Microsoft.DotNet.ImageBuilder/src/Commands/QueueBuildCommand.cs
In the case when AutoBuilder disables queuing new builds due to too many recent failures, an error message is provided stating that a build must be queued manually as part of resolving the issue.  However, the error message leaves out some important information. That build must be tagged with `autobuilder` in order to cause AutoBuilder to recognize that a successful build has occurred.
When AutoBuilder queries for recent failures, it is specifically filtering builds to only those tagged with `autobuilder`. So if a user has manually queued a build to fix whatever issue was occurring, AutoBuilder will not see that build in its query unless it was tagged with `autobuilder`. If the build wasn't queued that way, then the next time AutoBuilder attempts to queue a build, it will see that the …
> Clarify error message for queueBuild command

- eng/common/templates/jobs/validate-image-sizes.yml
The image size validation tests are unable to pull WS 2022 images because the tests are being run on the WS 20H2 agent pool.  Updating to use WS 2022 agent pool instead.
> Use WS 2022 pool to run image size tests

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/IngestKustoImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/WaitForMcrImageIngestionCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/DateTimeService.cs
- src/Microsoft.DotNet.ImageBuilder/src/IDateTimeService.cs
- src/Microsoft.DotNet.ImageBuilder/src/JsonHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/ManifestData.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/PlatformData.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GetStaleImagesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Helpers/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/MergeImageInfoFilesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishManifestCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/WaitForMcrImageIngestionCommandTests.cs
As [described in the issue](https://github.com/dotnet/docker-tools/issues/847#issuecomment-912552874), multi-arch tags which are syndicated are not being tracked properly when waiting for MCR ingestion. There is no guarantee that the digest of a multi-arch tag will be the same digest in the syndicated destination because the underlying manifest list can be based on different images.
These changes fix this by explicitly tracking the digest of syndicated multi-arch tags in the image info file.  The logic for waiting for MCR ingestion consumes that data to ensure that both the primary and syndicated digests are successfully ingested.
Fixes #847
> Track syndicated manifest digests

- src/Microsoft.DotNet.ImageBuilder/src/Commands/ManifestOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/ImageInfo.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestFilter.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Helpers/ManifestHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/ImageInfoHelperTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PlatformDataTests.cs
An issue from https://github.com/dotnet/docker-tools/pull/859 causes Image Builder to fail when processing a manifest which has images without a product version set, such as the samples manifest.  Processing such a manifest will cause a null value to be passed to `Regex.IsMatch`, resulting in an exception.
I've fixed this by doing a simple null check and also enabling NRT checks to better catch issues like this.
> Product version filtering fix

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PullImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PullImagesOptions.cs
In order to execute a component governance scan over the supported images, we first need to pull those images to the build agent. The CG tool requires that the images to be scanned exist locally on the machine.
These changes add a command to pull the images which can be executed by the pipeline.
Related to dotnet/dotnet-docker#3001
> Command to pull images

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateArtifactsCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/PlatformData.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/VariableHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/VariableHelperTests.cs
This supports https://github.com/microsoft/dotnet-framework-docker/issues/811 by adding support for nested variables in the manifest. This means the value of a variable can reference another variable.
> Support for nested manifest variables

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Manifest/Platform.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateBuildMatrixCommandTests.cs
Distroless Dockerfiles of CBL-Mariner will need to be executed on a custom agent pool. Currently, there is only one matrix defined for Linux Dockerfiles of a given architecture.  They're all lumped together targeting the same agent pool.  This is problematic because there's not a mechanism to separate out the distroless Dockerfiles to run them in a separate agent pool.  There needs to be a way for the generated build matrices to provide a distinct matrix just for the distroless Dockerfiles.  Once a separate matrix is provided, the pipeline can then explicitly reference that matrix and configure the appropriate agent pool name for that matrix.  
One way to do this is to change the matrix generation to not lump all Linux Dockerfiles together but rather define distinct matrices for each …
> Support for custom build matrix OS versions

- eng/common/build.ps1
Now that Image Builder [supports product version filtering](https://github.com/dotnet/docker-tools/pull/859) natively, this can be utilized from the common build script.
Related to #836
> Support native product version filtering from build script

- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/VariableHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/VariableHelperTests.cs
This fixes an issue introduced by https://github.com/dotnet/docker-tools/pull/873 where variables that are exclusively defined via the options are not exposed by VariableHelper. This specifically causes an issue when generating readmes in the dotnet/dotnet-docker repo. In that repo, a `branch` variable is provided:
https://github.com/dotnet/dotnet-docker/blob/7275e84505032552923953dce76fd478b42f63f9/eng/readme-templates/Get-GeneratedReadmes.ps1#L34
This variable does not get included by VariableHelper and subsequently not used by the GenerateReadmesCommand class. This causes the readme templates which rely on the branch variable to produce incorrect output.
I've fixed the logic to ensure that any variable exclusively defined via the options is included in the results.
> Fix variable resolution logic

- eng/common/templates/jobs/build-images.yml
- eng/common/templates/jobs/test-images-linux-client.yml
- eng/common/templates/jobs/wait-for-ingestion.yml
- eng/common/templates/stages/build-test-publish-repo.yml
- eng/common/templates/steps/cleanup-docker-linux.yml
- eng/common/templates/steps/download-build-artifact.yml
- eng/common/templates/steps/init-common.yml
- eng/common/templates/steps/init-docker-linux.yml
- eng/common/templates/steps/test-images-linux-client.yml
- eng/common/templates/variables/common-paths.yml
In order to support other teams consuming the common infra, this removes the assumption that a test script will exist for the source repo.  If the `testScriptPath` variable is not set, it will skip execution of the PreBuildValidation job and any test steps.
Related to #830
> Skip tests if test script path not set

- eng/common/templates/steps/cleanup-docker-windows.yml
- eng/common/templates/steps/init-docker-windows.yml
- eng/common/templates/steps/test-images-windows-client.yml
The previous changes in #866 did not include changes to support an optional test script for Windows builds.  This causes Windows build jobs for PR builds to fail if a test script doesn't exist. These changes apply the same condition checks to the Windows-related files that were initially made to the Linux-related files.
Related to #830
> Support optional windows tests

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateImageGraphCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetBaseImageStatusCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GetStaleImagesCommandTests.cs
This updates the semantics of `PlatformInfo.FinalStageFromImage` to be nullable. When the value is null, it means the final stage of the Dockerfile has `FROM scratch`. Using the semantics of nullability provides better language support to identify all dependencies that would be affected by having a "FROM scratch" Dockerfile.
Related to #871
> Support for "FROM scratch" Dockerfiles

- eng/common/Install-DotNetSdk.ps1
- eng/src/file-pusher/Dockerfile
- eng/src/file-pusher/file-pusher.csproj
- eng/src/yaml-updater/Dockerfile
- eng/src/yaml-updater/yaml-updater.csproj
- src/Microsoft.DotNet.ImageBuilder/.dockerignore
- src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
- src/Microsoft.DotNet.ImageBuilder/Dockerfile.windows
- src/Microsoft.DotNet.ImageBuilder/manifest.json
- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
- src/Microsoft.DotNet.ImageBuilder/tests/Microsoft.DotNet.ImageBuilder.Tests.csproj
This also applies a [workaround to NuGet restore errors](https://github.com/NuGet/NuGet.Client/pull/4259) that have been showing up in builds.
> Update .NET SDK version to Current/6.0

- src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
This fixes a change that was made in https://github.com/dotnet/docker-tools/pull/895 which set the RID to `linux-musl`. This causes the `publishImageInfo` command to fail because of an [issue with libgit2sharp](https://github.com/dotnet/dotnet-docker/pull/2111) that requires access to native DLLs. These native DLLs are only provided when using a versioned RID.
> Use Alpine RID

- eng/pipelines/check-base-image-updates.yml
- eng/pipelines/templates/steps/get-stale-images.yml
Reverts pipeline changes made in https://github.com/dotnet/docker-tools/pull/824. These changes were never intended to be part of that PR. They were used for testing a scenario but they require dependent changes that don't exist yet in Image Builder.
> Revert pipeline changes

- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
Allows `impish` OS version in manifest to be translated to a display name of `Ubuntu 21.10`.
> Add display name for Ubuntu 21.10

- eng/common/package-scripts/get-installed-packages.sh
- eng/common/package-scripts/get-upgradable-packages.sh
When attempting to run the package scripts against the .NET Monitor image it doesn't work because the entrypoint of that image is the `dotnet-monitor` executable. So passing the script path to it via the `docker run` command isn't going to execute the script. 
I've updated the scripts to override the entrypoint so that the scripts will be executed.
> Handle images with non-default entrypoint

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/ExecuteHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/IProcessService.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/Component.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/PlatformData.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Manifest/PackageQueryInfo.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Manifest/Platform.cs
- src/Microsoft.DotNet.ImageBuilder/src/ProcessService.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
These changes allow the components installed within built images to be tracked within the image info file. The word "component" used here is intended to be general purpose name to refer to any versioned thing that we want to track in the image. For now, only Linux packages will be tracked.
This consumes the scripts added by https://github.com/dotnet/docker-tools/pull/824 in order to get the list of packages and versions that are in the image. By default, it uses the script defined in that PR. But an option is available for a custom script to be used for certain Dockerfiles. This accounts for the distroless scenario where it's not possible to execute the commands within the container that are done for regular containers. Each distroless Dockerfile can be associated with its own custom …
> Track components of built images

- eng/common/build.ps1
Adds quotes around arg values to allow for wildcards to work in Linux.
Fixes https://github.com/dotnet/dotnet-docker/issues/3288
> Fix build script to work on Linux with wildcards

- eng/common/package-scripts/Dockerfile.scripts
- eng/common/package-scripts/get-installed-packages.container.sh
- eng/common/package-scripts/get-installed-packages.sh
- eng/common/package-scripts/get-upgradable-packages.container.bash.sh
- eng/common/package-scripts/get-upgradable-packages.container.sh
- eng/common/package-scripts/get-upgradable-packages.sh
In order to support querying packages of distroless containers, custom package scripts need to be implemented rather than using the common scripts defined here. But in order to allow for reusability of the logic in these common scripts, they need the ability to allow the caller to pass custom arguments for the package manager. As an example, for distroless scenarios for CBL-Mariner, the custom args needed to pass to the dnf package manager would be `--releasever=$version --installroot /staging`. This allows the logic to target a specific install root location for querying the packages.
These changes update the scripts to support custom package manager args.
In addition, support for the dnf package manager was added because the CBL-Mariner distroless scripts also require the use of that …
> Pkg scripts support for custom pkg manager args

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
A regression was introduced by #897 that causes builds to fail when a cache miss occurs on a shared Dockerfile. The first platform that references the Dockerfile is correctly built. When the second platform that references the same Dockerfile is processed, it ends up executing the "cache hit" code path, attempting to tag an image by digest value that doesn't exist locally. This results in an error. For example:
```
-- EXECUTING: docker tag mcr.microsoft.com/dotnet/nightly/runtime-deps@sha256:ecfdfda7ca93e02c4a8e2c54eabe7ee81363019164dac9f8518f3b4eefdf7e45 dotnetdocker.azurecr.io/build-staging/1493853/dotnet/nightly/runtime-deps:5.0-bullseye-slim
Error response from daemon: No such image: mcr.microsoft.com/dotnet/nightly/runtime-deps@sha256:ecfdfda7ca93e02c4a8e2c54eabe7ee81363019164dac9f851 …
```
> Fix image caching regression

- src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/MergeImageInfoFilesCommandTests.cs
The changes from https://github.com/dotnet/docker-tools/pull/897 have an issue when image info files get merged by the `mergeImageInfo` command. If a platform containing a component gets merged with another platform containing the same component, it results in the following error:
```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.ArgumentException: Property set method not found.
at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
at Microsoft.DotNet.ImageBuilder.ImageInfoHelper.MergeData(Object srcObj, Object …
```
> Fix merging of platform data that contains components

- src/Microsoft.DotNet.ImageBuilder/src/Models/Manifest/Manifest.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestInfo.cs
- src/Microsoft.DotNet.ImageBuilder/tests/ManifestInfoTests.cs
This allows a large manifest file to be broken apart so that repos can be defined in separate sub-manifest files.
> Add support to include repos from other manifest files

- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestInfo.cs
- src/Microsoft.DotNet.ImageBuilder/tests/ManifestInfoTests.cs
The changes in https://github.com/dotnet/docker-tools/pull/916 were incomplete because it didn't consolidate repos from separate manifests that shared the same name.
The https://github.com/dotnet/dotnet-buildtools-prereqs-docker repo will end up having multiple sub-manifest files that all define a repo named `dotnet-buildtools/prereqs`. Simply concatenating the repos together into the model isn't sufficient because there is logic throughout Image Builder that assumes that there is only one repo in the model with a given name.
To fix this, I've updated the manifest loading to consolidate all repos that share the same name. It first validates that the repo definitions don't have conflicting state. It then combines all the images from those repos into one repo model.
> Consolidate repos that share a name

- eng/common/package-scripts/get-installed-packages.container.sh
- eng/common/package-scripts/get-installed-packages.sh
- eng/common/package-scripts/get-upgradable-packages.container.bash.sh
- eng/common/package-scripts/get-upgradable-packages.container.sh
- eng/common/package-scripts/get-upgradable-packages.sh
Several updates made to the scripts for getting installed and upgradable Linux packages:
* Add support for yum package manager. Relevant to CentOS which is used in the https://github.com/dotnet/dotnet-buildtools-prereqs-docker repo. The dnf, tdnf, and yum package managers all have the same command syntax used by the scripts so most of the logic has been encapsulated to support all three of these package managers.
* Add support for zypper package manager. Relevant to openSUSE which is used in the https://github.com/dotnet/dotnet-buildtools-prereqs-docker repo.
* Ensure that the container is run as root. This is necessary to override the non-root user that is defined by Helix images in the https://github.com/dotnet/dotnet-buildtools-prereqs-docker repo.
* A couple minor fixes in the …
> Package script updates

- eng/common/templates/stages/build-test-publish-repo.yml
This was originally added to support https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/550.
> Build/test job support for ARM32 v6 variant

- eng/common/templates/jobs/publish.yml
- eng/common/templates/stages/dotnet/build-test-publish-repo.yml
- eng/common/templates/variables/common.yml
- eng/common/templates/variables/docker-images.yml
- eng/common/templates/variables/dotnet/build-test-publish.yml
Updates the publish stage to call the new `postPublishNotification` command from https://github.com/dotnet/docker-tools/pull/838. This reports the results of the significant tasks that comprise the publish stage.
> Enable publish notifications

- src/Microsoft.DotNet.ImageBuilder/src/BlobsClientExtensions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GitOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/IOctokitClientFactory.cs
- src/Microsoft.DotNet.ImageBuilder/src/OctokitClientFactory.cs
- src/Microsoft.DotNet.ImageBuilder/src/TreesClientExtensions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GetStaleImagesCommandTests.cs
After the [enablement to store component data in the image info file](https://github.com/dotnet/dotnet-docker/pull/3319), it's caused the [check-base-image-updates](https://github.com/dotnet/docker-tools/blob/main/eng/pipelines/check-base-image-updates.yml) pipeline to fail with the error:
```
Unhandled exception: Microsoft.DotNet.VersionTools.Automation.GitHubApi.HttpFailureResponseException: Response code does not indicate success: 403 (Forbidden) with content: {"message":"This API returns blobs up to 1 MB in size. The requested blob is too large to fetch via the API, but you can use the Git Data API to request blobs up to 100 MB in size.","errors":[{"resource":"Blob","field":"data","code":"too_large"}],"documentation_url":"https://docs.github.com/rest/reference/repos#get-repository-cont …
```
> Use GitHub blobs API for image info files

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageInfoMergeOptions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/ImageInfoHelperTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishImageInfoCommandTests.cs
I noticed that the image info files contain more values than expected in the `syndicatedDigests` array. This is because each time the image info file from a build is merged into the previously published version in the dotnet/versions repo, it becomes an additive operation for the `syndicatedDigests` array. New syndicated digest values keep getting added into the array but never removed. This is incorrect. It should be replacing the previous values with each publish, just as is done for tags.
There is currently no negative behavior of this other than simply filling up the image info file with content we don't need. This is because nothing actually consumes the `syndicatedDigests` field after the image info file has been published. It's only consumed as part of the locally generated image …
> Fix image info merge to replace syndicated digests

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateArtifactsCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateDockerfilesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateReadmesCommand.cs
Currently, Image Builder only implements the `InsertTemplate` function for readme templates. In order to support https://github.com/dotnet/dotnet-docker/issues/2152, there's a need to also have support for this function in the Dockerfile templates.
These changes refactor the code to move the implementation of the `InsertTemplate` function to the base `GenerateArtifactsCommand` class that both readme and Dockerfile template generation share.
> Support InsertTemplate function in Dockerfile templates

- eng/check-base-image-subscriptions.json
Now that https://github.com/dotnet/docker-tools/pull/929 has been fixed, the nightly subscription can be re-enabled.
This reverts commit 65f8e3eac6884675e56fa211c950e82d109167cd.
> Revert "Temporarily remove nightly subscription (#928)"

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateArtifactsCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateReadmesCommandTests.cs
Updates Image Builder's artifact generation to support passing arguments to templates. This allows for a sub-template to be more reusable. For example, we can define a sub-template for Dockerfiles that just handles installation of PowerShell. That sub-template can then be inserted by the sdk Dockerfile templates. This greatly reduces the duplication of content across Dockerfiles and enforces consistency.
This is implemented by defining two additional optional arguments for the `InsertTemplate` function. The first arg is a map, in Cottle terms, which can be defined using a JSON-like syntax. The map defines the fields and their values which will be made available to the sub-template to consume via the `ARGS` symbol. The second arg is a string that can be used to dynamically indent the …
> Support for template args

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateArtifactsCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateDockerfilesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateReadmesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateDockerfilesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateReadmesCommandTests.cs
There's an issue with how the `InsertTemplate` function behaves when using it from nested templates. The path to the referenced template file must be relative to the root template file, not the referencing template file. This makes the template file referencing dependent on knowing where in the directory structure the root template file is located. Instead, the relative path should be based from the referencing template.
Here's an example to illustrate the issue in concrete terms.
Path: dockerfile-templates/aspnet/3.1/Dockerfile.linux
```
{{InsertTemplate("../my-template-1")}}
```
Path: dockerfile-templates/aspnet/template-foo
```
{{InsertTemplate("../template-bar")}}
```
Path: dockerfile-templates/template-bar
```
Hello World
```
The above templates will end up failing to generate …
> Fix relative path referencing of template files

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateDockerfilesCommand.cs
Currently the `PRODUCT_VERSION` symbol for generated artifacts is set to the value from the manifest model, which is an unresolved value. For example, it will be set to `$(dotnet|3.1|product-version)` instead of `3.1.22`.
To make it more useful to templates, I've set it to the resolved value.
> Set template symbol to resolved value of product version

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateBuildMatrixCommandTests.cs
Fixes #891 
This required updating some test data because it was using Dockerfile graphs that we technically don't support.
> Validate duplicate leg names in build matrix

- eng/common/templates/jobs/build-images.yml
- eng/common/templates/stages/build-test-publish-repo.yml
Builds jobs do not cancel when the build is canceled. This was a regression introduced by https://github.com/dotnet/docker-tools/pull/866.
In that change, `succeeded()` was removed as a condition for the job because that condition interfered with having the PreBuildValidation job be skippable. If `succeeded()` was kept and the PreBuildValidation job was skipped, it would cause the build jobs to be skipped as well. This is why the `in(dependencies.PreBuildValidation.result, 'Succeeded', 'SucceededWithIssues', 'Skipped')` condition was added. However, by removing `succeeded()`, it removed the ability to stop the job when the build is canceled.
To fix this, an explicit condition for checking whether the build is canceled has been added.
> Allow build jobs to be canceled

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestInfo.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateBuildMatrixCommandTests.cs
The changes from https://github.com/dotnet/docker-tools/pull/941 have exposed an issue with generation of the PlatformVersionedOs matrix type.
The scenario involves two repos that don't have a dependency on each other but share the same architecture, product version, and OS version. The current behavior will cause separate matrix legs to be generated, as expected, however the names of the legs are the same because the name is only based on the product version and OS version.
These changes update the leg name generation to also include the first platform's repo name as a differentiator.
> Fix matrix generation to differentiate versions of separate repos

- eng/common/templates/stages/dotnet/build-test-publish-repo.yml
The .NET-specific `build-test-publish-repo.yml` pipeline template was not configured to pass the `testMatrixCustomBuildLegGroupArgs` parameter that the base `build-test-publish-repo.yml` allows for. This is necessary in order to customize the args which are used for the test matrix in .NET scenarios.
> Pass test matrix custom build leg group args in pipeline template

- eng/common/templates/variables/docker-images.yml
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateBuildMatrixCommandTests.cs
The changes in https://github.com/dotnet/docker-tools/pull/947 have caused builds to no longer work on the Image Builder pipeline because the matrix leg name contains a forward slash. This happens when the repo ID resolves to a value that contains a slash. The leg name is subsequently used by the pipeline as part of a file path. The presence of the forward slash implicitly defines a directory name and messes up the logic. Specifically, it's causing the following exception:
```
---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/artifacts/linuxamd64alpine-dotnet-buildtools/image-builder-image-info.json'.
at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
at …
```
> Fix matrix leg name to not include slash

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
This change works around an issue that prevents Dockerfiles with the same architecture but different variant values from being built in the same build job. Specifically, this applies to the changes from https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/550 which has an arm32v6 and arm32v7 Dockerfile that are dependent on each other.
That PR itself didn't expose any issue. It wasn't until https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/564 that the issue manifested. By setting the variant in the manifest to the "correct" value, it caused the two Dockerfiles to be built in separate jobs and fail because the build of the Helix Dockerfile had a dependency on the crossbuild Dockerfile.
This is the only specific case where there is a difference in variant for the …
> Exclude variant value from matrix generation

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateReadmesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetBaseImageStatusCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/ImageSizeCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PullImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/UpdateImageSizeBaselineCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/ValidateImageSizeCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerService.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerServiceCache.cs
- src/Microsoft.DotNet.ImageBuilder/src/IDockerService.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
Due to the changes in https://github.com/dotnet/docker-tools/pull/940, the build for the .NET 6 samples is failing with the following error in the Arm32 legs:
```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.InvalidOperationException: Failed to execute docker build --platform linux/arm/v7 -t dotnetdocker.azurecr.io/build-staging/1573227/dotnet/samples:aspnetapp-buster-slim-arm32v7 -t dotnetdocker.azurecr.io/build-staging/1573227/dotnet/samples:aspnetapp -f dotnet-dotnet-docker/samples/aspnetapp/Dockerfile.debian-arm32 dotnet-dotnet-docker/samples/aspnetapp
failed to get destination image "sha256:d43c51a2603110b8392b050705c55f7f0e777487fcce103ac9dd9f3089af4cf2": image with reference …
```
> Use --platform option for docker pull

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateArtifactsCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateDockerfilesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateReadmesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateDockerfilesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateReadmesCommandTests.cs
An issue exists with how content is generated from artifact templates when the `indent` argument of the `InsertTemplate` function is being used. The indent value doesn't get applied to the next nested template. This prevents the reusability of sub-templates when indentation is involved.
Here's an example:
```
RootTemplate Content
{{InsertTemplate("TemplateA", [], "  ")}}
```
```
TemplateA Content
{{InsertTemplate("TemplateB")}}
```
```
TemplateB Content
```
Generating the content from RootTemplate yields the following output:
```
RootTemplate Content
TemplateA Content
TemplateB Content
```
Since TemplateB was referenced by TemplateA, the indentation of TemplateA should also apply to TemplateB's content in this scope.
The expected output is the following:
```
RootTemplate Content
TemplateA …
```
> Template generation: accumulate indentation for nested templates

- eng/common/templates/stages/dotnet/build-test-publish-repo.yml
This defaults all internal builds that use this template to use the `NetCore1ESPool-Internal` pool for Linux jobs instead of the default public hosted pool, `ubuntu-latest`.
Currently, this has some build performance implications due to provisioning of build agents being slow. This is something that https://github.com/dotnet/core-eng/issues/15391 can hopefully address.
I also fixed the indentation of the Arm pool configuration.
> Switch to use the Arcade pool for internal builds

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateArtifactsCommand.cs
This allows templates to use conditional logic based on whether any indentation is being applied to it. See https://github.com/dotnet/dotnet-docker/pull/3445#discussion_r795756396.
> Expose indentation of template as a symbol

- eng/common/templates/jobs/post-build.yml
- eng/common/templates/stages/build-test-publish-repo.yml
The Post-Build job is using the `defaultLinuxAmd64PoolImage` VM image for its agent pool which ends up being `ubuntu-latest`. For builds that make use of the `build-test-publish-repo.yml` template, the Post-Build job should instead be using whatever pool is passed for the `linuxAmd64Pool` parameter instead. This will ensure it uses the 1ES hosted pool instead.
> Use parameterized pool for post-build job

- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
Image Builder isn't correctly representing the `PlatformInfo.FinalStageFromImage` property in the case of a multi-stage Dockerfile that has `FROM scratch` as the final stage.
Here's an example Dockerfile that demonstrates the issue:
```Dockerfile
FROM mybase
FROM scratch
```
When ImageBuilder loads the model, it will have `PlatformInfo.FinalStageFromImage` set to `"mybase"` when it really should be `null`. This is because the `FROM scratch` stage gets filtered out when calculating the property. I've corrected the logic to handle this scenario.
> Fix for Dockerfiles using "FROM scratch"

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PullImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PullImagesOptions.cs
As described in https://github.com/dotnet/docker-tools/issues/961#issuecomment-1032792234, we'll use the image info file to determine which images are to be scanned for SBOM generation.
In order to do that, we need to pull those images to the build agent first. There is an existing `pullImages` command but this doesn't use an image info file as input. It pulls images strictly based on what's defined in the manifest and whatever filtering is applied.
These changes update the `pullImages` command to optionally accept an image info path as input. It will then use the tags defined in that file as the basis for which tags are to be pulled.
This ensures that we only pull what was actually built rather than everything defined in the manifest.
> Use image info as input to pullImages command

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PullImagesCommand.cs
The changes in https://github.com/dotnet/docker-tools/pull/955 caused a regression in the output variable of the `pullImages` command. It caused the format of the output to include the platform along with the tag.
Expected output:
```
mcr.microsoft.com/dotnet/nightly/runtime-deps:3.1.22-buster-slim,mcr.microsoft.com/dotnet/nightly/runtime-deps:3.1.22-buster-slim-arm32v7
```
Actual Output:
```
(mcr.microsoft.com/dotnet/nightly/runtime-deps:3.1.22-buster-slim, linux/amd64),(mcr.microsoft.com/dotnet/nightly/runtime-deps:3.1.22-buster-slim-arm32v7, linux/arm/v7)
```
This is because the `IEnumerable` being used to generate the output had been changed to `IEnumerable<(string, string)>` when it should be `IEnumerable<string>`.
> Fix format of output variable for pullImages command

- eng/common/templates/jobs/generate-sbom.yml
- eng/common/templates/stages/build-test-publish-repo.yml
- eng/common/templates/variables/docker-images.yml
This adds a pipeline stage which will generate an SBOM from the built images. It runs after the Post-Build stage, in parallel with the Test stage. It has the following workflow:
1. Consumes the image-info.json artifact produced by the Post-Build stage
2. Trims out any unchanged images that were pulled from the cache and not actually built
3. Pulls the images
4. Generate an SBOM from the images
5. Upload the SBOM as a pipeline artifact
Fixes #961
> Include SBOM generation in build

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildOptions.cs
As part of the work to enable ARM64 support of CBL-Mariner for https://github.com/dotnet/dotnet-docker/issues/3455, it was discovered that the image metadata of Mariner's ARM64 images do not contain the variant field (https://github.com/dotnet/dotnet-docker/issues/3520). This causes the platform architecture validation check to fail: 
https://github.com/dotnet/docker-tools/blob/5eb5824b8370a33482c95facd7a5f0525da48e48/src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs#L428-L453
To work around this, I'm adding a build option that allows the validation check to be skipped. As part of the implementation of https://github.com/dotnet/dotnet-docker/issues/3455, this option will be set only for the CBL-Mariner ARM64 build legs.
> Allow platform check in build command to be skipped

- eng/common/Retain-Build.ps1
- eng/common/templates/jobs/generate-matrix.yml
- eng/common/templates/jobs/publish.yml
- eng/common/templates/steps/retain-build.yml
This updates the pipeline template to support [build retention](#973) for official builds. By default, build retention is not enabled. Any pipeline that wants to enable it needs to be set with a `retainBuild` variable set to `true`.
The pipeline can run any stage independently. So a given build may end up executing only one of those stages. But we'd want to be able to retain any build, regardless of which stage it is running. In order to do that the build step used to retain the build is executed across all of the stages to ensure that it will be retained. If multiple stages run in a build, the step which retains the build essentially becomes a no-op after the first stage has run the step.
Fixes #973
> Support build retention in pipeline template

- eng/common/templates/jobs/build-images.yml
This allows pipelines to customize the `imageBuilderBuildArgs` variable that gets passed as an argument to the `build` command of Image Builder.
This is specifically necessary to support https://github.com/dotnet/dotnet-docker/issues/3455, allowing it to inject a `--skip-platform-check` option to the build arguments for Arm64 build legs (see https://github.com/dotnet/docker-tools/pull/974).
> Support customization of imageBuilderBuildArgs

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
This provides an option to the `build` command to output the list of digests of the images that were built. 
This supports the work of #979 by allowing the pipeline to retrieve this list of digests and provide them as input in order to generate an SBOM for each of the images.
> Build option to output digests of images

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoOptions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishImageInfoCommandTests.cs
This updates the `publishImageInfo` command to remove the logic which makes the commit to the AzDO versions repo. This is part of the work to implement #986 which will solely rely on the GitHub versions repo. This means that the need to make the same commit to the AzDO repo is no longer needed.
> Remove extra commit to AzDO versions repo

- eng/common/templates/jobs/build-images.yml
A [recent change to the .NET install location](https://github.com/microsoft/dropvalidator/pull/406) from the ManifestGeneratorTask has broken the builds when an attempt is made to generate the SBOM. It fails to generate a correct path to the `dotnet` executable in order to execute the tool.
This updates the path to conform to the new changes. It also enables the tool to be executed in Arm build legs now that https://github.com/microsoft/dropvalidator/pull/399 has been merged.
> Fix SBOM generation

- src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
When Image Builder publishes image info files, it's accumulating image component data between builds. For example, a recent [build of Alpine images](https://github.com/dotnet/versions/commit/58cb965e90283925ca2d44d8db6fdd429039a686) picked up a new version of busybox. The image info file now shows that there are two versions of busybox contained in an image: 1.33.1-r6 and 1.33.1-r7. This is because of the merge behavior when updating image info files. It preserved the version from a previous build and added the new version to the list. This is incorrect behavior. The list of components should be completely replaced, not merged.
I've updated the logic in Image Builder to handle this correctly.
> Don't merge components between builds

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/DockerRegistryCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerService.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerServiceCache.cs
- src/Microsoft.DotNet.ImageBuilder/src/IDockerService.cs
- src/Microsoft.DotNet.ImageBuilder/src/IManifestToolService.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageDigestCache.cs
- src/Microsoft.DotNet.ImageBuilder/src/LockHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/ManifestToolService.cs
- src/Microsoft.DotNet.ImageBuilder/src/ManifestToolServiceExtensions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GetStaleImagesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Helpers/ReturnsExtensions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/ManifestToolServiceExtensionsTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishManifestCommandTests.cs
This is some preliminary work to enable making API calls to container registries. Doing that requires having an async API within the `ManifestToolService` class. I've made that change which then cascaded to other parts of the codebase which I've updated.
> Use async API in ManifestToolService

- eng/common/templates/jobs/copy-base-images.yml
- eng/common/templates/variables/docker-images.yml
- eng/common/templates/variables/dotnet/build-test-publish.yml
- eng/common/templates/variables/dotnet/common.yml
- eng/pipelines/templates/steps/get-stale-images.yml
This updates the pipeline to be compatible with the latest version of Image Builder containing the changes in https://github.com/dotnet/docker-tools/pull/998. This required passing registry credentials to the `getStaleImages` command.
> Pass required registry creds to ImageBuilder cmds

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateReadmesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishMcrDocsCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
- src/Microsoft.DotNet.ImageBuilder/src/Models/Manifest/Manifest.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Manifest/Readme.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Manifest/Repo.cs
- src/Microsoft.DotNet.ImageBuilder/src/ReadmeHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestInfo.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/ModelExtensions.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/RepoInfo.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateReadmesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Helpers/ManifestHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishMcrDocsCommandTests.cs
We need the ability to generate different sets of readmes depending on the site that will be hosting them. For example, readmes for Docker Hub will be different than the MCR portal.
These changes enable that by extending the manifest model for describing readmes.
This JSON snippet example shows the difference in the model, allowing for multiple readmes to be associated with a repo:
```diff
- "readmeTemplate": "eng/readme-templates/README.md",
- "mcrTagsMetadataTemplate": "eng/mcr-tags-metadata-templates/runtime-deps-tags.yml",
+ "readmes": [
+   {
+     "path": "README.runtime-deps.md",
+     "templatePath": "eng/readme-templates/README.md"
+   },
+   {
+     "path": ".mcr/portal/README.runtime-deps.portal.md",
+     "templatePath": "eng/readme-templates/README.mcr.md"
+   }
+ ],
```
An …
> Support for generating multiple repo readmes

- src/Microsoft.DotNet.ImageBuilder/src/ReadmeHelper.cs
The changes in https://github.com/dotnet/docker-tools/pull/1001 broke the readme publish scenario. In that scenario, it takes the existing readme from the repo and strips out the tag listing to be replaced by marker text that MCR's tooling replaces with its own tag listing. But that changes from https://github.com/dotnet/docker-tools/pull/1001, broke the logic which strips out the tag listing. So it ended up producing a two tag listings.
This is fixed by adding back the comment marker to the readme so that the logic in ImageBuilder can correctly identify the section which needs to be stripped out.
> Fix readme generation to support publish scenario

- src/Microsoft.DotNet.ImageBuilder/src/ReadmeHelper.cs
The changes in https://github.com/dotnet/dotnet-docker/pull/3784 were incorrect because they didn't preserve the `` comment in the generated readme. That causes the publish scenario to not find the marker and end up leaving the original tags listing.
I've fixed this to both preserve the comment and also add validation to check that the marker exists.
> Fix readme generation to preserve end of generated tags marker comment

- eng/common/templates/jobs/publish.yml
- eng/common/templates/jobs/test-images-linux-client.yml
- eng/common/templates/jobs/test-images-windows-client.yml
- eng/common/templates/stages/build-test-publish-repo.yml
- eng/common/templates/stages/dotnet/build-test-publish-repo.yml
- eng/common/templates/steps/set-dry-run.yml
- eng/common/templates/steps/test-images-linux-client.yml
- eng/common/templates/steps/test-images-windows-client.yml
- eng/common/templates/steps/validate-branch.yml
- eng/common/templates/variables/common.yml
- eng/common/templates/variables/dotnet/build-test-publish.yml
Updates the common pipeline infrastructure in order to enable support for internal .NET builds (related to https://github.com/dotnet/dotnet-docker/issues/2152).
This mainly involves adding more customization points within the pipeline such as being able to inject custom initialization logic before running tests. Another small buy key change is to allow the publishing of the image info file to be disabled by the pipeline via a `publishImageInfo` variable.
> Pipeline support for internal .NET builds

- eng/src/file-pusher/file-pusher.csproj
- eng/src/yaml-updater/yaml-updater.csproj
- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
- src/Microsoft.DotNet.ImageBuilder/tests/Microsoft.DotNet.ImageBuilder.Tests.csproj
Updates the projects in this repo to reference the latest versions of their package dependencies. The only one not included in this is [System.CommandLine](https://github.com/dotnet/docker-tools/issues/1019) which has breaking changes that need to be accounted for.
> Upgrade package dependencies

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateBuildMatrixCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Helpers/DockerfileHelper.cs
Builds in the nightly branch of https://github.com/dotnet/dotnet-docker are currently broken due to the Dockerfile in src\runtime-deps\6.0\cbl-mariner2.0-distroless\amd64 being built by multiple jobs (same applies to other architectures). Because it's built by multiple jobs we have two distinct images that are tagged the same way. This leads to issues during publish due to the dependency on the information in the image-info.json file which is expecting a certain digest to exist for an image.
This began to occur after the introduction of https://github.com/dotnet/dotnet-docker/pull/3882. But the issue only manifests when both 6.0 and 7.0 have cache misses for the CBL-Mariner 2.0 Dockerfiles. If you get a cache hit for 6.0 and not for 7.0 things will be fine because we're not producing a …
> Fix matrix generation to prevent duplicate build of Dockerfile

- eng/common/templates/stages/build-test-publish-repo.yml
- eng/common/templates/steps/parse-os-versions.yml
- eng/common/templates/steps/test-images-linux-client.yml
- eng/common/templates/steps/test-images-windows-client.yml
- eng/common/templates/variables/docker-images.yml
- eng/tests/pipeline-validation/run-tests.ps1
- src/Microsoft.DotNet.ImageBuilder/run-tests.ps1
These are changes to support a fix for https://github.com/dotnet/dotnet-docker/issues/3870. The issue there is that we're excluding distroless Mariner images from being tested in jobs where both Mariner and distroless Mariner images were built (e.g. PR builds).
In order to fix this, the intention is to make use of the data we have available in the generated matrix. It includes an `osVersions` field which specifies the set of OS versions represented by the Dockerfile paths it has included to be built/tested in matrix job. In the case of this scenario, that field contains both "cbl-mariner2.0" and "cbl-mariner2.0-distroless", for example. By passing both of these values to the `run-tests.ps1` script, it can correctly include both of those image types to be in its testing.
This is a breaking …
> Support multiple OS versions in tests

- eng/common/templates/jobs/publish.yml
Changes were made in https://github.com/dotnet/docker-tools/pull/1018 to include the correct fully-qualified repo name in the publish notification body. Specifically, it used the value of the `--repo-prefix` option when constructing the repo name. That logic is all correct. The problem is that the `--epo-prefix` option isn't being set when calling the command from the pipeline. This change fixes that.
> Show correct repo name in publish notification

- src/Microsoft.DotNet.ImageBuilder/src/McrStatusClient.cs
The MCR status service is migrating to a different resource/application. Updating the ID to reflect the change. The new ID currently works so this can be rolled out right away.
> Update MCR status resource ID

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesOptions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GetStaleImagesCommandTests.cs
The changes from https://github.com/dotnet/docker-tools/pull/1031 are incomplete when it comes to the scenario of checking for whether an update to the base image exists. When the Dockerfile's base tag is being overridden, we want to compare against the digest of the tag that has the override applied, not the tag that's defined in the Dockerfile.
This requires a change to the `GetStaleBaseImagesCommand` using the same pattern that was used for the other commands in https://github.com/dotnet/docker-tools/pull/1031. It simply applies the override, if applicable, when it needs to look up the digest value that gets compared to the digest from the image info file.
Similarly, `BuildCommand` also needs to be updated so that it outputs the correct base image digest when generating the image info …
> Fixes to better support tag override

- eng/common/templates/jobs/copy-base-images.yml
- eng/common/templates/stages/build-test-publish-repo.yml
- eng/common/templates/stages/dotnet/build-test-publish-repo.yml
- eng/common/templates/steps/copy-base-images.yml
- eng/common/templates/variables/common.yml
This updates the pipeline to allow custom init steps to be injected for the `CopyBaseImages` stage and to provide additional custom args to the `CopyBaseImages` command. This allows consuming repos to provide the custom args introduced by https://github.com/dotnet/docker-tools/pull/1031.
> Support custom init steps for CopyBaseImages stage

- eng/common/templates/jobs/build-images.yml
This fixes the pipeline logic to reference the ImageBuilder args variable in a way that supports it containing special characters like `'` and `$` without resolving them in the context of PowerShell. This is related to https://github.com/dotnet/docker-tools/pull/1031 where the substitution pattern to be used will contain a sub-string like `$1`. Such a value needs to remain unresolved by PowerShell.
> Allow literal special characters in ImageBuilder args

- eng/check-base-image-subscriptions.json
- eng/check-base-image-subscriptions2.json
- eng/pipelines/check-base-image-updates.yml
- eng/pipelines/templates/jobs/check-base-image-updates.yml
The changes in https://github.com/dotnet/dotnet-docker/pull/3971 require a corresponding change in the execution of the `getStaleImages` command. That command needs to have the same `--base-override-regex` and `--base-override-sub` options in order to correctly interpret the image digests that would be written to the image info file by those builds (see https://github.com/dotnet/docker-tools/pull/1034).
However, we can't make that change in all cases of when the `getStaleImages` command is called. We want to evaluate the changes from https://github.com/dotnet/dotnet-docker/pull/3971 in the nightly branch before rolling out to main. Since the `getStaleImages` command applies to all subscriptions defined in https://github.com/dotnet/docker-tools/blob/main/eng/check-base-image-subscriptions.j …
> Split base image subscriptions

- eng/common/templates/stages/build-test-publish-repo.yml
- eng/common/templates/stages/dotnet/build-test-publish-repo.yml
- eng/common/templates/variables/common.yml
- src/Microsoft.DotNet.ImageBuilder/manifest.json
This infrastructure no longer needs to be maintained since Windows Server 20H2 is EOL today and we'll not be running any more builds that are based on it.
> Remove infra related to Windows Server 20H2

- eng/common/templates/jobs/build-images.yml
- eng/common/templates/stages/build-test-publish-repo.yml
- eng/common/templates/steps/copy-base-images.yml
- eng/common/templates/steps/test-images-linux-client.yml
- eng/common/templates/steps/test-images-windows-client.yml
- eng/common/templates/steps/validate-branch.yml
Due to the changes in https://github.com/dotnet/dotnet-docker/pull/3910, we now have the ability to create internal AzDO PRs that target internal builds of .NET. But we need to be able to run a build for that PR to validate the changes.
Currently the pipeline logic is all based around conditions that check for internal vs public, with no distinction of whether the pipeline was triggered by a PR. That's problematic because we don't want to be executing the same pipeline logic for an internal PR as we would for an internal official build. For example, we don't want to be pushing images to the staging location in the ACR for a PR. We'd want the pipeline to mostly be similar to what a PR build would look like in a public GitHub PR. The main difference would be that it has access to internal …
> Add pipeline support for internal PR builds

- eng/common/templates/jobs/build-images.yml
An update to the SBOM manifest tool build task caused a build break. Our script logic is not finding the dotnet directory that was expected to be installed by the tool.
The task for the tool was updated with these changes: https://github.com/microsoft/dropvalidator/pull/523. This caused the task to attempt to use an existing .NET installation on the build agent as long as it was compatible. If not, it install its own. In addition, when it does install its own, the path is different than what our script was expecting.
I've updated the script to compensate for all these conditions. It will first check to see if the tool installed its own version of .NET. If it did, it will target that installation. If not, it will expect that the agent has the compatible version of .NET already installed …
> Fix dotnet path usage with SBOM manifest tool

- eng/common/templates/jobs/build-images.yml
The change to the manifest AzDO task that made the changes in https://github.com/dotnet/docker-tools/pull/1045 necessary have been rolled back. That rollback now means the changes in https://github.com/dotnet/docker-tools/pull/1045 cause build failures because it's attempting to look for the .NET install location in the wrong directory.
I've updated the script to handle either scenario. This allows it to be more robust and at least handle either of these conditions. The team which owns this AzDO task do intend to add roll out there changes again. They were testing it temporarily.
> Compensate for varying .NET install location from manifest task

- eng/common/templates/stages/dotnet/build-test-publish-repo.yml
Due to 1ES conflicts, the pool names are slightly different between internal and public: `Docker-2016 => Docker2016`.
> Update public project pool names

- src/Microsoft.DotNet.ImageBuilder/src/Commands/WaitForMcrImageIngestionCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/McrStatusClient.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/McrStatus/ImageStatus.cs
- src/Microsoft.DotNet.ImageBuilder/tests/WaitForMcrImageIngestionCommandTests.cs
When publishing internal images, the `waitForMcrIngestion` command is not correctly processing the results. It ends up executing an infinite loop because it's not querying the detail results for the images. This happens because the repo prefix `internal/private/` is messing things up. The `ShouldProcessImageStatus` fails to return true for these images because the repo for the image doesn't match the TargetRepository property of the image status result.
For example, the TargetRepository property ends up being `private/dotnet/nightly/aspnet` which is different from the image's repository `dotnet/nightly/aspnet`. TargetRepository represents the location in the ingested registry, not our ACR. So we really should be checking the SourceRepository to be able to correctly compare things. The …
> Support MAR ingestion confirmation for internal repos

- eng/common/templates/jobs/publish.yml
When publishing from a branch with forward slashes, the branch name that gets output in the publish notification contains only the last portion of the branch name. For example, a branch name like `internal/private/nightly` will have its branch name appear in the publish notification issue as `nightly`. This is how the predefined $(Build.SourceBranchName) variable works (see https://github.com/Microsoft/azure-pipelines-agent/issues/838). In order to get the full branch name, we need to use `Build.SourceBranch` but that also includes `/refs/heads` so we strip that out.
> Fix publish notification branch name

- eng/common/templates/variables/dotnet/build-test-publish.yml
The repo prefix for the internal repo is defined incorrectly in the `officialRepoPrefixes` variable. This causes the build to use the `--dry-run` option in the publish stage when attempting to publish to the internal repo. That's not what we want.
Updated with the correct repo name.
> Fix official repo prefix for internal repo

- eng/common/templates/jobs/validate-image-sizes.yml
Fixes a pool name that was missed in https://github.com/dotnet/docker-tools/pull/1050
> Update public pool name for image size validation template

- eng/common/templates/steps/wait-for-mcr-image-ingestion.yml
The changes from https://github.com/dotnet/docker-tools/pull/1049 fixed the implementation of the `waitForMcrImageIngestion` command to use the `--repo-prefix` option. These changes update the pipeline to pass that option to the command when it's invoked in the publish pipeline.
> Flow publish repo prefix to wait for MCR image ingestion

- eng/common/templates/jobs/validate-image-sizes.yml
- eng/common/templates/stages/dotnet/build-test-publish-repo.yml
The public agent pool names have been changed back to their original name, consistent with the naming pattern of the internal pools.
> Revert public pool name changes

- eng/common/templates/stages/build-test-publish-repo.yml
As a result of making broad sets of changes in the https://github.com/dotnet/dotnet-buildtools-prereqs-docker repo that cause a large set of the associated pipelines to be run simultaneously, we're seeing errors in the "Copy Base Images" stage of the pipeline.
```
Operation registries-7ec13324-6d01-4aa8-8d59-451229c80f57 failed. Resource /subscriptions/941d4baa-5ef2-462e-b4b1-505791294610/resourceGroups/DotnetContainers/providers/Microsoft.ContainerRegistry/registries/dotnetdocker Invalid message 429 Too Many Requests Too Many Requests (HAP429).
Microsoft.Rest.Azure.CloudException: Long running operation failed with status 'BadRequest'.
at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.CheckErrorStatusAndThrowAsync(HttpRequestMessage request, HttpResponseMessage response)
at …
```
> Run copyBaseImages with path filtering

- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyBaseImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/FileHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/GitHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/SubscriptionHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/CopyBaseImagesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GetStaleImagesCommandTests.cs
In order to add a subscription to the https://github.com/dotnet/dotnet-buildtools-prereqs-docker repo to participate in auto-rebuilding whenever a base image updates, there are some changes necessary in Image Builder related to its loading of those subscriptions from the https://github.com/dotnet/docker-tools/blob/main/eng/check-base-image-subscriptions.json file.
The dotnet-buildtools-prereqs-docker repo makes use of `System:DockerfileGitCommitSha` variable in its manifests. This variable cannot be computed when Image Builder attempts to load the repo's subscription. That's because the way in which Image Builder gets the repo's code is by downloading the repo zip file from GitHub. The extracted contents of that zip file do not contain a `.git` folder and so the code which retrieves the …
> Use git clone instead of download repo zip

- src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
- src/Microsoft.DotNet.ImageBuilder/Dockerfile.windows
This required an adjustment to the installation method because the release assets for the manifest tool no longer include each separate executable per platform. There's no just a single tarball which contains the executables for all the platforms. So that gets downloaded and we extract just what we need from it.
Also added checksum validation.
Fixes https://github.com/dotnet/docker-tools/issues/1065
> Upgrade manifest tool to 2.0.6

- src/Microsoft.DotNet.ImageBuilder/Dockerfile.az.linux
- src/Microsoft.DotNet.ImageBuilder/manifest.json
The build for the changes from https://github.com/dotnet/docker-tools/pull/1068 is failing because of the `--registry-override` option that is used. (This didn't fail in the PR build because that option is not used for the build.) The Dockerfile.az.linux file had hardcoded the image names it referenced in its `FROM` instructions. In conjunction with the `--registry-override` option, it caused Image Builder to rewrite the file to apply the override. But it generated a `FROM` instruction like this: `FROM dotnetdocker.azurecr.io/dotnet-buildtools/image-builder:linux-$ARCHAS az-installer`. Note the lack of a space between `$ARCH` and `AS`. This isn't valid syntax so the build failed.
We shouldn't be having the Dockerfile be rewritten with the registry option. We want to keep the exact version …
> Fix repo reference in az Dockerfile

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateImageGraphCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
The NuGet dependency graph of Image Builder included a vulnerable version of `System.Drawing.Common` (4.7.0). This was due to an indirect dependency on an older version of `System.Configuration.ConfigurationManager` that various other packages had. I've fixed this by explicitly adding a dependency on `System.Configuration.ConfigurationManager` that gives us version 6.0.0 of `System.Drawing.Common`.
I've also upgraded other packages to their latest versions.
> Update NuGet package versions

- eng/common/Get-ImageBuilder.ps1
- eng/common/Invoke-ImageBuilder.ps1
- eng/common/templates/variables/docker-images.yml
- eng/pipelines/update-image-builder-tag.yml
This helps to support https://github.com/dotnet/dotnet-docker/issues/4139 by allowing internal build pipelines to override the name of the Image Builder image to use within the pipeline. With the changes in https://github.com/dotnet/docker-tools/pull/1068, a suffix is added to the tag name. This allows the overriding pipeline to be able to set the variable to that new name, and base it on the original name, without introducing a cyclic dependency.
> Refactor ImageBuilder variable name

- eng/common/Get-ImageBuilder.ps1
- eng/common/Get-ImageNameVars.ps1
- eng/common/Invoke-CleanupDocker.ps1
The changes in https://github.com/dotnet/docker-tools/pull/1070 broke the use of the `Get-ImageBuilder.ps1` script because it's unable to properly parse the `docker-images.yml` file. The YAML file now includes comments and blank lines that need to be filtered out.
> Fix YAML parsing in Get-ImageBuilder.ps1

- eng/check-base-image-subscriptions-buildtools.json
- eng/check-base-image-subscriptions.json
- eng/pipelines/check-base-image-updates.yml
The changes from https://github.com/dotnet/docker-tools/pull/1075 are incomplete. They are causing base image diffs for all the images that we use from the internal MS mirror. This is because we're not applying the same base image override regex that is used in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/6124dd8d705e266effaffcbb5eca10d9278df8d2/eng/pipelines/steps/set-base-image-override-options.yml#L13.
But applying that regex should only be done for the images in that repo. We don't want to apply it to other repos for which there are base image check subscriptions. To handle that, I've split off the subscription for https://github.com/dotnet/dotnet-buildtools-prereqs-docker into its own subscription file and a separate job configures it to be used.
> Use separate base check subscription for buildtools-prereqs repo

- eng/common/Install-DotNetSdk.ps1
The script that installs .NET is using the "Current" channel which now defaults to .NET 7. This causes the tests to fail because they are compiled for .NET 6. Updating the script to explicitly install .NET 6 for now. We'll update to .NET 7 later.
> Explicitly install .NET 6 SDK

- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
There were component governance alerts for some NuGet packages that weren't directly referenced. These have been explicitly added to get the latest patched version:
* Azure.Storage.Blobs
* Root dependency: Microsoft.Azure.Kusto.Ingest
* Azure.Storage.Queues
* Root dependency: Microsoft.Azure.Kusto.Ingest
* Microsoft.Data.SqlClient
* Root dependency: Microsoft.Azure.Kusto.Ingest
* System.Data.SqlClient
* Root dependency: Microsoft.TeamFoundationServer.Client
I've also updated other packages that had newer versions available.
> Update package dependencies

- eng/common/templates/stages/build-test-publish-repo.yml
- eng/common/templates/steps/parse-test-arg-arrays.yml
- eng/common/templates/steps/test-images-linux-client.yml
- eng/common/templates/steps/test-images-windows-client.yml
- eng/tests/pipeline-validation/run-tests.ps1
Updates the pipeline to pass the set of Dockerfile paths to the test script instead of the product version. More details on this at https://github.com/dotnet/dotnet-docker/pull/4207.
Related to https://github.com/dotnet/dotnet-docker/issues/4185
> Pass Dockerfile paths to to test script

- eng/common/templates/steps/test-images-linux-client.yml
- eng/common/templates/steps/test-images-windows-client.yml
Test jobs are unnecessarily downloading all pipeline artifacts when they actually only need the image-info artifact. This can cause a fairly significant amount of time to execute in some cases, especially on the Arm machines.
This is fixed by explicitly setting the desired artifact name: `image-info`.
Fixes #749
> Only download image-info artifact for test setup

- src/Microsoft.DotNet.ImageBuilder/run-tests.ps1
ImageBuilder tests are failing to run from the pipeline because the pipeline is attempting to pass a `-Paths` parameter (from https://github.com/dotnet/docker-tools/pull/1082) but the script wasn't updated to include that parameter.
I've updated the script to have the parameter. It's not consumed at all because the tests aren't specific to a particular Dockerfile.
> Add Paths parameter for ImageBuilder test script

- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
Add display name support for versionless Ubuntu so that an OS version of `ubuntu` or `ubuntu-chiseled` is displayed as `Ubuntu`.
> Add display name support for generic Ubuntu

- src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
- src/Microsoft.DotNet.ImageBuilder/Microsoft.DotNet.ImageBuilder.sln
- src/Microsoft.DotNet.ImageBuilder/manifest.json
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerService.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerServiceCache.cs
- src/Microsoft.DotNet.ImageBuilder/src/IDockerService.cs
- src/Microsoft.DotNet.ImageBuilder/src/IManifestService.cs
- src/Microsoft.DotNet.ImageBuilder/src/ManifestService.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishManifestCommandTests.cs
Due to the behavior described in #1084, these changes remove the usage of the manifest-tool and instead make use of the `docker manifest` command. While this is technically an experimental feature, it's been that way for years and is widely used. I think the use of this command also puts us in a better position to be supported.
Making use of the `docker manifest push` command always causes the manifest to be pushed even if it already exists. This is the behavior that we need and fixes #1084.
The usage patterns are different between the two such that it required a bit of code rejiggering to spit out the commands we need. The manifest-tool was capable of creating and pushing multiple manifest list tags in one command. The `docker manifest` command requires an individual command invocation …
> Use "docker manifest" command instead of manifest-tool

- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
First part of https://github.com/dotnet/dotnet-docker/issues/4322
> Add Debian 12 Bullseye to ImageBuilder's platform info

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CleanAcrImagesOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyAcrImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyBaseImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyImagesOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/IngestKustoImageInfoOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/ServicePrincipalOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/WaitForMcrDocIngestionOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/WaitForMcrImageIngestionOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/CopyImageService.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/CopyAcrImagesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/CopyBaseImagesCommandTests.cs
A situation can sometimes occur in image caching scenarios where the cached image is pulled from MAR and pushed to the ACR resulting in a different image digest in ACR than it had in MAR. This causes the incorrect data to exist in the image info which affects caching behavior of subsequent builds. It can also affect the logic for querying MAR's image ingestion status because we'll be querying the expected digest which doesn't exist. The reason we'd be querying for image ingestion status for a cached image is if it was assigned new tags.
This is fixed by changing the workflow for how image caching is done. When a cache hit occurs, this is the current workflow:
1. Pull image from MAR by digest
2. Add desired tags based on ACR staging repo
3. Push tags to ACR
Here is the new workflow:
1. …
> Image caching redesign

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PostPublishNotificationCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/DockerHelper.cs
For tag names that have dynamically-generated values, the publish notification that gets created is not using the correct value. It's using the value that was generated when loading the manifest to execute the command rather than the value stored in the image info file.
Fixed the logic to use the tag names from the image info file instead.
Fixes #1010
> Support dynamic tag values in publish notifications

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
The changes from https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/754 caused a failure in the internal build:
```
Error response from daemon: dockerfile parse error line 1: FROM requires either one or three arguments
```
This occurs because Image Builder is incorrectly rewriting the Dockerfile to target the locally built tag instead of the public MCR tag. It ends up replacing the whitespace between the end of the tag and the `AS` keyword, producing this `FROM` instruction: `FROM dotnetdocker.azurecr.io/build-staging/2090449/dotnet-buildtools/prereqs:ubuntu-20.04-crossdeps-localAS binutils`. Notice there's no space before `AS`. This is invalid syntax and causes the error to occur.
This is fixed by using the correct character class in the Regex which does the string …
> Fix regex for FROM image overwrite

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestCommand.cs
As part of the publish process we push manifest list tags and then query them to get their digests. The code which queries for the digests does so by executing all the requests in parallel. When Image Builder was based on .NET 6, we would periodically see the following exception when executing that code:
```
Unhandled exception: System.ArgumentNullException: Value cannot be null. (Parameter 'obj')
at System.OrdinalIgnoreCaseComparer.GetHashCode(String obj)
at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
at System.Net.Http.Headers.HttpHeaders.AddHeaders(HttpHeaders sourceHeaders)
at System.Net.Http.Headers.HttpRequestHeaders.AddHeaders(HttpHeaders sourceHeaders)
at …
```
> Disable concurrent calls for querying manifests

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
Lately there have been random build timeouts popping up at the point where the `build` command tags cached images. It's not clear what is hanging. It could either be a deadlock of some kind in ImageBuilder's caching code (which seems unlikely since that code hasn't changed) or maybe a new version of Docker that doesn't tolerate parallel tagging operations very well, or maybe something else.
Regardless, this should be fixed by changing the logic to create the tags serially rather than in parallel.
> Change tagging from parallel to serial

- src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
Fixes https://github.com/dotnet/docker-tools/issues/1113
> Reference correct runtime-deps image in ImageBuilder Linux Dockerfile

- eng/pipelines/check-base-image-updates.yml
Accounts for the change that was made in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/887. Without this change, the builds to check for base images updates is blocked.
> Remove Fedora from base image override

- src/Microsoft.DotNet.ImageBuilder/src/GraphExtensions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateBuildMatrixCommandTests.cs
Fixes https://github.com/dotnet/docker-tools/issues/1141
I did not test https://github.com/dotnet/docker-tools/pull/1142 enough and it turns out it was still an issue in some cases. In this case, the PlatformVersionedOS matrix graph generation would create multiple legs for the same OS when we needed to build images with a shared cached parent that were not direct siblings. For example, generating a matrix when we have built both `aspnet` and `aspnet-composite` would end up creating two separate test graphs - one with `[runtime-deps, aspnet-composite]` and the other with `[runtime, aspnet, sdk]` (that's before we filter the images down in a later step).
```mermaid
flowchart TD
A[runtime-deps] --> B
A --> E[aspnet-composite]
B[runtime] --> C
C[aspnet] --> D[sdk]
```
The issue is that the …
> Fix build matrix graph generation to include grandparents in calculation

- eng/common/templates/stages/dotnet/build-test-publish-repo.yml
This lets you specify the pool as
```
pool:
name: foo
demands: bar
```
instead of just 
```
pool: foobar
```
Which is needed to facilitate passing a custom 1es hosted pool in the buildtools prereqs repo for this PR. https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/901
> Allow passing custom linuxAmd64Pool as object and not just string

- eng/common/templates/stages/dotnet/build-test-publish-repo.yml
This reverts commit eca722a715f22bde9e3925e2f8ce83390ceba2a0.
It was actually not necessary as can be seen in [this public pipeline run](https://dev.azure.com/dnceng-public/public/_build/results?buildId=332276&view=logs&j=9aada89a-2e24-5acb-2807-6900158b9cce) which successfully gets the correct 1ES hosted pool, even when overriding the `linuxAmd64Pool` default string (`""`).
> Revert "Allow passing custom linuxAmd64Pool as object and not just string (#1155)"

- eng/common/templates/stages/dotnet/build-test-publish-repo.yml
This mitigates an issue that we're having with our Server 2022 pools at the moment. I ran some internal tests and noticed no issues using the 1ES hosted pools. We can switch back once our custom pools are functional again.
> Switch Windows Server 2022 CI legs to 1ES hosted pools

- src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
ImageBuilder is incompatible with Alpine 3.18 until #1161 is addressed, since Alpine 3.18 contains Docker version 23.x, which sets buildkit/buildx as the default. Also see #1159
> Pin Alpine version to 3.17

- eng/common/templates/stages/dotnet/build-test-publish-repo.yml
Docker-2022* pools seem to be in working order now. We can switch back from 1ES hosted pools. Here is an example run that uses agents from the Docker-2022-Internal pool - [pipeline run [internal link]](https://dev.azure.com/dnceng/internal/_build/results?buildId=2230872&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76&j=758d7417-7473-52bb-e4e7-358533cf3cc7)
This reverts commit 08cf0d9476e1bcf72ba44f7275090bd59435b7e5.
Fixes #1164
> Revert "Switch Windows Server 2022 CI legs to 1ES hosted pools (#1163)"

- src/Microsoft.DotNet.ImageBuilder/src/DockerService.cs
This fixes the issue that we saw for patch Tuesday where the wrong Dockerfile was cached for some 7.0 runtime Dockerfiles.
Please see https://github.com/moby/buildkit/issues/1368
It's fixed in Docker version 23, but the bug is in the agent code and not the client, so we would have to wait until our build agents are updated.
> Add workaround for incorrect BuildKit file caching behavior

- eng/common/templates/variables/docker-images.yml
Follow up from https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/918
> Use new CBL Mariner 2.0 based testrunner image

- eng/common/Install-DotNetSdk.ps1
- src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
- src/Microsoft.DotNet.ImageBuilder/Dockerfile.windows
- src/Microsoft.DotNet.ImageBuilder/manifest.json
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PostPublishNotificationCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/INotificationService.cs
- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
- src/Microsoft.DotNet.ImageBuilder/src/NotificationService.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Microsoft.DotNet.ImageBuilder.Tests.csproj
- src/Microsoft.DotNet.ImageBuilder/tests/QueueBuildCommandTests.cs
Fixes https://github.com/dotnet/docker-tools/issues/1162
New Arcade packages target .NET 8.0, so I needed to upgrade ImageBuilder to .NET 8 as well. Took the opportunity to make the Dockerfile multi-platform as well (I have been using this modified Dockerfile for some time to test ImageBuilder in arm64 CI anyways). And as far as I could tell, the LibGit2Sharp issues are all closed so I removed the RID weirdness.
I tested this manually by pointing at a private repo of mine.
> Break publish notifications up into comments

- eng/common/templates/steps/test-images-linux-client.yml
This change was made some time ago in the dotnet-docker main repo but never backported to eng/common, so it got overwritten and caused more problems. Original change: https://github.com/dotnet/dotnet-docker/commit/f2cad09f84ea4f2035c15d57fcd4272ce5fdf174
The [new Mariner testrunner container](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/918) has an older version of Docker that doesn't have BuildKit enabled by default. This should make it use BuildKit by default.
> Manually enable BuildKit in TestRunner container

- eng/src/file-pusher/Dockerfile
- eng/src/file-pusher/file-pusher.csproj
- eng/src/yaml-updater/Dockerfile
- eng/src/yaml-updater/yaml-updater.csproj
This was left out of https://github.com/dotnet/docker-tools/pull/1188 because I searched for `net7.0` and not `7.0` by itself. I will include these files in the checklist I am writing for this procedure. Also downgraded the System.Commandline version to match ImageBuilder after it was updated in error with #1188.
Part of https://github.com/dotnet/docker-tools/issues/1181
> Update file-pusher and yaml-updater dockerfiles to 8.0

- eng/common/templates/jobs/cg-detection.yml
- eng/pipelines/cg-detection.yml
The `ubuntu-latest` Azure DevOps Pools [don't have .NET 8 yet](https://github.com/actions/runner-images/blob/1687f31a3b1ce5f61a7e1e9a4ca23d22ba6e2f7c/images/linux/Ubuntu2204-Readme.md) so they can't build our .NET 8 projects. This fixes the CG pipeline by installing the .NET version we use to build.
> Fix CG build by installing newer .NET version

- eng/common/templates/jobs/cg-detection.yml
The solution in https://github.com/dotnet/docker-tools/pull/1194 worked, however when that flowed to other repos they didn't have a definition for the $(dotnetInstallDir) variable. Since it's only used in this file for this purpose, I just inlined it.
> Fix CG Build in dependent repos by removing variable in CG pipeline template

- eng/pipelines/cg-detection.yml
This was mistakenly left out of https://github.com/dotnet/docker-tools/pull/1195.
> Remove unused variable in CG pipeline

- src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
Fixes build error due to upgrade to Alpine 3.19.
Related: https://github.com/dotnet/dotnet-docker/pull/5202
> Update libgit2sharp and remove dependency on libssl 1.1 compat libraries

- eng/common/templates/variables/common.yml
- eng/pipelines/cg-detection.yml
Refactoring how the skipComponentGovernanceDetection variable is overridden.  The pattern I added in  https://github.com/dotnet/docker-tools/pull/1218 was silly.  This new pattern is the existing pattern used for other common variables.
Test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2405705&view=results (Microsoft internal link)
> Refactor skipComponentGovernanceDetection variable handling

- eng/pipelines/dotnet-docker-tools-eng-validation.yml
Fixes https://github.com/dotnet/docker-tools/issues/1220
[Test run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2405709&view=results) (internal link)
> Migrate eng-validation pipeline to 1ES unofficial template

- eng/common/templates/stages/dotnet/build-test-publish-repo.yml
From the expanded yaml I downloaded from our PR validation pipeline, this code used to expand to: 
```
pool:
image: Mariner-2-Docker-ARM64
os: linux
hostArchitecture: Arm64
name: Docker-Linux-Arm-Public
```
This is invalid since the only image in that pool is `Ubuntu-20.04-Docker-ARM64`. Azure DevOps silently ignores incorrect image name requests, making this YAML misleading.
Related: https://github.com/dotnet/docker-tools/pull/1215#discussion_r1529470841
Test run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2408331&view=results
> Move 1ES PT image definition inside internal project conditional

- eng/common/templates/jobs/build-images.yml
- eng/common/templates/jobs/copy-base-images.yml
- eng/common/templates/jobs/generate-matrix.yml
- eng/common/templates/jobs/publish.yml
- eng/common/templates/jobs/wait-for-ingestion.yml
- eng/common/templates/steps/init-docker-linux.yml
- eng/common/templates/steps/test-images-linux-client.yml
- eng/common/templates/steps/test-images-windows-client.yml
- eng/common/templates/steps/validate-image-sizes.yml
- eng/pipelines/cleanup-acr-images-custom.yml
- eng/pipelines/cleanup-acr-images.yml
- eng/pipelines/templates/jobs/check-base-image-updates.yml
Part of #1213 
These changes are intended to...
Remove the Docker cleanup step:
- From the end of pipeline runs
- Before pre-build validation and matrix generation
Leave the cleanup step:
- Before building any images
- Before mirroring/pulling any base images 
Test run (still running at time of submission, but it's been through a few iterations): https://dev.azure.com/dnceng/internal/_build/results?buildId=2412187&view=results
> Remove certain instances of Docker image cleanup

- eng/common/templates/stages/dotnet/build-test-publish-repo.yml
I am hoping that this will address some public build flakiness. This will also bring the public CI in-line with the internal CI by using the same VM image.
> Use Mariner ARM64 VM image for public builds

- eng/common/templates/1es-official.yml
- eng/common/templates/1es-unofficial.yml
- eng/pipelines/cg-detection.yml
- eng/pipelines/check-base-image-updates.yml
- eng/pipelines/dotnet-buildtools-image-builder-official.yml
- eng/pipelines/dotnet-docker-tools-eng-validation.yml
- eng/pipelines/upload-file.yml
This PR:
- Should fix https://github.com/dotnet/dotnet-docker/issues/5332
- It's hard to validate that it actually fixes this. However I've got a totally green build from dotnet-docker-nightly-playground [here](https://dev.azure.com/dnceng/internal/_build/results?buildId=2427926&view=results) [internal link]. I think it is ignoring the /versions directory correctly.
- Reduces lots of duplication
- Centralizes the location where we define which pool we use for SDL stages
- We could probably do better with the definition. I put it in a parameter, since parameters let you hold arbitrary yaml objects. However we could just inline the whole thing and put all the values in variables.
> Use custom templates for 1ES Pipeline Templates

- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PlatformInfoTests.cs
Fixes #1248 
In addition to the tests added here, I did regenerated the readmes in the dotnet-docker nightly branch and manually verified the changes.
> Update GetOSDisplayName to exclude -distroless

- eng/common/templates/1es-official.yml
Fixes https://github.com/dotnet/dotnet-docker/issues/5399
This is a point-in-time fix, which is why I hard-coded the default pool. All of the hard-coded pool and images names should be re-evaluated as part of https://github.com/dotnet/docker-tools/issues/1227
> Use a default Linux pool for non-sdl tasks

- src/Microsoft.DotNet.ImageBuilder/src/BasicAuthenticationCredentials.cs
- src/Microsoft.DotNet.ImageBuilder/src/ManifestService.cs
- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
- src/Microsoft.DotNet.ImageBuilder/src/RegistryHttpClient.cs
- src/Microsoft.DotNet.ImageBuilder/src/RegistryServiceClient.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
This removes Image Builder's dependency on Microsoft.Azure.Management.Fluent, which is marked as deprecated. The remaining code actually mainly had a dependency on a transitive dependency of Microsoft.Azure.Management.Fluent: Microsoft.Rest.ClientRuntime.
Fixes https://github.com/dotnet/docker-tools/issues/1123
> Remove dependency on Azure Fluent package

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyAcrImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyImagesOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/CopyImageService.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/CopyAcrImagesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/CopyBaseImagesCommandTests.cs
I have the necessary pipeline changes ready to go when this version of ImageBuilder is built and the automated update PR is created.
> Remove service principal authentication from CopyImages commands

- eng/common/templates/steps/validate-branch.yml
- eng/common/templates/variables/common.yml
Fixes #1247 and applies the suggestion that we should fail by default and only pass if specific conditions are met (inverted the existing conditions).
- ~~Still needs to have an additional passing condition for publish prefixes that aren't in the `officialRepoPrefixes`~~
> Fix branch validation

- eng/common/templates/stages/build-test-publish-repo.yml
- eng/common/templates/steps/copy-base-images.yml
- eng/pipelines/check-base-image-updates.yml
- eng/pipelines/templates/jobs/check-base-image-updates.yml
An issue with the base image update pipeline was introduced in https://github.com/dotnet/docker-tools/pull/1261. In order to run with authentication, the copy-base-images step needs to know if it's in the internal project or not, but the parameter was not passed in.
> Pass internalProjectName to copy-base-images from base image update pipeline

- src/Microsoft.DotNet.ImageBuilder/src/ContainerRegistryContentClientFactory.cs
Related to https://github.com/dotnet/docker-tools/issues/1273. The issue of the `build` command not being available was because there was no export for `IContainerRegistryContentClientFactory`.
> Add missing export for IContainerRegistryContentClientFactory

- eng/common/templates/jobs/publish.yml
- eng/common/templates/steps/wait-for-mcr-doc-ingestion.yml
- eng/common/templates/steps/wait-for-mcr-image-ingestion.yml
This hopefully fixes #1278. I don't have a great way to test this. Running it in any other context than a published build (AKA as a dry run) will skip the BuildTaskResults API call that failed in #1278. But maybe we can merge this followed by another open PR and see what happens?
> Revert changes to task names in postPublishNotification args

- src/Microsoft.DotNet.ImageBuilder/src/AuthHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
Microsoft.IdentityModel.Clients.ActiveDirectory is deprecated. This removes all dependencies on that package.
I also removed Microsoft.Identity.Client since a direct dependency is not needed. It's a transitive dependency from Azure.Identity.
Fixes https://github.com/dotnet/docker-tools/issues/1176
> Remove Microsoft.IdentityModel.Clients.ActiveDirectory dependency

- eng/common/templates/jobs/publish.yml
The `Post Publish Notification` task fails with this error:
```
Unhandled exception: System.InvalidOperationException: Build task with name 'Wait For Image Ingestion' could not be found in the build timeline.
```
Fixed by using the correct casing that matches the actual task.
> Fix casing for tasks of publish notification

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PostPublishNotificationCommand.cs
Related to https://github.com/dotnet/docker-tools/pull/1280
This uses case-insensitivity when finding matching task names so the logic isn't so strict.
> Use case insensitive comparison for publish notify tasks

- eng/common/templates/1es-unofficial.yml
This should fix #1285, pending a test that's running internally. This also brings our eng-validation pipeline closer in line with the official pipeline which is a design goal for the eng-validation pipeline.
> Opt-in to SBOM for unofficial pipelines

- eng/common/templates/steps/wait-for-mcr-image-ingestion.yml
- src/Microsoft.DotNet.ImageBuilder/src/McrStatusClient.cs
This should fix https://github.com/dotnet/docker-tools/issues/1286 once the new ImageBuilder is built and flows in.
Using the service connection by itself yielded a new error:
```
---> Azure.Identity.AuthenticationFailedException: ClientAssertionCredential authentication failed: AADSTS1002012: The provided value for scope <snip> is not valid. Client credential flows must have a scope value with /.default suffixed to the resource identifier (application ID URI).
```
So that's why the ImageBuilder change is necessary. I will file a follow-up issue to use a pipeline variable for the status API scope since hardcoding it isn't great.
> Use service connection for MAR ingestion and use .default scope

- src/Microsoft.DotNet.ImageBuilder/src/Commands/IngestKustoImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/IngestKustoImageInfoOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Services/IKustoClient.cs
- src/Microsoft.DotNet.ImageBuilder/src/Services/KustoClientWrapper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/IngestKustoImageInfoCommandTests.cs
Removes the use of service principal configuration for authentication to the Kusto cluster and replaces it with `DefaultAzureCredential` which will enable the use of a Managed Identity in the pipeline.
Contributes to https://github.com/dotnet/docker-tools/issues/1264
> Use MSI for Kusto authentication

- eng/common/templates/steps/run-imagebuilder.yml
- eng/common/templates/steps/run-pwsh-with-auth.yml
- eng/common/templates/steps/test-images-linux-client.yml
- eng/common/templates/steps/test-images-windows-client.yml
This removes the use of credentials for logging into the ACR in test jobs and replaces it with the use of a service connection.
This requires the changes in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1057.
Contributes to https://github.com/dotnet/docker-tools/issues/1264
> Use ACR service connection to login to ACR for test job

- eng/common/templates/steps/run-pwsh-with-auth.yml
The changes in https://github.com/dotnet/docker-tools/pull/1290 are causing a failure in the image builder pipeline:
```
Job Publish: The step name RunPwshWithAuth appears more than once. Step names must be unique within a job.
```
The template needs to not default a name for the step because it can cause duplicates. Instead, it should be defaulted to nothing.
> Conditionally set task name

- eng/common/templates/jobs/publish.yml
Updates to reflect the current display names of the tasks.
> Fix task names for publish notification

- src/Microsoft.DotNet.ImageBuilder/src/ImageBuilder.cs
- src/Microsoft.DotNet.ImageBuilder/tests/DependencyInjectionTests.cs
Fixes #1273 by adding a test that will fail when there are any composition errors. Also by adding the config option for disabling silent rejection on the container, ImageBuilder will no longer start when there are composition errors.
> Add simple test for MEF Dependency Injection

- src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
Add ORAS tooling to Linux Image Builder image.
Used instructions from https://oras.land/docs/installation/ with necessary modification for Alpine, to use `wget` instead of `curl`.
> Add ORAS tool to Linux ImageBuilder images

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/ContainerRegistryContentClientFactory.cs
- src/Microsoft.DotNet.ImageBuilder/tests/DependencyInjectionTests.cs
The Docker login token is expiring after a certain period for builds that take a long time (e.g. 3 hrs). This causes the `docker push` operation to fail with an `unauthorized` error.
Resolving this by refreshing the token by logging in again right before the push.
> Refresh login token before publish

- src/Microsoft.DotNet.ImageBuilder/src/ContainerRegistryContentClientFactory.cs
- src/Microsoft.DotNet.ImageBuilder/tests/DependencyInjectionTests.cs
The changes from https://github.com/dotnet/docker-tools/pull/1310 are causing a failure in the `GenerateBuildMatrix` pipeline step because the agent has no auth configuration in that step, causing the `GetToken` method to fail during component composition.
Workaround is to just catch the exception. It will work correctly in build steps that are configured with authentication enabled.
> Workaround for token failure in non-authenticated configurations

- src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
When iteratively building the Dockerfile after making changes to the Image Builder code, it causes the ORAS tool to be downloaded each time. This is unnecessary and a waste of time. To improve this experience, I've moved that logic up in the Dockerfile, before Image Builder gets built, so that it can take advantage of the layer caching.
> Make better use of layer caching in Dockerfile

- src/Microsoft.DotNet.ImageBuilder/src/AuthHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/AzureScopes.cs
- src/Microsoft.DotNet.ImageBuilder/src/AzureTokenCredentialProvider.cs
- src/Microsoft.DotNet.ImageBuilder/src/AzureTokenCredentialProviderExtensions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CleanAcrImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/ContainerRegistryContentClientFactory.cs
- src/Microsoft.DotNet.ImageBuilder/src/CopyImageService.cs
- src/Microsoft.DotNet.ImageBuilder/src/IAzureTokenCredentialProvider.cs
- src/Microsoft.DotNet.ImageBuilder/src/McrStatusClient.cs
- src/Microsoft.DotNet.ImageBuilder/src/RegistryContentClientFactory.cs
- src/Microsoft.DotNet.ImageBuilder/src/RegistryCredentialsProvider.cs
- src/Microsoft.DotNet.ImageBuilder/src/Services/KustoClientWrapper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/CleanAcrImagesCommandTest.cs
- src/Microsoft.DotNet.ImageBuilder/tests/RegistryContentClientFactoryTests.cs
Fixes https://github.com/dotnet/docker-tools/issues/1316
The original changes from https://github.com/dotnet/docker-tools/pull/1310 and https://github.com/dotnet/docker-tools/pull/1314 were hacks in order to deal with token expiration that occurs with a long-running command. If execution of the command takes longer than an hour and then an attempt is made to retrieve an Azure access token, it will fail. This is resolved by retrieving the token at the beginning of the command instead.
This defines a provider component that returns an Azure credential that's configured with a pre-cached access token. The access tokens are retrieved during the startup of the command during component composition.
In order to get the tokens, we have to know the scope ahead of time. So these are explicitly …
> Improve Azure token logic

- src/Microsoft.DotNet.ImageBuilder/src/NotificationService.cs
#1322 has been affecting us for a few days, so I'm submitting this PR to hopefully work around the issue and get our builds green by catching OverflowExceptions when posting comments. We can remove it once the issue is fixed in OctoKit and then Microsoft.DotNet.Git.IssueManager.
> Catch Overflow exceptions to workaround OctoKit issue

- eng/common/templates/stages/dotnet/build-test-publish-repo.yml
Needed to set arm timeout in jobs that (indirectly) use this template. Context: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1083/files#r1633704323
@mthalman PTAL
> Pass through linuxArmBuildJobTimeout

- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
- src/Microsoft.DotNet.ImageBuilder/src/NotificationService.cs
Fixes #1322 
Also references Octokit explicitly in ImageBuilder's project file since we do use it explicitly:
https://github.com/dotnet/docker-tools/blob/c3f7994c4e427812c1b9c07b3b050104d4c4eb6e/src/Microsoft.DotNet.ImageBuilder/src/BlobsClientExtensions.cs#L7
> Explicitly reference Octokit package in ImageBuilder and revert #1325

- src/Microsoft.DotNet.ImageBuilder/src/CopyImageService.cs
The changes from https://github.com/dotnet/docker-tools/pull/1321 cause an attempt to get a token in `CopyImageService` when executing in dry run mode. This causes the following exception:
```
Unhandled exception: Azure.Identity.CredentialUnavailableException: DefaultAzureCredential failed to retrieve a token from the included credentials. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/defaultazurecredential/troubleshoot
- EnvironmentCredential authentication unavailable. Environment variables are not fully configured. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/environmentcredential/troubleshoot
- WorkloadIdentityCredential authentication unavailable. The workload options are not fully configured. See the …
```
> Move ArmClient initialization out of dry run

- eng/common/templates/jobs/build-images.yml
- eng/common/templates/jobs/publish.yml
- eng/common/templates/steps/clean-acr-images.yml
- eng/common/templates/steps/copy-base-images.yml
- eng/common/templates/steps/test-images-linux-client.yml
- eng/common/templates/steps/test-images-windows-client.yml
- eng/common/templates/variables/common.yml
- eng/common/templates/variables/docker-images.yml
- eng/pipelines/cleanup-acr-images-custom.yml
- eng/pipelines/cleanup-acr-images.yml
Related to https://github.com/dotnet/dotnet-docker-internal/issues/5024 and https://github.com/dotnet/dotnet-docker-internal/issues/5026
This PR updates the ymls to use the appropriate ACR server and serviceConnectionName for the given repo. The changes were made to the following ymls:
- common/templates/jobs/build-images.yml
- common/templates/jobs/publish.yml
- common/templates/steps/clean-acr-images.yml
- common/templates/steps/copy-base-images.yml
- common/templates/steps/test-images-linux-client.yml
- common/templates/steps/test-images-windows-client.yml
- pipelines/cleanup-acr-images-custom.yml
- pipelines/cleanup-acr-images.yml
[ImageBuilder pipeline run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2459246&view=results)
[Windows tests pipeline …
> Pipeline Changes for Pushing Mirror and Build-Staging Repositories to Separate ACR

- eng/common/templates/jobs/copy-base-images-staging.yml
- eng/common/templates/jobs/copy-base-images.yml
- eng/common/templates/stages/build-test-publish-repo.yml
- eng/common/templates/steps/copy-base-images-staging.yml
- eng/common/templates/steps/copy-base-images.yml
- eng/pipelines/mirror-base-images.yml
- eng/pipelines/templates/jobs/check-base-image-updates.yml
- eng/pipelines/templates/jobs/copy-base-images-public-mirror.yml
1/2 of https://github.com/dotnet/dotnet-docker-internal/issues/5504
Implements a new subscription type (manifest-only subscription) and pipeline that consumes that subscription. The pipeline runs an import of all the base images into our cache ACR. Some minor refactoring of the CopyBaseImages pipeline templates was required.
> Add pipeline for mirroring base images to cache ACR on a schedule

- src/Microsoft.DotNet.ImageBuilder/src/ReadmeHelper.cs
Readme generation doesn't allow a readme to contain the `Full Tag Listing` header w/o also injecting the tags table. This blocks the implementation of https://github.com/dotnet/dotnet-docker/pull/5585. See https://github.com/dotnet/dotnet-docker/pull/5585#discussion_r1647680272.
In such a scenario where a readme has the header but not the end of tags marker, it essentially duplicates much of the readme and prepends it, along with the tags table. I've updated the logic to check if the end of tags marker is not present and not inject the tags table in that case. (The original intent was to throw if this marker was missing but there was a bug there preventing that from happening.)
> Allow readmes to have tags header w/o tags table

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
Fixes #1350 
The changes from https://github.com/dotnet/docker-tools/pull/1321 don't work for long-running jobs. The presumption was that the necessary tokens would be retrieved up front when Image Builder runs a command. (It's necessary for the token to be retrieved right away while we still have a valid OIDC token from the pipeline. If you wait too long the OIDC token will expire, preventing you from retrieving any access tokens with it.) But this isn't true for the `build` command. It retrieves a token for the `AzureScopes.ContainerRegistryScope` scope at the end of the build when querying for digests of the pushed images. This is the first time an attempt is made to get a token for that scope. So no cached token exists for that scope. But by this point the OIDC token from the pipeline …
> Prepopulate credential cache for ACR

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
The change from https://github.com/dotnet/docker-tools/pull/1352 was causing the `build` command to fail on public builds because the environment isn't configured to have creds.
Updated it to only execute when push is enabled, which is the case for internal builds where the creds will exist.
> Only prepopulate creds cache when push enabled

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishManifestCommandTests.cs
The `publishManifest` command ran into the [same issue as the `build` command](https://github.com/dotnet/docker-tools/issues/1350). See [example build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2482890&view=logs&j=739bb7ec-7296-5b40-7dff-ee3297bfdaa4&t=6123d7e1-dcba-5ae2-930b-8eeaf17e8400&s=380ab8c6-4139-55ff-15c4-fb48260f4dca) (internal link). In this case, there were numerous errors while pushing the manifests which resulted in a lot of retries. Those retries eventually succeeded but the overall effect was that the command took a long time to run. At the end of the command, it attempts to query the registry to get the digests and the token had expired due to the length of time.
The fix is to follow the same pattern that was done to fix the `build` command with …
> Prepopulate token cache for publishManifest cmd

- eng/common/templates/jobs/publish.yml
Closes https://dev.azure.com/dnceng/internal/_build/results?buildId=2483932&view=results
Moves the artifact publishing to end of the publishing stage.
[Test run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2483932&view=results) (internal Microsoft link)
> Move SB Artifact Publishing

- src/Microsoft.DotNet.ImageBuilder/src/Commands/CleanAcrImagesCommand.cs
The changes in https://github.com/dotnet/docker-tools/pull/1385 added a `docker login` call to ensure credentials were configured for calling `oras`. But this doesn't work when executing the image-clean pipeline in dry run mode. When dry run is set to true for the login call, it doesn't actually invoke the command. So no login occurs and the subsequent `oras` calls all fail.
This change explicitly sets dry run to `false` for the login command.
> CleanAcrImages: don't use dry run for login

- eng/common/templates/steps/annotate-eol-digests.yml
- eng/pipelines/annotate-eol-digests.yml
* Updates the annotation publishing to account for the updates in https://github.com/dotnet/docker-tools/pull/1364.
* Consumes the new command from https://github.com/dotnet/docker-tools/pull/1373 to wait until annotations have been ingested.
* Publish a pipeline artifact text file of the annotation digests that were pushed.
> EOL Annotation pipeline updates

- src/Microsoft.DotNet.ImageBuilder/src/MarImageIngestionReporter.cs
While running a build that executed the MAR ingestion reporting logic, I encountered a scenario where a status had a value of `Unknown` that was not handled. It caused a `NotSupportedException` to be thrown by the code. Upon examining the digest that was being reported on, it eventually did have a `Succeeded` state.
This updates the code to handle the `Unknown` state just like it would other "pending" states.
> Handle unknown state for MAR ingestion

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateEolAnnotationDataCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateEolAnnotationDataCommandTests.cs
When running `GenerateEolAnnotationDataCommand` on the dotnet-docker repo, it was getting an error due to the existence of `9.0-preview` product versions in the image info file:
```
Error occurred while generating EOL annotation data: System.FormatException: The input string '0-preview' was not in a correct format.
at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
at System.Version.Parse(String input)
at Microsoft.DotNet.ImageBuilder.Commands.GenerateEolAnnotationDataCommand.GetProductEolDigests(ImageData image, Dictionary`2 productEolDates) in /image-builder/src/Commands/GenerateEolAnnotationDataCommand.cs:line 192
at Microsoft.DotNet.ImageBuilder.Commands.GenerateEolAnnotationDataCommand.GetDige …
```
> EOL annotation generation update to handle pre-release versions

- src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
- src/Microsoft.DotNet.ImageBuilder/manifest.json
Closes https://github.com/dotnet/docker-tools/issues/1392
[Test build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2515837&view=results) (internal Microsoft link)
> Use azure linux for Image Builder container image

- src/Microsoft.DotNet.ImageBuilder/src/Commands/CleanAcrImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
This change adjusts how many delete requests that are sent to the ACR when cleaning up manifests. This avoids potential issues that have been seen when sending several thousand delete requests at once. It makes use of the concurrency limiter from Polly. That lets us queue up all our delete tasks at once and then it will only allow a specific number of them to execute concurrently.
> Use concurrency limiter when deleting repo manifests

- src/Microsoft.DotNet.ImageBuilder/src/Commands/IOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/Options.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/TagInfo.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/VariableHelper.cs
> Remove support for DockerfileGitCommitSha and TimeStamp system variables

- .config/dotnet-tools.json
- .vault-config/secrets.yaml
- eng/pipelines/secret-management-weekly.yml
Copy from https://github.com/dotnet/dotnet-docker/pull/5797 in dotnet-docker.
Closes https://github.com/dotnet/dotnet-docker/issues/4517
This PR onboards .NET Docker Bot to secret manager and introduces a new pipeline for rotating secrets on a weekly basis.
[Example pipeline run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2519194&view=logs&j=adcf571c-cc13-5e72-b2ad-561cfc37a926)
> Onboard .NET Docker Bot to secret manager

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateEolAnnotationDataCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateEolAnnotationDataCommandTests.cs
There are a couple issues with the logic in `GenerateEolAnnotationDataCommand` related to image names that prevent it from working properly in the production environment:
* When computing the repo names to process, it doesn't prepend the repo prefix specified in the command options. This prevents it from querying the correct repos to find images that need to be annotated.
* The image digest names in the image info file are based on their public name (e.g. mcr.microsoft.com). These values need to be transformed to the ACR name (with repo prefix) in order to properly match against the names in the ACR.
> Use repo prefix for EOL data logic

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateEolAnnotationDataCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateEolAnnotationDataOptions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateEolAnnotationDataCommandTests.cs
The `GenerateEolAnnotationDataCommand` calls the `oras` tool to query for annotations. In order for the `oras` tool to communicate with the ACR, it needs to be authenticated. This isn't being done today, so it fails in the pipeline with unauthorized errors (it works locally when you're logged into docker CLI).
> Login to Docker for GenerateEolAnnotationDataCommand

- src/Microsoft.DotNet.ImageBuilder/src/Commands/CleanAcrImagesCommand.cs
Ran into another issue with the ACR getting in a bad state from image deletion. Related to https://github.com/dotnet/docker-tools/pull/1401. Reducing the concurrent request count down some more to try to prevent this from happening.
> Reduce concurrent delete request count

- eng/common/templates/jobs/publish.yml
- eng/common/templates/steps/annotate-eol-digests.yml
- eng/common/templates/variables/common.yml
- eng/pipelines/annotate-eol-digests.yml
Contributes to https://github.com/dotnet/docker-tools/issues/1201
Updates the publish stage of the common pipeline infrastructure to support pushing EOL annotations.
This is opt-in behavior for consuming pipelines. A pipeline will need to set the `publishEolAnnotations` variable to `true` to opt in.
> Push EOL annotations in publish stage

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateEolAnnotationDataCommand.cs
When executing `GenerateEolAnnotationDataCommand` in dry run mode, it attempts to authenticate with Azure credentials in the `GetAllImageDigestsFromRegistry` method. This fails on the build agent because it has no default Azure credentials.
This is fixed by defaulting the method results to an empty set when in dry run mode.
> Dry run fix for GenerateEolAnnotationDataCommand

- src/Microsoft.DotNet.ImageBuilder/src/RegistryCredentialsProviderExtensions.cs
I ran into an issue in https://github.com/dotnet/dotnet-docker/pull/5837 where `PublishManifestCommand` was failing after defaulting the value of the `acr.server` to an empty value for public builds. Previously, this variable was undefined and so the pipeline was interpreting `$(acr.server)` as the literal value. But I needed to set it to an empty value to fix a different issue, which is the correct thing to do in this case. But when setting it to an empty value, it was causing `PublishManifestCommand` to attempt to get default Azure credentials and failing. This is because the public builds are not configured to have auth. The reason that setting `acr.server` to an empty value causes this is because of the combination of these calls: …
> Avoid getting creds on dry run

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageCacheService.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageNameResolver.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
Contributes to #1417 
In order to implement the approach described in https://github.com/dotnet/docker-tools/issues/1417#issuecomment-2315921521, we need to have common logic for determining whether an image is cached or not. This is currently defined in `BuildCommand`. In order to reuse that logic for the matrix generation, it's being factored out into a separate reusable service.
> Factor out image caching logic from BuildCommand

- eng/common/templates/jobs/publish.yml
- eng/common/templates/steps/annotate-eol-digests.yml
- eng/pipelines/annotate-eol-digests.yml
* Avoids pipeline artifact name collision when publishing EOL data artifact
* Supports PR builds by setting the dry run option for the `annotateEolDigests` command.
> Minor updates for EOL annotation publishing

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/RegistryCredentialsProviderExtensions.cs
Fixes #1424 
Instead of running `BuildImagesAsync()` under authentication the whole time, defer login to only when we need to pull cached images in the case of a cache hit. That should be the only place we need credentials during the actual building of images, since we already pulled the base images with `PullBaseImagesAsync()`.
This has the added benefit of running the rest of the build command without any Docker credentials, since they shouldn't be necessary (and should fail the build).
> Defer Docker login until just before pulling cached images during build command

- src/Microsoft.DotNet.ImageBuilder/src/Commands/CleanAcrImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CleanAcrImagesOptions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/CleanAcrImagesCommandTest.cs
On rare occasions, there may be specific images that should be excluded from being cleaned by the `cleanAcrImages` command.
This adds a new `--exclude` option to the command that provides a way for the caller to provide an image name that will be excluded from being cleaned. Multiple `--exclude` options can be provided if necessary. This supports an image name that is referenced by tag or digest.
> Allow images to be excluded from cleaning

- eng/common/templates/jobs/publish.yml
- eng/common/templates/variables/docker-images.yml
Fixes https://github.com/dotnet/docker-tools/issues/1433
This uses the new options added in https://github.com/dotnet/docker-tools/pull/1434 to get the content of the image info file before and after it gets updated by the `publishImageInfo` command. This provides accurate content of these files that the existing pipeline steps which use `curl` to download the file do not. So those steps have been removed as well.
> Consume image info output of publishImageInfo command

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoCommand.cs
The changes from https://github.com/dotnet/docker-tools/pull/1434 cause issues in the pipeline when dry run is enabled because the `generateEolAnnotationData` command that gets executed after it expects those files to exist. But in dry run, those files are not written to.
This is fixed by moving the check for dry run so that it is after those files get written to.
> Fix dry run logic in publishImageInfo

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
This fixes the following error when building in a local dev scenario:
```
Found published digest 'sha256:329a2269a558de2f9da355342b5328f62733af8c975075d5513fcb5a65717363' for tag
'mcr.microsoft.com/dotnet/nightly/runtime-deps:8.0.8-bookworm-slim-amd64' but could not find a matching
digest value from the set of locally pulled digests for this tag: 
mcr.microsoft.com/dotnet/nightly/runtime-deps@sha256:8421fbf62d06c7e340e75c0103a34cf15c260033891623148c48bb47f98a2086, <snipped lots of duplicates>. 
This most likely means that this tag has been updated since it was last pulled.
```
https://github.com/dotnet/docker-tools/pull/1418 made it so that `platformData` in `BuildImagesAsync()` is never null, even when building without the intent to push to a repo - that's fine, but it also removed a …
> Fix build command for local dev scenario

- README.md
- src/Microsoft.DotNet.ImageBuilder/README.md
This PR documents the workflow for building ImageBuilder for the purposes of testing changes in pipelines. It covers single-platform, multi-arch, and multi-platform (Windows + Linux) container image builds.
> Add ImageBuilder container build instructions

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageNameResolver.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateBuildMatrixCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Helpers/ManifestServiceHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishManifestCommandTests.cs
Contributes to #1417
This adds trimming logic to Image Builder's matrix generation. This trimming will optimize the number of build jobs that get created. It prevents scenarios of spinning up jobs that are essentially no-ops because the images they process may all be cached.
It trims the set of Dockerfiles based on whether cached images already exist for those Dockerfiles. Once that set of Dockerfiles is determined, then it proceeds with its usual logic, potentially expanding the set of Dockerfiles that get included. So the final matrix result may include images which are cached, but those are necessary to be included based on the build requirements.
> Trim matrix based on image cache state

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateBuildMatrixCommandTests.cs
The changes in https://github.com/dotnet/docker-tools/pull/1449 didn't correctly handle the scenario where path filters are provided to the `generateBuildMatrix` command (e.g. `--path <value>`). It was essentially ignoring what was filtered by those options and only processing the content of the provided image info file. This causes more images to be built than are intended.
> Support path filters for matrix trimming

- eng/common/templates/jobs/generate-matrix.yml
- eng/common/templates/stages/build-test-publish-repo.yml
The changes from https://github.com/dotnet/docker-tools/pull/1459 cause a failure during the Test stage ([example build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2556433&view=results) - internal link): `generateBuildMatrix: command not found`.
This is because it's attempting to run the command directly from the agent rather than from the container. This was a result of a mistake in the YAML. It was attempting to condition the logic differently depending on whether it was generating a matrix for the test stage or not. But that was unnecessary. In both build stage and test stage scenarios, it can use the same template logic for running the command.
Another issue was that `Set GenerateBuildMatrix Command` step had a silent failure: `commonMatrixAndBuildOptions: command …
> Fix test stage matrix generation

- eng/common/templates/jobs/build-images.yml
- eng/common/templates/stages/build-test-publish-repo.yml
- eng/common/templates/stages/dotnet/build-test-publish-repo.yml
Backport of changes in `eng\common` from https://github.com/dotnet/dotnet-docker/pull/5928
These changes enable testing of internal builds in our pipelines:
- Update pipeline stages/steps/jobs for support of internal testing scenario
- Update pipeline for internal testing so it behaves as if it was a Pull request
> Add support for testing of internal builds

- eng/pipelines/cleanup-acr-images.yml
This will cleanup old EOL images within the dotnet-buildtools/prereqs repo, excluding a custom defined image that will be defined via a variable in AzDO.
> Add clean leg for buildtools-prereqs

- eng/common/templates/jobs/generate-matrix.yml
- eng/common/templates/stages/build-test-publish-repo.yml
- eng/common/templates/stages/dotnet/build-test-publish-repo.yml
This adds support for being able to supply custom init steps for matrix jobs.
This is a backport of the changes from https://github.com/dotnet/dotnet-docker/pull/5968.
> Support custom init steps for matrix job

- eng/common/templates/steps/common-init-for-matrix-and-build.yml
Fixes https://github.com/dotnet/dotnet-docker/issues/5967
The underlying issue was that the tsa config's path location is variable depending on whether or not the pipeline has multiple repos. The AzDO checkout step behaves differently if there are multiple repos being cloned versus a single.  There is no built in variables to determine the default repos path.  
Because of this the tsa config file's path cannot be easily determined in the [1es-official.yml](https://github.com/MichaelSimons/docker-tools/blob/f69f0104ba2243990cc29fd7e69e67afa626fcb1/eng/common/templates/1es-official.yml#L57-L58) in order to specify a custom config path parameter.  Given the 1es-official template is used in a variety of scenarios and that our build logic is encapsulated in templates, it makes it difficult to …
> Add special logic to handle tsa config in common build template

- eng/common/templates/steps/common-init-for-matrix-and-build.yml
This fixes an issue with https://github.com/dotnet/docker-tools/pull/1468.  Public GitHub repo names include the organization but that is trimmed from the git repo name.  This was tested in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1212
> Update repo name variable used in Copy TSA Config

- eng/common/templates/stages/build-test-publish-repo.yml
This PR fixes the issue with missing parameter for Windows 2025 build job causing failure of internal servicing validation pipeline: https://dev.azure.com/dnceng/internal/_build/results?buildId=2557405&view=results
Windows 2025 job was added with https://github.com/dotnet/docker-tools/pull/1454
Internal servicing validation changes were in flight at the same time, and did not cover Windows 2025: https://github.com/dotnet/docker-tools/pull/1463
> Supply isInternalServicingValidation to Windows 2025 build job

- eng/common/templates/stages/build-test-publish-repo.yml
- eng/common/templates/steps/common-init-for-matrix-and-build.yml
Fixing regression caused by merge of refactoring change (https://github.com/dotnet/docker-tools/pull/1459) and internal testing change (https://github.com/dotnet/docker-tools/pull/1463)
Refactored template didn't get the required `isInternalServicingValidation` parameter.
> Add isInternalServicingValidation parameter to common-init-for-matrix-and-build.yml steps

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateReadmesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/McrTagsMetadataGenerator.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/McrTags/TagGroup.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/PlatformInfo.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/VariableHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateReadmesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Helpers/ManifestHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/McrTagsMetadataGeneratorTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Microsoft.DotNet.ImageBuilder.Tests.csproj
This change allows patterns like:
`aspire-dashboard-tags.yml`
```yaml
$(McrTagsYmlRepo:aspire-dashboard)
$(McrTagsYmlTagGroup:8)
```
`monitor-tags.yml`
```yaml
$(McrTagsYmlRepo:monitor)
$(McrTagsYmlTagGroup:9.0)
$(McrTagsYmlTagGroup:8.1-preview-ubuntu-chiseled|.NET Monitor Preview Tags)
$(McrTagsYmlTagGroup:8.1-preview-cbl-mariner-distroless|.NET Monitor Preview Tags)
$(McrTagsYmlTagGroup:8.0-ubuntu-chiseled)
$(McrTagsYmlTagGroup:8.0-cbl-mariner-distroless)
$(McrTagsYmlTagGroup:6.3-alpine)
$(McrTagsYmlTagGroup:6.3-ubuntu-chiseled)
$(McrTagsYmlTagGroup:6.3-cbl-mariner)
$(McrTagsYmlTagGroup:6.3-cbl-mariner-distroless)
```
`runtime-tags.yml`:
```yaml
$(McrTagsYmlRepo:runtime)
$(McrTagsYmlTagGroup:9.0-bookworm-slim)
$(McrTagsYmlTagGroup:9.0-alpine3.20)
$(McrTagsYmlTagGroup:9.0-noble) …
```
> Allow multi-arch tags in MCR tags metadata templates

- eng/pipelines/cleanup-acr-images.yml
Configures the clean pipeline to target all EOL images in the `dotnet/framework/*` repos.
> Clean dotnet/framework images that are EOL

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateBuildMatrixCommandTests.cs
Fixes https://github.com/dotnet/docker-tools/issues/1476
The matrix trimming logic was using the image info file as its source for processing Dockerfiles to be trimmed or not. This meant that any new Dockerfiles which have not yet been built/published were not being included because they were not represented in the image info file yet.
These changes update the logic to use the manifest as the source and then to look up the corresponding image info data from that. By using the manifest as the source, we're sure to process all Dockerfiles. This includes a bit of refactoring to share common code with the `getStaleImages` command which needs to use the same logic.
> Support new Dockerfiles in matrix trimming

- eng/common/templates/jobs/post-build.yml
- eng/common/templates/steps/download-build-artifact.yml
Fixes #1477 
In some scenarios, a pipeline run doesn't actually run any build jobs due to matrix trimming. This prevents any pipeline artifacts from being published. The Post-Build stage needs to be resilient to this scenario and not fail when there are no artifacts to download.
> Prevent post-build fail on artifact download

- src/Microsoft.DotNet.ImageBuilder/src/Commands/MergeImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/MergeImageInfoOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoOptions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/MergeImageInfoFilesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishImageInfoCommandTests.cs
Contributes to #1470 
As described in https://github.com/dotnet/docker-tools/issues/1470#issuecomment-2436157156, this updates Image Builder so that it splits apart the merging of image info files from the act of publishing the image info file to the versions repo. That logic has been removed from the `publishImageInfo` command. Instead, the already existing `mergeImageInfo` command has been updated to handle the publish scenario. So now `mergeImageInfo` command can be used for merging image info fragments from multiple build jobs (Post-Build stage) as well as merging the final image info with the image info from the versions repo (Publish stage).
> Split merging of image info from publishing

- eng/common/templates/jobs/publish.yml
- eng/common/templates/variables/docker-images.yml
Fixes #1470 
This is in response to the changes to the commands in https://github.com/dotnet/docker-tools/pull/1488.
It changes the Publish stage to first take the image info produced by the build and merge it into the latest image info from the versions repo. Later in the pipeline (after EOL annotations have been published), it will push the merged image info file to the versions repo.
> Update pipeline for changes to image info commands

- eng/common/templates/jobs/publish.yml
Remove an unnecessary step from the publish stage. This was used for debugging purposes and not meant to be included.
> Remove debugging step from publish stage

- src/Microsoft.DotNet.ImageBuilder/src/Commands/AnnotateEolDigestsCommand.cs
Fixes the issue described in https://github.com/dotnet/dotnet-docker/pull/6048#issuecomment-2474425538.
The comment made there wasn't quite accurate. It's nothing to do with there being a null digest. It has to do with the fact that it's processing any data at all from the EOL annotation data file. Normally, there isn't any data in that file. When there is, it attempts to process that data in `AnnotateEolDigestsCommand` which doesn't handle it well in a dry run.
In general, we try to have as much logic as possible execute in the context of a dry run. But given that much of the logic of the `AnnotateEolDigestsCommand` is dependent on the results returns from `oras`, which doesn't actually get executed in a dry run`, it's not really feasible to execute much of it. So this short-circuits the …
> Handle dry run for AnnotateEolDigestsCommand

- src/Microsoft.DotNet.ImageBuilder/src/McrTagsMetadataGenerator.cs
- src/Microsoft.DotNet.ImageBuilder/tests/McrTagsMetadataGeneratorTests.cs
- Created a much more actionable error message for when tags are missing.
- Slight refactoring of the tests to support more flexible platforms, and using simpler computation to get the expected tags.
> Improve missing tags error message and add Windows test for tags metadata generator

- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyAcrImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishManifestCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/TrimUnchangedPlatformsCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/WaitForMcrImageIngestionCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/PipelineHelper.cs
Related to the suggestion in https://github.com/dotnet/docker-tools/pull/1494/files#r1841053475, this updates publish-related commands to gracefully handle an image info file that doesn't exist and just no-op in that scenario.
> Gracefully handle missing image info in publish commands

- src/Microsoft.DotNet.ImageBuilder/src/Commands/CleanAcrImagesCommand.cs
Ran into another issue with the ACR getting in a bad state from image deletion. Related to https://github.com/dotnet/docker-tools/pull/1401. Reducing the concurrent request count down some more to try to prevent this from happening.
> Reduce concurrent delete requests

- eng/common/templates/steps/init-docker-windows.yml
This PR fixes an issue that was encountered when publishing Server 2025 images: https://dev.azure.com/dnceng/internal/_build/results?buildId=2589255&view=logs&j=11434e3e-4fd8-538e-73a7-1fa357b5715e&t=ac305b46-e5f7-5446-77d9-86c252a1ec29&l=49 [internal MSFT link]
```
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\a\_work\_temp\azureclitaskscript1732567089292.ps1'"
Program 'token' failed to run: The operation attempted is not supportedAt 
C:\a\_work\_temp\azureclitaskscript1732567089291_inlinescript.ps1:1 char:179
+ ... lId; $env:AZURE_FEDERATED_TOKEN_FILE = C:\a\_work\_temp\token; C:\a\_ ...
+                                            ~~~~~~~~~~~~~~~~~~~~~~.
At …
```
> Add extra quoting for federated token file path

- src/Microsoft.DotNet.ImageBuilder/src/Commands/Command.TOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/DockerfileFilterOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateDockerfilesOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/IFilterableOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/ManifestFilterOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/ManifestOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/Options.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PlatformFilterOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/QueueBuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageBuilder.cs
- src/Microsoft.DotNet.ImageBuilder/src/SubscriptionHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateBuildMatrixCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GetStaleImagesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/QueueBuildCommandTests.cs
This PR contains some changes needed to accomplish [Consider using Docker custom build outputs (`--output`) for generated Dockerfiles and Readmes (dotnet/dotnet-docker#5654)](https://github.com/dotnet/dotnet-docker/issues/5654), by fixing [ImageBuilder requires Docker to run all commands, even if they don't use it (#1428)](https://github.com/dotnet/docker-tools/issues/1428).
These changes shouldn't cause breaks for any features used by any commands. It does remove some filtering options from `GenerateDockerfiles`, but those options were unused.
Commits are separated into buildable chunks that each pass all tests, if that makes reviewing easier.
- https://github.com/dotnet/dotnet-docker/issues/5654 requires commands be used in a Dockerfile build and not a running container.
- In order to …
> Remove default dependency on Docker CLI for generating Dockerfiles

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateEolAnnotationDataCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateEolAnnotationDataCommandTests.cs
Fixes #1507 by updating the `generateEolAnnotationData` command to not output digests which do not already exist in the registry.
> Exclude missing EOL digests from the EOL data output

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageCacheService.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateBuildMatrixCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Helpers/ManifestServiceHelper.cs
Fixes https://github.com/dotnet/docker-tools/issues/1516
In the scenario where this issue was discovered, it was the runtime image whose base runtime-deps image was being inspected to determine whether it had changed. So it was querying the registry the runtime-deps digest instead of accounting for the new locally built version of runtime-deps. Since runtime-deps was rebuilt then runtime should also be rebuilt. But since it had the digest from the registry and that matched what was in the image info, then it just used the cached image for runtime.
This fixes the logic by accounting for two different scenarios. In the build scenario, all base images will have either been built locally (if they are .NET base images) or pre-emptively pulled. Prior to this fix, the logic was not accounting …
> Image caching fix for locally built images

- eng/pipelines/dotnet-docker-tools-eng-validation.yml
This pipeline was using the incorrect template according to its "production/non-production" status.
> Use official pipeline template for eng validation

- eng/common/templates/jobs/build-images.yml
- eng/common/templates/stages/build-test-publish-repo.yml
This is a backport of https://github.com/dotnet/dotnet-docker/pull/5983/commits/a1e1e04d82916f0616effe5ff0f0aa4397a18623. This commit got lost in subsequent dotnet-docker /eng/common updates since it wasn't backported earlier.
> Re-enable pre-build validation for internal servicing testing

- eng/pipelines/mirror-base-images.yml
Matches the template to its "production" classification.
> Use official pipeline template for base image mirroring

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Helpers/ImageInfoHelper.cs
Related:
- #1185
To get a better understanding of #1185, I refactored both the `PullBaseImages` method as well as the build command's caching test.
For `PullBaseImages`, I tried to flatten the logic and fail early rather than having deeply nested conditionals. For the caching test, I used helper methods to shorten some of the object definitions and used Fluent Assertions to provide more actionable error messages.
Once I had a good understanding of how things worked, I added a failing test for #1185, which is commented out. I have a better idea of how to fix it in the `PullBaseImages` method now.
> Refactor PullBaseImages method and build command caching test

- eng/src/file-pusher/file-pusher.csproj
- src/Microsoft.DotNet.ImageBuilder/src/Microsoft.DotNet.ImageBuilder.csproj
I verified that these package versions are no longer needed for the issues/CVEs mentioned in the comments, due to changes in other package versions.
> Remove unnecessary pinned package versions

- .github/dependabot.yml
Part of https://github.com/dotnet/dotnet-docker-internal/issues/6178. This will automatically update any GitHub Actions the repo is using.
> Add dependabot configuration for updating GitHub Actions

- .github/dependabot.yml
Dependabot updates have been too frequent. This PR switches them from daily to weekly on Mondays. I also set the time of day so that new PRs should be ready to review by the time work starts on Mondays.
> Switch dependabot config to weekly

- .devcontainer/devcontainer.json
- src/Microsoft.DotNet.ImageBuilder/src/DockerService.cs
Fixes #1174
Remove workaround for BuildKit Dockerfile caching issue.
* Remove the code that sets the timestamp of the Dockerfile manually from `src/Microsoft.DotNet.ImageBuilder/src/DockerService.cs`.
* Add `tasks` section to `.devcontainer/devcontainer.json` with `test` and `build` commands.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/dotnet/docker-tools/pull/1603?shareId=6e251f9a-ff1e-4444-90c3-00ad6d03500d).
> Remove workaround for BuildKit Dockerfile caching issue

- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/TagInfo.cs
- src/Microsoft.DotNet.ImageBuilder/src/ViewModel/VariableHelper.cs
Reverts dotnet/docker-tools#1617
Reverting because these tags don't work the way we would like (see https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1378).
> Revert "Add back support for DockerfileGitCommitSha variable"

- eng/common/Install-DotNetSdk.ps1
Fixes #1644
Add retries to dotnet-install script invocation in `Install-DotNetSdk.ps1`.
* Wrap the invocation of the dotnet-install script with the `Invoke-WithRetry.ps1` script.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/dotnet/docker-tools/pull/1645?shareId=39687453-91c3-40ed-a4bb-e6c4d2fc95c0).
> Add retries to dotnet-install script invocation

- eng/common/Install-DotNetSdk.ps1
The default of 2 retries is still sometimes not enough ([see failure here](https://dev.azure.com/dnceng-public/public/_build/results?buildId=976323&view=logs&j=758d7417-7473-52bb-e4e7-358533cf3cc7&t=19da6720-ddc0-5c48-2855-b2005113be80&l=92)). This PR increases it to 5.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/dotnet/docker-tools/pull/1646?shareId=e466c049-d407-43ff-a481-3fd674f3296c).
> Add additional retries to dotnet-install script invocation

- eng/common/Install-DotNetSdk.ps1
dot.net just redirects to the CDN and it's currently having issues. Using the CDN directly was recommended by dnceng.
> Use CDN url for dotnet-install script instead of dot.net

- eng/common/Install-DotNetSdk.ps1
- eng/common/templates/jobs/cg-build-projects.yml
Since https://github.com/dotnet/dotnet-docker/pull/6348 added a .NET 10 project, we need CG pipeline to be able to build .NET 10 projects. However, we don't need to use .NET 10 across all downstream projects. So, this PR adds a parameter that allows pipelines to override the default .NET version.
> Add .NET version channel parameter to CG pipeline

- src/Microsoft.DotNet.ImageBuilder/src/Commands/Command.TOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GetStaleImagesOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GitOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/ManifestOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/Options.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PostPublishNotificationCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PostPublishNotificationOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishMcrDocsCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishMcrDocsOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/QueueBuildOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/GitHubClientFactory.cs
- src/Microsoft.DotNet.ImageBuilder/src/Helpers/JwtHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/IGitHubClientFactory.cs
- src/Microsoft.DotNet.ImageBuilder/src/IOctokitClientFactory.cs
- src/Microsoft.DotNet.ImageBuilder/src/NotificationService.cs
- src/Microsoft.DotNet.ImageBuilder/src/OctokitClientFactory.cs
- src/Microsoft.DotNet.ImageBuilder/src/SystemCommandLineExtensions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GetStaleImagesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishMcrDocsCommandTests.cs
Related: https://github.com/dotnet/docker-tools/issues/1637, https://github.com/dotnet/docker-tools/issues/1656, https://github.com/dotnet/dotnet-docker-internal/issues/7468
I tested this with a personal app installed on my account. It works with both Octokit and M.DN.VersionTools.Automation clients.
The GitHubAuth options needed to be refactored as well, since with #1660 I forgot that you also need the App Client ID for app authentication. I added support for arbitrary custom option validation to make that easier. The GH Auth option aliases were also renamed to give them all a common `gh-*` prefix to make them easier to see together in the CLI help output. This work is all in the first commit and can be reviewed separately.
Todo:
> Add GitHub App support

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GitOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/Helpers/JwtHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/OctokitClientFactory.cs
Requested by @dagood.
Using base64 encoded key is better because:
- We don't have to store the key on-disk
- Avoids issues with line-breaks and other escape characters when passing the key via CLI
Related: #1663
> Use base64 encoded private key for GitHub App auth

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/PublishImageInfoCommandTests.cs
fixes: https://github.com/dotnet/dotnet-docker-internal/issues/7806
When using GitHub App credentials, the image builder correctly generates an installation access token but was not using it during Git operations. Instead, the push relied on GitHubAuthOptions.AuthToken, which is empty in GitHub App scenarios. This caused LibGit2Sharp to fail with repeated redirects due to missing or invalid credentials.
This change ensures the installation token is retrieved via CreateGitHubTokenAsync and injected into both CloneOptions and PushOptions as a UsernamePasswordCredentials with the required "x-access-token" format.
> Fix GitHub App auth for Git push in PublishImageInfoCommand

- eng/pipelines/templates/jobs/check-base-image-updates.yml
A couple of GitHub token arguments were not defined as Azure Pipeline variables, so they were missed in https://github.com/dotnet/docker-tools/pull/1662. This PR updates them to use the new option format.
> Update other GitHub token arguments

- eng/common/templates/jobs/publish.yml
- eng/common/templates/steps/publish-readmes.yml
- eng/common/templates/variables/dotnet/build-test-publish.yml
Add `gitHubVersionsRepoInfo.authArgs` that we can change in microsoft/go-images to use an app rather than a token.
Override tested with:
```yml
- name: gitHubVersionsRepoInfo.authArgs
value: >-
--gh-private-key '$(BotAccount-bot-for-go-private-key)'
--gh-app-client-id '$(BotAccount-bot-for-go-client-id)'
--gh-app-installation-id '$(BotAccount-bot-for-go-installation)'
```
https://dev.azure.com/dnceng/internal/_build/results?buildId=2688959&view=results
> Add gitHubVersionsRepoInfo.authArgs configurable variable

- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/IngestKustoImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/IManifestService.cs
- src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/JsonHelper.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/ImageArtifactDetails.cs
- src/Microsoft.DotNet.ImageBuilder/src/Models/Image/PlatformData.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Helpers/ImageInfoHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Helpers/ManifestServiceHelper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/ImageArtifactDetailsTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/IngestKustoImageInfoCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/Microsoft.DotNet.ImageBuilder.Tests.csproj
> Add image/layer size to image-info and ingest in Kusto

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GitOptions.cs
- src/Microsoft.DotNet.ImageBuilder/src/OctokitClientFactory.cs
When doing a dry-run, sometimes we want to pass in un-resolved AzDO variables instead of placeholder variables. For example, `"$(myGitHubAppInstallationId)"`. That would fail, however, because the `--gh-app-installation-id` option always expected an int/long. This allows it to accept a string instead so those dry-run scenarios don't rely on actually converting whatever you pass in to a valid int/long, they can just be ignored instead.
Also, some minor code formatting/readability tweaks.
> Accept string instead of long for `--gh-app-installation-id` CLI option

- src/Microsoft.DotNet.ImageBuilder/src/CopyImageService.cs
During a dry run of image copy commands, the output currently looks like this:
```console
Importing '${acrName}/${publishRepoPrefix}/dotnet/nightly/runtime-deps:9.0-alpine3.21-aot-arm32v7' from '${imageStagingPath}/dotnet/nightly/runtime-deps:9.0-alpine3.21-aot-arm32v7'
```
That's misleading since it is not actually importing anything during a dry-run. This PR changes the output to be more clear that it's a dry run. Something like:
```console
(Dry run) Would have imported '${acrName}/${publishRepoPrefix}/dotnet/nightly/runtime-deps:9.0-alpine3.21-aot-arm32v7' from '${imageStagingPath}/dotnet/nightly/runtime-deps:9.0-alpine3.21-aot-arm32v7'
```
> Show different output when copying images during dry-run

- src/Microsoft.DotNet.ImageBuilder/src/ExecuteHelper.cs
When the `--dry-run` option is passed, it's useful to know whether or not a given command was actually executed when inspecting logs.
Related: https://github.com/dotnet/docker-tools/pull/1691
> Add "[DRY RUN]" to process execution output logging

- src/Microsoft.DotNet.ImageBuilder/src/Commands/IngestKustoImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Services/IKustoClient.cs
- src/Microsoft.DotNet.ImageBuilder/src/Services/KustoClientWrapper.cs
- src/Microsoft.DotNet.ImageBuilder/tests/IngestKustoImageInfoCommandTests.cs
- There was no logging when actually ingesting info into Kusto, or when skipping ingestion during a dry-run.
- The dryRun parameter of `IngestFromCsvAsync` was redundant. There is only one call-site for this command, which is already skipped during a dry-run.
> Add more logging to IngestKustoImageInfo command

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/GitService.cs
Before these changes, running PublishImageInfo would fail if there were no changes to commit. Now, it should skip committing and publishing and write a log message instead. I also added more logging to the command in general.
> Do not fail PublishImageInfo command when there are no changes to commit

- src/Microsoft.DotNet.ImageBuilder/src/Commands/Command.TOptions.cs
Related: #1508 
This CLI option never worked because of a typo/logic error. It tried to access the instance variable `Options` before `Initialize`, so it always returned false and never actually skipped the logging.
> Fix functionality of --no-version-logging CLI option

- eng/common/templates/variables/docker-images.yml
This commit was accidentally overwritten from https://github.com/dotnet/docker-tools/pull/1710, which is causing the [eng-validation](https://dev.azure.com/dnceng/internal/_build/results?buildId=2719401&view=results) pipeline to fail internally.
> Update Image Builder tag reference

- eng/pipelines/import-image.yml
- Fix build parallelism with service connection stage
- Add custom build number
- This makes it where you can tell what was imported by looking at the pipeline run. For example, importing `library/alpine:3.22` appends `-library_alpine_3.22` to the end of the build number.
> Minor improvements to import-image pipeline

- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateArtifactsCommand.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateReadmesCommandTests.cs
Cottle did not have a plain string find-and-replace function. This PR adds a custom `replace` function. Having this would make some parts of working with Dockerfile templates much simpler.
> Add string replace command to cottle templates

- eng/common/templates/steps/annotate-eol-digests.yml
Previously, it was impossible to skip the "Wait for Annotation Ingestion" task, even if `waitForIngestionEnabled` was set to false. This adds the missing condition so that the task can be skipped in case there is a problem with the MAR status API.
> Make EOL annotation ingestion pipeline task respect `waitForIngestionEnabled` variable

- src/Microsoft.DotNet.ImageBuilder/src/Commands/QueueBuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/PipelineHelper.cs
I did not notice that the `check-base-image-updates` pipeline was not queuing some builds because the pipeline reported a status of "success" (i.e. green checkmark). This PR will make the pipeline finish with status "succeeded with issues" (i.e. yellow exclamation point) whenever we know there are base image updates but decide not to queue a build for any reason.
> Set pipeline result to warning when auto builder skips queuing a build

- src/Microsoft.DotNet.ImageBuilder/src/Commands/PublishMcrDocsCommand.cs
This was a bug. It was causing issues when publishing readmes with the changes from https://github.com/dotnet/docker-tools/pull/1744. The Manifest directory is already prepended to the readme path in [ManifestInfo.Create](https://github.com/dotnet/docker-tools/blob/4617aa8afdeb9f27267e3f80dd7fc3f5cba1662e/src/Microsoft.DotNet.ImageBuilder/src/ViewModel/ManifestInfo.cs#L85-L89). It was applied a second time in PublishMcrDocsCommand, causing publishing to fail because it couldn't find the readme file.
Related: https://github.com/dotnet/dotnet-docker/pull/6563
> Remove duplicate manifest directory in Readme path in PublishMcrDocs command

- src/Microsoft.DotNet.ImageBuilder/src/Commands/MergeImageInfoCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/MergeImageInfoOptions.cs
- src/Microsoft.DotNet.ImageBuilder/tests/MergeImageInfoFilesCommandTests.cs
Part of https://github.com/dotnet/dotnet-docker/issues/6559.
The next step will be to add an option to the pipeline for triggering this behavior.
> Add option to override commit for new images in image info

- eng/common/templates/jobs/publish.yml
- eng/common/templates/stages/publish.yml
This PR is part of https://github.com/dotnet/dotnet-docker/issues/6559.
This depends on new version of ImageBuilder with the `--commit-override` CLI option from #1749. Which will be published shortly.
> Add pipeline option for overriding image info commit SHA 

- eng/common/templates/stages/dotnet/publish.yml
Small backport from https://github.com/dotnet/dotnet-docker/pull/6578, this parameter should have been added in https://github.com/dotnet/docker-tools/pull/1751 but was missed.
> Add missing commit override parameter to publish stage

- eng/common/templates/1es-official.yml
- eng/common/templates/1es-unofficial.yml
- eng/common/templates/stages/setup-service-connections.yml
If no service connections are specified, this stage shouldn't be included. Also, it doesn't need to check out the repo (saves 40-50 seconds).
> Optimize service connection setup stage

- eng/common/templates/variables/dotnet/build-test-publish.yml
- eng/common/templates/variables/dotnet/common.yml
- eng/common/templates/variables/dotnet/secrets.yml
- eng/pipelines/check-base-image-updates.yml
- eng/pipelines/dotnet-buildtools-image-builder-official.yml
- eng/pipelines/import-image.yml
- eng/pipelines/mirror-base-images.yml
- eng/pipelines/push-common-updates.yml
- eng/pipelines/update-image-builder-tag.yml
Previously, the secrets variable group was referenced from all internal pipelines. This made some pipelines over-privileged. Now, secrets should be referenced only by pipelines that need them. Additionally, pipelines that need them should reference them at the top-level template only, so that it's obvious which ones are using secrets.
> Move secrets into separate variable group

- src/Microsoft.DotNet.ImageBuilder/src/LifecycleMetadataService.cs
The changes from https://github.com/dotnet/docker-tools/pull/1768 are causing an error in dry runs:
```
-- EXECUTING [DRY RUN]: oras attach --artifact-type application/vnd.microsoft.artifact.lifecycle --annotation "vnd.microsoft.artifact.lifecycle.end-of-life.date=2025-08-20" --format json $(acr-staging.server)/mirror/ubuntu.azurecr.io/ubuntu:noble
Unhandled exception: System.Exception: Unable to deserialize manifest
at Microsoft.DotNet.ImageBuilder.LifecycleMetadataService.AnnotateEolDigest(String digest, DateOnly date, Boolean isDryRun, Manifest& lifecycleArtifactManifest) in /image-builder/src/LifecycleMetadataService.cs:line 67
at Microsoft.DotNet.ImageBuilder.Commands.CopyBaseImagesCommand.ExecuteAsync() in /image-builder/src/Commands/CopyBaseImagesCommand.cs:line 88
```
This handles …
> Handle dry run for EOL annotation

- src/Microsoft.DotNet.ImageBuilder/src/Commands/AnnotateEolDigestsCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CleanAcrImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/CopyBaseImagesCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateEolAnnotationDataCommand.cs
- src/Microsoft.DotNet.ImageBuilder/src/ILifecycleMetadataService.cs
- src/Microsoft.DotNet.ImageBuilder/src/LifecycleMetadataService.cs
- src/Microsoft.DotNet.ImageBuilder/tests/AnnotateEolDigestsCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/BuildCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/CleanAcrImagesCommandTest.cs
- src/Microsoft.DotNet.ImageBuilder/tests/CopyBaseImagesCommandTests.cs
- src/Microsoft.DotNet.ImageBuilder/tests/GenerateEolAnnotationDataCommandTests.cs
This reverts commit ba17c975099ea57a81c6e10bb4228f4401243b5a because it causes build failures on Windows agents:
```
Unhandled exception: System.ComponentModel.Win32Exception (0x80004005): An error occurred trying to start process 'oras' with working directory 'D:\a\_work\1\s'. The operation completed successfully.
```
Related to #1768, https://github.com/dotnet/dotnet-docker-internal/issues/7673
> Revert "Set EOL annotation for staged images and mirrored base images" (#1768)

- eng/pipelines/update-image-builder-tag.yml
The imagebuilder pipeline was renamed to `docker-tools-imagebuilder-official`, which caused this pipeline to start failing. It would be better to reference the pipeline by its ID, but I couldn't find a way to do that for pipeline resources.
> Update imagebuilder pipeline source name

- eng/common/templates/jobs/publish.yml
- eng/common/templates/steps/set-dry-run.yml
Fixes #1781. This was left out of https://github.com/dotnet/docker-tools/pull/1771.
I also removed the default value so it will error if it's not passed in.
> Pass publishConfig through set-dry-run.yml template

- eng/common/templates/steps/annotate-eol-digests.yml
The changes from https://github.com/dotnet/docker-tools/pull/1810 cause the following error in the `Annotations` job when publishing the annotation artifact for the public mirror ACR: `##[error]Artifact annotation-digests-1 already exists for build 2801090`.
This is because it's the second time that annotations are being published in the same job and, in both instances, the artifact name is the same between them.
Fixed by using the ACR name in the artifact name to provide uniqueness.
The artifact is only meant for manual troubleshooting. No automation currently reads this artifact.
> Use unique artifact name for annotations

- eng/common/templates/steps/clean-acr-images.yml
- eng/pipelines/templates/steps/set-eol-annotations.yml
- src/ImageBuilder/Commands/CleanAcrImagesOptions.cs
The goal of this change is to make it easier to tell what the ACR cleanup pipelines are doing at a glance from the Azure Pipelines UI.
> Add ACR clean action to pipeline step display names
